import { describe, it, expect } from "vitest";
import {
  PROFILE,
  renderRoadmap,
  renderGantt,
  renderAgentBoard,
} from "../plugins/planning/index.js";
import type {
  PrimitiveInstance,
  RelationInstance,
} from "../src/core/models/instance.js";
import type { RendererInput } from "../src/plugin/types.js";

/**
 * Renderer tests. Each renderer is called directly (NOT through
 * Host.runRenderer) with a hand-built RendererInput so the tests are
 * resilient to host-layer faults unrelated to the planning plugin.
 *
 * Intent:
 *   - the three renderers each accept the documented input and produce
 *     output of the declared MIME type;
 *   - output contains the documented landmarks (so a regression that
 *     drops a section is caught);
 *   - output is well-formed enough to embed in downstream pipelines:
 *       Roadmap / AgentBoard: valid UTF-8;
 *       Gantt: valid SVG (single <svg> root, viewBox set, has <title>).
 */

function task(
  id: string,
  fields: Record<string, unknown>,
): PrimitiveInstance {
  return {
    id,
    type_id: "plan:Task",
    field_values: fields,
    revision: 0,
  };
}
function ac(id: string, fields: Record<string, unknown>): PrimitiveInstance {
  return {
    id,
    type_id: "plan:AcceptanceCriterion",
    field_values: fields,
    revision: 0,
  };
}
function blocker(
  id: string,
  fields: Record<string, unknown>,
): PrimitiveInstance {
  return {
    id,
    type_id: "plan:Blocker",
    field_values: fields,
    revision: 0,
  };
}
function iteration(
  id: string,
  fields: Record<string, unknown>,
): PrimitiveInstance {
  return {
    id,
    type_id: "plan:Iteration",
    field_values: fields,
    revision: 0,
  };
}
function wbs(id: string, fields: Record<string, unknown>): PrimitiveInstance {
  return {
    id,
    type_id: "plan:WorkBreakdown",
    field_values: fields,
    revision: 0,
  };
}
function rel(
  id: string,
  type_id: string,
  source_id: string,
  target_id: string,
  field_values: Record<string, unknown> = {},
): RelationInstance {
  return { id, type_id, source_id, target_id, field_values, revision: 0 };
}

function input(
  primitives: PrimitiveInstance[],
  relations: RelationInstance[] = [],
): RendererInput {
  return {
    workbookId: "demo",
    profile: PROFILE,
    primitives,
    relations,
  };
}

// ---------------------------------------------------------------------------
// plan:RoadmapRenderer
// ---------------------------------------------------------------------------

describe("plan:RoadmapRenderer (text/markdown)", () => {
  it("emits the documented header with task / iteration / breakdown counts", async () => {
    const out = await renderRoadmap(input([], []));
    expect(out.contentType).toBe("text/markdown");
    expect(out.filename).toBe("roadmap.md");
    const md = new TextDecoder("utf-8", { fatal: true }).decode(out.bytes);
    expect(md).toContain("# demo — Roadmap");
    expect(md).toContain("Generated by `plan:RoadmapRenderer`");
    expect(md).toContain("0 tasks");
    expect(md).toContain("0 iterations");
    expect(md).toContain("0 breakdowns");
  });

  it("groups tasks by iteration, then by status, in declared status order", async () => {
    const it1 = iteration("iteration:s1", {
      name: "sprint-1",
      start_date: "2026-05-01",
      end_date: "2026-05-14",
      goal: "Land the planning plugin",
    });
    const t1 = task("task:in-progress", {
      name: "in-progress task",
      summary: "Doing it now",
      kind: "Implementation",
      executor_kind: "AI",
      ai_minutes: 30,
      status: "In_progress",
      priority: "P1",
      assignee_id: "actor:Bot:builder",
    });
    const t2 = task("task:ready", {
      name: "ready task",
      summary: "Next up",
      kind: "Test",
      executor_kind: "Human",
      human_estimate: "2h",
      status: "Ready",
      priority: "P2",
    });
    const t3 = task("task:backlog", {
      name: "backlog task",
      summary: "Later",
      kind: "Documentation",
      executor_kind: "Human",
      human_estimate: "1d",
      status: "Backlog",
      priority: "P3",
    });
    const md = new TextDecoder().decode(
      (
        await renderRoadmap(
          input(
            [it1, t1, t2, t3],
            [
              rel("rel:1", "plan:InIteration", "task:in-progress", "iteration:s1"),
              rel("rel:2", "plan:InIteration", "task:ready", "iteration:s1"),
              rel("rel:3", "plan:InIteration", "task:backlog", "iteration:s1"),
            ],
          ),
        )
      ).bytes,
    );
    expect(md).toContain("## Iterations");
    expect(md).toContain("`iteration:s1`");
    expect(md).toContain("[2026-05-01 → 2026-05-14]");
    expect(md).toContain("Land the planning plugin");
    // Status order: In_progress before Ready before Backlog.
    const ipIdx = md.indexOf("**In_progress**");
    const readyIdx = md.indexOf("**Ready**");
    const backlogIdx = md.indexOf("**Backlog**");
    expect(ipIdx).toBeGreaterThan(0);
    expect(readyIdx).toBeGreaterThan(ipIdx);
    expect(backlogIdx).toBeGreaterThan(readyIdx);
    // AI duration badge appears for AI task.
    expect(md).toContain("⏱30m");
    // Human estimate appears for human task.
    expect(md).toContain("⏱2h");
    // Assignee badge appears.
    expect(md).toContain("👤actor:Bot:builder");
  });

  it("renders a Work Breakdown section when wbs primitives exist", async () => {
    const w = wbs("wbs:demo", {
      name: "demo",
      summary: "demo breakdown",
      status: "Active",
    });
    const t = task("task:demo", {
      name: "t",
      summary: "in wbs",
      kind: "Implementation",
      executor_kind: "AI",
      ai_minutes: 15,
      status: "Ready",
      priority: "P2",
    });
    const md = new TextDecoder().decode(
      (
        await renderRoadmap(
          input([w, t], [rel("rel:c", "plan:Contains", "wbs:demo", "task:demo")]),
        )
      ).bytes,
    );
    expect(md).toContain("## Work Breakdown");
    expect(md).toContain("`wbs:demo`");
    expect(md).toContain("demo breakdown");
    expect(md).toContain("`task:demo`");
  });

  it("surfaces only ACTIVE blockers (resolved_at empty)", async () => {
    const b1 = blocker("blocker:active", {
      description: "active blocker",
      severity: "High",
      discovered_at: "2026-05-04",
    });
    const b2 = blocker("blocker:resolved", {
      description: "resolved blocker",
      severity: "Low",
      discovered_at: "2026-05-01",
      resolved_at: "2026-05-03",
    });
    const md = new TextDecoder().decode(
      (await renderRoadmap(input([b1, b2], []))).bytes,
    );
    expect(md).toContain("## Active blockers (1)");
    expect(md).toContain("`blocker:active`");
    expect(md).not.toContain("`blocker:resolved`");
  });

  it("surfaces loose tasks (no iteration, no contains, no subtask) under their own header", async () => {
    const t = task("task:loose", {
      name: "loose",
      summary: "no parent",
      kind: "Investigation",
      executor_kind: "AI",
      ai_minutes: 10,
      status: "Backlog",
      priority: "P3",
      is_root: true,
    });
    const md = new TextDecoder().decode(
      (await renderRoadmap(input([t], []))).bytes,
    );
    expect(md).toContain("## Loose tasks");
    expect(md).toContain("`task:loose`");
  });
});

// ---------------------------------------------------------------------------
// plan:AgentBoardRenderer
// ---------------------------------------------------------------------------

describe("plan:AgentBoardRenderer (text/markdown)", () => {
  it("emits a documented header and the Available-to-claim queue", async () => {
    const t = task("task:claimable", {
      name: "claimable",
      summary: "ready and unclaimed",
      kind: "Implementation",
      executor_kind: "AI",
      ai_minutes: 20,
      status: "Ready",
      priority: "P1",
    });
    const out = await renderAgentBoard(input([t]));
    expect(out.contentType).toBe("text/markdown");
    expect(out.filename).toBe("board.md");
    const md = new TextDecoder("utf-8", { fatal: true }).decode(out.bytes);
    expect(md).toContain("# demo — Agent Board");
    expect(md).toContain("## 🎯 Available to claim");
    expect(md).toContain("`task:claimable`");
  });

  it("excludes Ready tasks with non-stale claims from the available queue", async () => {
    const future = new Date(Date.now() + 60 * 60 * 1000).toISOString();
    const t = task("task:claimed", {
      name: "claimed",
      summary: "ready but claimed",
      kind: "Implementation",
      executor_kind: "AI",
      ai_minutes: 30,
      status: "Ready",
      priority: "P1",
      claim_holder_id: "actor:Bot:other",
      claim_until: future,
    });
    const md = new TextDecoder().decode(
      (await renderAgentBoard(input([t]))).bytes,
    );
    expect(md).toContain("## 🎯 Available to claim");
    // The available section says "no tasks available" because the only
    // Ready task is non-stale-claimed.
    const availableSection = md.split("---")[0]!;
    expect(availableSection).toContain("No tasks available");
    expect(availableSection).not.toContain("`task:claimed`");
  });

  it("includes Ready tasks whose claim is STALE (claim_until in the past) in available queue with 🔄STALE marker", async () => {
    const past = new Date(Date.now() - 60 * 60 * 1000).toISOString();
    const t = task("task:stale", {
      name: "stale",
      summary: "claim expired",
      kind: "Implementation",
      executor_kind: "AI",
      ai_minutes: 25,
      status: "Ready",
      priority: "P0",
      claim_holder_id: "actor:Bot:zombie",
      claim_until: past,
    });
    const md = new TextDecoder().decode(
      (await renderAgentBoard(input([t]))).bytes,
    );
    const availableSection = md.split("---")[0]!;
    expect(availableSection).toContain("`task:stale`");
    expect(availableSection).toContain("🔄STALE");
  });

  it("groups tasks by assignee and shows unassigned tasks last", async () => {
    const tA = task("task:alice", {
      name: "alice's",
      summary: "for alice",
      kind: "Implementation",
      executor_kind: "Human",
      human_estimate: "1d",
      status: "In_progress",
      priority: "P1",
      assignee_id: "actor:Person:alice",
    });
    const tU = task("task:floating", {
      name: "floating",
      summary: "no assignee",
      kind: "Implementation",
      executor_kind: "AI",
      ai_minutes: 15,
      status: "Backlog",
      priority: "P2",
    });
    const md = new TextDecoder().decode(
      (await renderAgentBoard(input([tA, tU]))).bytes,
    );
    const aliceIdx = md.indexOf("## 👤 actor:Person:alice");
    const unassignedIdx = md.indexOf("## Unassigned");
    expect(aliceIdx).toBeGreaterThan(0);
    expect(unassignedIdx).toBeGreaterThan(aliceIdx);
  });
});

// ---------------------------------------------------------------------------
// plan:GanttSvgRenderer
// ---------------------------------------------------------------------------

describe("plan:GanttSvgRenderer (image/svg+xml)", () => {
  it("emits a syntactically valid SVG with viewBox and a <title>", async () => {
    const out = await renderGantt(input([], []));
    expect(out.contentType).toBe("image/svg+xml");
    expect(out.filename).toBe("gantt.svg");
    const svg = new TextDecoder("utf-8", { fatal: true }).decode(out.bytes);
    expect(svg.startsWith("<?xml")).toBe(true);
    expect(svg).toContain("<svg");
    expect(svg).toContain('xmlns="http://www.w3.org/2000/svg"');
    expect(svg).toContain("viewBox=");
    expect(svg).toContain("<title>demo — Gantt</title>");
    expect(svg).toContain("</svg>");
  });

  it("draws one <rect> per scheduled task", async () => {
    const t1 = task("task:a", {
      name: "a",
      summary: "scheduled a",
      kind: "Implementation",
      executor_kind: "AI",
      ai_minutes: 30,
      status: "In_progress",
      priority: "P1",
      planned_start: "2026-05-01",
      planned_finish: "2026-05-05",
    });
    const t2 = task("task:b", {
      name: "b",
      summary: "scheduled b",
      kind: "Test",
      executor_kind: "Human",
      human_estimate: "2d",
      status: "Ready",
      priority: "P2",
      planned_start: "2026-05-06",
      planned_finish: "2026-05-08",
    });
    const svg = new TextDecoder().decode(
      (await renderGantt(input([t1, t2]))).bytes,
    );
    const rectCount = (svg.match(/<rect /g) ?? []).length;
    expect(rectCount).toBe(2);
    expect(svg).toContain("task:a");
    expect(svg).toContain("task:b");
    expect(svg).toContain("2026-05-01");
    expect(svg).toContain("2026-05-08");
  });

  it("lists unscheduled tasks in the footer block", async () => {
    const t = task("task:undated", {
      name: "undated",
      summary: "no planned dates",
      kind: "Investigation",
      executor_kind: "AI",
      ai_minutes: 10,
      status: "Backlog",
      priority: "P3",
    });
    const svg = new TextDecoder().decode(
      (await renderGantt(input([t]))).bytes,
    );
    expect(svg).toContain("Unscheduled (1)");
    expect(svg).toContain("task:undated");
  });

  it("encodes status via fill colour and executor_kind via stroke class", async () => {
    const tAi = task("task:ai", {
      name: "ai",
      summary: "ai task",
      kind: "Implementation",
      executor_kind: "AI",
      ai_minutes: 15,
      status: "In_progress",
      priority: "P1",
      planned_start: "2026-05-01",
      planned_finish: "2026-05-02",
    });
    const tHuman = task("task:human", {
      name: "human",
      summary: "human task",
      kind: "Implementation",
      executor_kind: "Human",
      human_estimate: "1h",
      status: "Blocked",
      priority: "P0",
      planned_start: "2026-05-03",
      planned_finish: "2026-05-03",
    });
    const svg = new TextDecoder().decode(
      (await renderGantt(input([tAi, tHuman]))).bytes,
    );
    // In_progress → green; Blocked → red.
    expect(svg).toContain('fill="#10b981"'); // green
    expect(svg).toContain('fill="#ef4444"'); // red
    expect(svg).toContain('class="bar-ai"');
    expect(svg).toContain('class="bar-human"');
  });

  it("escapes XML metacharacters in task names and ids (no injection)", async () => {
    const t = task("task:nasty", {
      // Mix all five XML-sensitive characters in fields the renderer
      // emits unconditionally: name (in <title> tooltip) and id.
      name: '<script>alert("x") & y</script>',
      summary: "short",
      kind: "Investigation",
      executor_kind: "AI",
      ai_minutes: 5,
      status: "Backlog",
      priority: "P3",
      planned_start: "2026-05-01",
      planned_finish: "2026-05-01",
    });
    const svg = new TextDecoder().decode(
      (await renderGantt(input([t]))).bytes,
    );
    // No literal <script> survives. Both `<` and `&` are escaped.
    expect(svg).not.toContain("<script>");
    expect(svg).toContain("&lt;script&gt;");
    expect(svg).toContain("&amp;");
    expect(svg).toContain("&quot;");
  });
});

// ---------------------------------------------------------------------------
// plan:GanttSvgRenderer — the canvas must contain what is drawn on it
// ---------------------------------------------------------------------------

/**
 * SVG clips at its viewport, silently. A drawing wider than its own `viewBox`
 * is not a cosmetic defect — the glyphs past the edge are computed, written to
 * the file, and then discarded by every renderer that opens it, with no error
 * anywhere. These tests hold the canvas to the text.
 *
 * The width the tests measure with is deliberately NOT the renderer's own
 * estimator: `0.5em` per character is below the true advance of any realistic
 * sans-serif run, so it is a lower bound on the space the text needs. A
 * viewBox that fails to contain even the lower bound is clipping for certain.
 */
const LOWER_BOUND_EM = 0.5;

function atLeastWidth(s: string, fontSize: number): number {
  return s.length * fontSize * LOWER_BOUND_EM;
}

function viewBoxOf(svg: string): { width: number; height: number } {
  const m = /viewBox="0 0 ([\d.]+) ([\d.]+)"/.exec(svg);
  if (m === null) throw new Error("no viewBox on the rendered SVG");
  return { width: Number(m[1]), height: Number(m[2]) };
}

/** Every `<text>` element as drawn: its class, its x, and its content. */
function textsOf(svg: string): { cls: string; x: number; body: string }[] {
  return [
    ...svg.matchAll(/<text class="([^"]+)" x="([\d.]+)" y="[\d.]+">([^<]*)/g),
  ].map((m) => ({ cls: m[1]!, x: Number(m[2]), body: m[3]! }));
}

const FONT_SIZE: Record<string, number> = {
  title: 16,
  subtitle: 11,
  "axis-label": 10,
  "row-label": 12,
  "row-label-summary": 10,
  "now-label": 10,
  "bar-text": 10,
  "unscheduled-header": 12,
  "unscheduled-row": 11,
};

function longSummaryTask(id: string, summary: string): PrimitiveInstance {
  return task(id, {
    name: id,
    summary,
    kind: "Implementation",
    executor_kind: "Either",
    ai_minutes: 30,
    status: "Ready",
    priority: "P2",
  });
}

describe("plan:GanttSvgRenderer — canvas fits its text", () => {
  it("sizes the viewBox from the unscheduled footer, not the timeline alone", async () => {
    /* The reported defect: 22 undated tasks with paragraph-length summaries
       produced viewBox="0 0 424 556" — the timeline width — while the rows ran
       to roughly 1800 units. Three quarters of every line was clipped. */
    const summary =
      "Add StudioHostAdapter.render(workbookId, target, renderer?) wrapping " +
      "renderProject from @fdpm/cli sdk.ts:836, which assembles the renderer " +
      "envelope from workbook state. Same path the fdpm:// MCP render resource uses.";
    const tasks = Array.from({ length: 22 }, (_, i) =>
      longSummaryTask(`task:undated-${i}`, summary),
    );
    const svg = new TextDecoder().decode((await renderGantt(input(tasks))).bytes);
    const { width } = viewBoxOf(svg);

    const rows = textsOf(svg).filter((t) => t.cls === "unscheduled-row");
    expect(rows).toHaveLength(22);
    for (const row of rows) {
      expect(row.x + atLeastWidth(row.body, FONT_SIZE["unscheduled-row"]!)).toBeLessThanOrEqual(
        width,
      );
    }
    // Timeline-only sizing is what the defect was; the canvas must exceed it.
    expect(width).toBeGreaterThan(240 + 24 * 7 + 16);
  });

  it("holds every drawn string inside the viewBox", async () => {
    const scheduledTask = task("task:a-rather-long-identifier-for-the-gutter", {
      name: "WWWWW MMMMM WWWWW MMMMM WWWWW",
      summary: "A summary of exactly thirty-eight chars",
      kind: "Implementation",
      executor_kind: "AI",
      ai_minutes: 30,
      status: "In_progress",
      priority: "P1",
      planned_start: "2026-05-01",
      planned_finish: "2026-05-04",
    });
    const svg = new TextDecoder().decode(
      (await renderGantt(input([scheduledTask, longSummaryTask("task:u", "x".repeat(400))])))
        .bytes,
    );
    const { width } = viewBoxOf(svg);
    for (const t of textsOf(svg)) {
      const size = FONT_SIZE[t.cls];
      expect(size, `unmeasured text class: ${t.cls}`).toBeDefined();
      expect(
        t.x + atLeastWidth(t.body, size!),
        `${t.cls} at x=${t.x} runs past the ${width}-unit viewBox: ${t.body}`,
      ).toBeLessThanOrEqual(width);
    }
  });

  it("widens the canvas so a long workbook id's title stays inside it", async () => {
    const svg = new TextDecoder().decode(
      (
        await renderGantt({
          ...input([]),
          workbookId: "studio-legacy-web-consolidation-with-a-very-long-name",
        })
      ).bytes,
    );
    const { width } = viewBoxOf(svg);
    const title = textsOf(svg).find((t) => t.cls === "title")!;
    expect(title.body).toContain("studio-legacy-web-consolidation");
    expect(title.x + atLeastWidth(title.body, 16)).toBeLessThanOrEqual(width);
  });

  it("elides an over-long footer row and keeps the full text in a <title>", async () => {
    const summary = "y".repeat(400);
    const svg = new TextDecoder().decode(
      (await renderGantt(input([longSummaryTask("task:u", summary)]))).bytes,
    );
    const row = /<text class="unscheduled-row"[^>]*>([^<]*)<title>([^<]*)<\/title>/.exec(svg);
    expect(row, "an elided row must carry the whole row as a tooltip").not.toBeNull();
    expect(row![1]!.endsWith("…")).toBe(true);
    expect(row![1]!.length).toBeLessThan(row![2]!.length);
    expect(row![2]).toContain(summary);
  });

  it("does not elide a footer row that already fits, and adds no tooltip", async () => {
    const svg = new TextDecoder().decode(
      (await renderGantt(input([longSummaryTask("task:u", "short summary")]))).bytes,
    );
    expect(svg).toContain("task:u [Ready/Either] — short summary</text>");
    expect(svg).not.toContain("…");
  });

  it("spaces date labels so two never overlap", async () => {
    /* Seven days at 24px each cannot carry a 10-character date every day. The
       old rule aimed at ~12 labels whatever their width and printed them on
       top of one another. */
    const t = task("task:a", {
      name: "a",
      summary: "s",
      kind: "Implementation",
      executor_kind: "AI",
      ai_minutes: 30,
      status: "Ready",
      priority: "P1",
      planned_start: "2026-05-01",
      planned_finish: "2026-05-07",
    });
    const svg = new TextDecoder().decode((await renderGantt(input([t]))).bytes);
    const labels = textsOf(svg).filter((l) => l.cls === "axis-label");
    expect(labels.length).toBeGreaterThan(1);
    for (let i = 1; i < labels.length; i += 1) {
      const previousRight =
        labels[i - 1]!.x + atLeastWidth(labels[i - 1]!.body, FONT_SIZE["axis-label"]!);
      expect(labels[i]!.x).toBeGreaterThanOrEqual(previousRight);
    }
  });

  it("knocks the day grid out from behind the empty-state note", async () => {
    /* With nothing scheduled the note is drawn inside the grid band. Day
       rules struck through the one sentence a reader has is a drawing that
       looks broken, which is the whole complaint this suite exists for. */
    const svg = new TextDecoder().decode((await renderGantt(input([]))).bytes);
    const note = textsOf(svg).find((t) => t.cls === "row-label-summary")!;
    expect(note.body).toContain("No tasks have planned_start");

    const knockout =
      /<rect x="([\d.]+)" y="[\d.]+" width="([\d.]+)" height="[\d.]+" fill="#ffffff" \/>/.exec(
        svg,
      );
    expect(knockout, "the note needs a ground of its own").not.toBeNull();
    const left = Number(knockout![1]);
    const right = left + Number(knockout![2]);
    expect(left).toBeLessThanOrEqual(note.x);
    expect(right).toBeGreaterThanOrEqual(note.x + atLeastWidth(note.body, 10));
    // It is a ground, so it is painted before the text it sits under.
    expect(svg.indexOf(knockout![0])).toBeLessThan(svg.indexOf(note.body));
  });

  it("keeps a gutter label out of the chart area", async () => {
    const t = task("task:an-identifier-far-too-long-for-a-240-unit-gutter-column", {
      name: "n",
      summary: "s",
      kind: "Implementation",
      executor_kind: "AI",
      ai_minutes: 30,
      status: "Ready",
      priority: "P1",
      planned_start: "2026-05-01",
      planned_finish: "2026-05-02",
    });
    const svg = new TextDecoder().decode((await renderGantt(input([t]))).bytes);
    const label = textsOf(svg).find((l) => l.cls === "row-label")!;
    expect(label.body.endsWith("…")).toBe(true);
    expect(label.x + atLeastWidth(label.body, 12)).toBeLessThanOrEqual(240);
  });
});
