import type { RendererFn, RendererOutput } from "../../../src/plugin/types.js";
import type { PrimitiveInstance } from "../../../src/core/models/instance.js";

/**
 * `text/markdown` renderer for planning projects.
 *
 * Layout:
 *   # <project_id> — Roadmap
 *   ## Iterations (chronological)
 *     for each iteration:
 *       - <name> [<start>..<end>]: <goal>
 *         - tasks bound via plan:InIteration, grouped by status
 *   ## Work Breakdown
 *     for each plan:WorkBreakdown root:
 *       - <name> (<status>): <summary>
 *         - tree of plan:Contains / plan:Subtask descendants
 *   ## Loose tasks (not in any iteration, not under any breakdown)
 *   ## Active blockers (resolved_at absent)
 *
 * No external libraries; pure string assembly. Output is valid GitHub-flavoured
 * Markdown.
 */

function fv<T = unknown>(p: PrimitiveInstance, key: string): T | undefined {
  return (p.field_values as Record<string, unknown>)[key] as T | undefined;
}

/**
 * Escape only the inline-significant Markdown characters that would
 * actually break parsing in a list item / heading: backslash, backtick,
 * asterisk, underscore, square brackets, and `<` (in case the input looks
 * like an HTML tag start). `(`/`)`/`{`/`}`/`>` are NOT inline-significant
 * outside link/image syntax — escaping them is over-eager and produces
 * ugly literal backslashes in rendered output (`\(slice 1-6\)`).
 */
function escapeMd(s: string): string {
  return s.replace(/([\\`*_\[\]<])/g, "\\$1");
}

const STATUS_ORDER = [
  "In_progress",
  "Ready",
  "Blocked",
  "In_review",
  "Backlog",
  "Done",
  "Cancelled",
] as const;

export const renderRoadmap: RendererFn = (input): RendererOutput => {
  const { primitives, relations, projectId, profile } = input;

  const tasks = primitives.filter((p) => p.type_id === "plan:Task");
  const iterations = primitives
    .filter((p) => p.type_id === "plan:Iteration")
    .slice()
    .sort((a, b) => {
      const sa = (fv<string>(a, "start_date") ?? "").trim();
      const sb = (fv<string>(b, "start_date") ?? "").trim();
      return sa.localeCompare(sb);
    });
  const breakdowns = primitives.filter((p) => p.type_id === "plan:WorkBreakdown");
  const blockers = primitives.filter((p) => p.type_id === "plan:Blocker");

  const taskById = new Map(tasks.map((t) => [t.id, t]));

  // Index task → iteration via plan:InIteration relations.
  const iterationOfTask = new Map<string, string>();
  for (const r of relations) {
    if (r.type_id === "plan:InIteration") iterationOfTask.set(r.source_id, r.target_id);
  }
  const tasksByIteration = new Map<string, string[]>();
  for (const t of tasks) {
    const it = iterationOfTask.get(t.id);
    if (!it) continue;
    const arr = tasksByIteration.get(it) ?? [];
    arr.push(t.id);
    tasksByIteration.set(it, arr);
  }

  // Index breakdown → contained tasks via plan:Contains.
  const containsByWbs = new Map<string, string[]>();
  for (const r of relations) {
    if (r.type_id === "plan:Contains") {
      const arr = containsByWbs.get(r.source_id) ?? [];
      arr.push(r.target_id);
      containsByWbs.set(r.source_id, arr);
    }
  }

  const lines: string[] = [];
  lines.push(`# ${projectId} — Roadmap`);
  lines.push("");
  lines.push(
    `> Profile: \`${profile.id}\` v${profile.version}. Generated by \`plan:RoadmapRenderer\` from ${tasks.length} task${tasks.length === 1 ? "" : "s"}, ${iterations.length} iteration${iterations.length === 1 ? "" : "s"}, ${breakdowns.length} breakdown${breakdowns.length === 1 ? "" : "s"}.`,
  );
  lines.push("");

  // Iterations section.
  if (iterations.length > 0) {
    lines.push("## Iterations");
    lines.push("");
    for (const it of iterations) {
      const name = fv<string>(it, "name") ?? it.id;
      const start = fv<string>(it, "start_date") ?? "?";
      const end = fv<string>(it, "end_date") ?? "?";
      const goal = (fv<string>(it, "goal") ?? "").trim();
      lines.push(
        `### \`${it.id}\` — ${escapeMd(name)} [${start} → ${end}]${goal ? ` — ${escapeMd(goal)}` : ""}`,
      );
      lines.push("");
      const itTasks = (tasksByIteration.get(it.id) ?? [])
        .map((id) => taskById.get(id))
        .filter((t): t is PrimitiveInstance => !!t);
      if (itTasks.length === 0) {
        lines.push("_No tasks bound to this iteration._");
        lines.push("");
        continue;
      }
      const byStatus = new Map<string, PrimitiveInstance[]>();
      for (const t of itTasks) {
        const s = fv<string>(t, "status") ?? "Backlog";
        const arr = byStatus.get(s) ?? [];
        arr.push(t);
        byStatus.set(s, arr);
      }
      for (const status of STATUS_ORDER) {
        const xs = byStatus.get(status);
        if (!xs || xs.length === 0) continue;
        lines.push(`**${status}** (${xs.length}):`);
        for (const t of xs) lines.push(formatTaskLine(t));
        lines.push("");
      }
    }
    lines.push("---");
    lines.push("");
  }

  // Work breakdowns section.
  if (breakdowns.length > 0) {
    lines.push("## Work Breakdown");
    lines.push("");
    for (const wbs of breakdowns) {
      const name = fv<string>(wbs, "name") ?? wbs.id;
      const status = fv<string>(wbs, "status") ?? "?";
      const summary = (fv<string>(wbs, "summary") ?? "").trim();
      lines.push(
        `### \`${wbs.id}\` — ${escapeMd(name)} _(${status})_${summary ? ` — ${escapeMd(summary)}` : ""}`,
      );
      lines.push("");
      const childIds = containsByWbs.get(wbs.id) ?? [];
      if (childIds.length === 0) {
        lines.push("_Empty breakdown._");
        lines.push("");
        continue;
      }
      for (const cid of childIds) {
        const child = primitives.find((p) => p.id === cid);
        if (!child) {
          lines.push(`- \`${cid}\` _(missing)_`);
          continue;
        }
        if (child.type_id === "plan:Task") {
          lines.push(formatTaskLine(child));
        } else {
          // Nested breakdown — render its name only; the next iteration of
          // the outer loop renders its own children.
          const cname = fv<string>(child, "name") ?? child.id;
          lines.push(`- \`${child.id}\` (sub-breakdown: ${escapeMd(cname)})`);
        }
      }
      lines.push("");
    }
    lines.push("---");
    lines.push("");
  }

  // Loose tasks.
  const containedTaskIds = new Set<string>();
  for (const ids of containsByWbs.values()) {
    for (const id of ids) containedTaskIds.add(id);
  }
  for (const r of relations) {
    if (r.type_id === "plan:Subtask") containedTaskIds.add(r.source_id);
  }
  const looseTasks = tasks.filter(
    (t) => !iterationOfTask.has(t.id) && !containedTaskIds.has(t.id),
  );
  if (looseTasks.length > 0) {
    lines.push("## Loose tasks (not in iteration, not contained)");
    lines.push("");
    for (const t of looseTasks) lines.push(formatTaskLine(t));
    lines.push("");
    lines.push("---");
    lines.push("");
  }

  // Active blockers.
  const activeBlockers = blockers.filter(
    (b) => !((fv<string>(b, "resolved_at") ?? "").trim().length > 0),
  );
  if (activeBlockers.length > 0) {
    lines.push(`## Active blockers (${activeBlockers.length})`);
    lines.push("");
    for (const b of activeBlockers) {
      const desc = (fv<string>(b, "description") ?? "").trim();
      const sev = fv<string>(b, "severity") ?? "?";
      const ext = (fv<string>(b, "external_ref") ?? "").trim();
      lines.push(
        `- \`${b.id}\` _(${sev})_ — ${escapeMd(desc)}${ext ? ` _(ref: ${ext})_` : ""}`,
      );
    }
    lines.push("");
  }

  return toOutput(lines);
};

function formatTaskLine(t: PrimitiveInstance): string {
  const id = t.id;
  const name = fv<string>(t, "name") ?? id;
  const summary = (fv<string>(t, "summary") ?? "").trim();
  const exec = fv<string>(t, "executor_kind") ?? "?";
  const ai = fv<number>(t, "ai_minutes");
  const human = fv<string>(t, "human_estimate");
  const priority = fv<string>(t, "priority") ?? "?";
  const status = fv<string>(t, "status") ?? "?";
  const assignee = fv<string>(t, "assignee_id");
  let durBadge = "";
  if (exec === "AI" && typeof ai === "number") durBadge = ` ⏱${ai}m`;
  else if (typeof human === "string" && human.trim().length > 0) durBadge = ` ⏱${human}`;
  return `- [${status}] \`${id}\` _(${exec}/${priority})_${durBadge}${assignee ? ` 👤${assignee}` : ""} — ${escapeMd(summary || name)}`;
}

function toOutput(lines: string[]): RendererOutput {
  const text = lines.join("\n");
  return {
    bytes: new TextEncoder().encode(text),
    contentType: "text/markdown",
    filename: "roadmap.md",
  };
}
