/**
 * Re-vendor schemas/uixo-native.ts from its upstream generator output.
 *
 * WHY A SCRIPT. The upstream file is itself generated ("GENERATED by
 * generate-native.ts ... Do not hand-edit; regenerate instead") in another
 * repository, under a tsconfig that does not set
 * `noUncheckedIndexedAccess`. Four expressions in its hand-authored oracle
 * (auditUixoDocument) therefore fail this repository's `tsc -p .`.
 *
 * Editing the file to fix them would be a hand-edit of a generated
 * artefact — the exact thing its banner forbids, and it would be silently
 * reverted the next time it is regenerated upstream. So the vendoring is a
 * reproducible transformation instead: prepend a header, apply a short
 * recorded list of type annotations (see ANNOTATIONS — without them the
 * file cannot be compiled in a repository that emits declarations), and
 * record the upstream sha256 so drift is detectable. `--check` reverses
 * the annotations and re-hashes, so an in-place edit of the body fails.
 *
 * `@ts-nocheck` suppresses errors inside the vendored file only. Exported
 * schema types are still inferred and still checked at every use site in
 * ../derive.ts, ../sidecar.ts and ../ingest.ts, which is where this
 * plugin's own correctness lives.
 *
 * Run:  npx tsx plugins/uixo/scripts/vendor-uixo.ts <path-to-uixo-native.ts>
 *       npx tsx plugins/uixo/scripts/vendor-uixo.ts --check
 */

import { createHash } from "node:crypto";
import { existsSync, readFileSync, writeFileSync } from "node:fs";
import { dirname, join, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const __dirname = dirname(fileURLToPath(import.meta.url));
const PLUGIN_DIR = resolve(__dirname, "..");
const VENDORED = join(PLUGIN_DIR, "schemas", "uixo-native.ts");
const MARKER = "// ---- END VENDORING HEADER (upstream content follows, with ANNOTATIONS applied) ----";

/**
 * Explicit type annotations applied to upstream exports whose INFERRED
 * type is too large for TypeScript to serialise into a `.d.ts`
 * (TS7056) — a 712-entry schema record and a 712-arm discriminated union.
 * This repository sets `declaration: true`, so without these the file
 * cannot be compiled here at all; upstream never hits it because it does
 * not emit declarations.
 *
 * Each entry is an exact-prefix rewrite, applied once, and asserted to
 * have matched — a silent miss would reintroduce TS7056 on the next
 * re-vendor. Widening to `z.ZodType` loses per-class inference INSIDE the
 * vendored file only; ../derive.ts re-narrows what it needs and is
 * type-checked normally.
 */
export const ANNOTATIONS: ReadonlyArray<{ from: string; to: string }> = [
  {
    from: "export const UIXO_ENTITY_SCHEMAS = {",
    to: "export const UIXO_ENTITY_SCHEMAS: Record<string, z.ZodObject<z.ZodRawShape>> = {",
  },
  {
    from: 'export const UixoEntitySchema = z.discriminatedUnion("type", [',
    to: 'export const UixoEntitySchema: z.ZodType = z.discriminatedUnion("type", [',
  },
  {
    from: "export const UixoDocumentShapeSchema = UixoDocumentShape;",
    to: "export const UixoDocumentShapeSchema: z.ZodType = UixoDocumentShape;",
  },
  {
    from: 'export const UixoCoreDocumentSchema = withAudit(["referential", "semantic"]);',
    to: 'export const UixoCoreDocumentSchema: z.ZodType = withAudit(["referential", "semantic"]);',
  },
  {
    from: 'export const UixoDocumentSchema = withAudit(["referential", "semantic", "policy"]);',
    to: 'export const UixoDocumentSchema: z.ZodType = withAudit(["referential", "semantic", "policy"]);',
  },
];

/** Apply every annotation, failing loudly if one no longer matches. */
export function annotate(upstream: string): string {
  let out = upstream;
  const missed: string[] = [];
  for (const a of ANNOTATIONS) {
    if (!out.includes(a.from)) {
      missed.push(a.from);
      continue;
    }
    out = out.replace(a.from, a.to);
  }
  if (missed.length > 0) {
    throw new Error(
      `vendor: ${missed.length} annotation anchor(s) no longer present upstream — the generator's output shape changed:\n  ${missed.join("\n  ")}`,
    );
  }
  return out;
}

export function vendoringHeader(upstreamSha: string): string {
  return [
    "// @ts-nocheck",
    "/*",
    " * VENDORED — DO NOT EDIT THIS FILE.",
    " *",
    " * Upstream: uixo-native.ts, generated by generate-native.ts from the",
    " * ontology uixo_tbox_full_v11 in its own repository.",
    ` * Upstream sha256: ${upstreamSha}`,
    " *",
    " * Everything below the END VENDORING HEADER marker is upstream, with the",
    " * ANNOTATIONS in scripts/vendor-uixo.ts applied and nothing else changed;",
    " * `--check` reverses them and re-hashes to prove it. To update, re-run:",
    " *   npx tsx plugins/uixo/scripts/vendor-uixo.ts <path-to-upstream>",
    " * then `npm run bridge` and commit both.",
    " *",
    " * `@ts-nocheck` is here because upstream compiles without",
    " * `noUncheckedIndexedAccess`, which this repository sets; four",
    " * expressions in its auditUixoDocument oracle fail under it. Suppression",
    " * is scoped to this file. Exported schema types are still inferred and",
    " * still checked at every use site.",
    " */",
    MARKER,
    "",
  ].join("\n");
}

/** Reverse the annotation pass, recovering the upstream bytes. */
export function deannotate(body: string): string {
  let out = body;
  for (const a of ANNOTATIONS) out = out.replace(a.to, a.from);
  return out;
}

/** The vendored file with our header stripped. */
export function upstreamBody(vendored: string): string {
  const at = vendored.indexOf(MARKER);
  return at < 0 ? vendored : vendored.slice(at + MARKER.length + 1);
}

export function sha256(text: string): string {
  return createHash("sha256").update(text).digest("hex");
}

function main(): void {
  const arg = process.argv[2];

  if (arg === "--check") {
    if (!existsSync(VENDORED)) {
      console.error("vendor: schemas/uixo-native.ts is missing.");
      process.exit(1);
    }
    const current = readFileSync(VENDORED, "utf8");
    if (!current.startsWith("// @ts-nocheck") || !current.includes(MARKER)) {
      console.error("vendor: the vendoring header is missing or malformed. Re-run vendor-uixo.ts.");
      process.exit(1);
    }
    const declared = /Upstream sha256: ([0-9a-f]{64})/.exec(current)?.[1];
    const actual = sha256(deannotate(upstreamBody(current)));
    if (declared !== actual) {
      console.error(`vendor: header declares sha256 ${declared} but the body hashes to ${actual}.`);
      console.error("The vendored body was edited in place. Re-vendor from upstream instead.");
      process.exit(1);
    }
    console.log(`vendor: header intact; ${ANNOTATIONS.length} annotations applied; upstream sha256 ${actual}.`);
    return;
  }

  if (!arg) {
    console.error("usage: vendor-uixo.ts <path-to-upstream-uixo-native.ts> | --check");
    process.exit(1);
  }
  const upstream = readFileSync(resolve(arg), "utf8");
  const digest = sha256(upstream);
  writeFileSync(VENDORED, vendoringHeader(digest) + annotate(upstream), "utf8");
  console.log(`vendor: wrote schemas/uixo-native.ts from ${arg}`);
  console.log(`        upstream sha256 ${digest}`);
  console.log("Next: npm run bridge, then commit both.");
}

if (import.meta.url === `file://${process.argv[1]}`) main();
