import type { RelationTypeDef } from "../../src/core/models/meta.js";
import { bool, enumOf, int, str } from "./_common.js";
import { ALL_PRIMITIVE_IDS, CONTAINABLE_IDS } from "./_id-lists.js";

/**
 * Relation types — mirrors the `relation_types=[...]` block of
 * src/fdpm/plugins/formal_specification.py (lines 2422-2860).
 *
 * Every relation uses the Python-source-style `source_types`/`target_types`
 * lists rather than the CLI's single `source_type_id`/`target_type_id`.
 * The compileProfile step normalises this at registration time.
 *
 * v3.1 additions: OccursIn, Qualifies, SupersededBy, Enforces.
 */
export const RELATIONS: RelationTypeDef[] = [
  {
    id: "fs:ContainedIn",
    name: "ContainedIn",
    description: "Content belongs to a section.",
    source_types: CONTAINABLE_IDS,
    // dnis:Node is included for projects on the
    // formal-specification-dnis composition profile, where sections are
    // modelled as dnis:Node primitives. The renderer's DNIS path
    // (renderers/_common.ts:buildDocumentTreeFromDnis) accepts either
    // the dnis:Node uid (= NID) or the slug-shaped primitive id as the
    // target of an fs:ContainedIn relation. Pure formal-specification
    // projects never construct dnis:Node primitives, so this widening
    // is invisible to them.
    target_types: ["fs:Section", "dnis:Node"],
    cardinality_bounds: { source_min: 1, source_max: null, target_min: 1, target_max: null },
    metadata_schema: [
      bool("is_primary", "Primary containment location."),
      int("order", "Rendering order within section."),
    ],
    fields: [],
    symmetric: false,
    transitive: false,
  },
  {
    id: "fs:DependsOn",
    name: "DependsOn",
    description: "Section depends on another section.",
    source_types: ["fs:Section"],
    target_types: ["fs:Section"],
    metadata_schema: [str("reason", "Why this dependency exists.")],
    fields: [],
    transitive: true,
    symmetric: false,
  },
  {
    id: "fs:References",
    name: "References",
    description: "Content cross-references another primitive.",
    source_types: ALL_PRIMITIVE_IDS,
    target_types: ALL_PRIMITIVE_IDS,
    metadata_schema: [
      enumOf("kind", "Reference semantics.", [
        // Original four (kept for back-compat).
        "uses",
        "refines",
        "overrides",
        "see_also",
        // Added to match real-world authoring vocabulary observed in
        // shipped roadmap transfers. Each is a distinct semantic the
        // four originals could not capture without overload.
        "governs",
        "records_decision",
        "records_assumption",
        "depends_on",
        "outputs_detail",
        "extends",
        "instantiates",
      ]),
      str("context", "Context of the reference.", { required: false }),
    ],
    fields: [],
    symmetric: false,
    transitive: false,
  },
  {
    id: "fs:Precedes",
    name: "Precedes",
    description: "Phase ordering.",
    source_types: ["fs:Phase"],
    target_types: ["fs:Phase"],
    transitive: true,
    fields: [],
    symmetric: false,
  },
  {
    id: "fs:GovernsTransition",
    name: "GovernsTransition",
    description: "Contract governs a phase boundary.",
    source_types: ["fs:Contract"],
    target_types: ["fs:Phase"],
    fields: [],
    symmetric: false,
    transitive: false,
  },
  {
    id: "fs:Validates",
    name: "Validates",
    description: "Property validates a mechanism, phase, or section.",
    source_types: ["fs:FormalProperty"],
    target_types: ["fs:Phase", "fs:Definition", "fs:TypeDefinition", "fs:Section"],
    fields: [],
    symmetric: false,
    transitive: false,
  },
  {
    id: "fs:Mitigates",
    name: "Mitigates",
    description:
      "Guideline or formal property mitigates a failure mode or known limitation.",
    source_types: ["fs:Guideline", "fs:FormalProperty"],
    target_types: ["fs:FailureMode", "fs:Limitation"],
    fields: [],
    symmetric: false,
    transitive: false,
  },
  {
    id: "fs:Illustrates",
    name: "Illustrates",
    description: "Attaches an example to the primitive it illustrates.",
    source_types: ["fs:Example"],
    target_types: ALL_PRIMITIVE_IDS,
    fields: [],
    symmetric: false,
    transitive: false,
  },
  {
    id: "fs:Amends",
    name: "Amends",
    description: "Links a change record to modified primitives.",
    source_types: ["fs:ChangeRecord"],
    target_types: ALL_PRIMITIVE_IDS,
    fields: [],
    symmetric: false,
    transitive: false,
  },
  {
    id: "fs:Verifies",
    name: "Verifies",
    description: "Links a test case to the property it verifies.",
    source_types: ["fs:TestCase"],
    target_types: ["fs:FormalProperty", "fs:Contract", "fs:Invariant"],
    fields: [],
    symmetric: false,
    transitive: false,
  },
  {
    id: "fs:Satisfies",
    name: "Satisfies",
    description: "Traces spec elements to external requirements.",
    source_types: ["fs:Phase", "fs:Contract", "fs:Definition"],
    target_types: ["fs:Requirement"],
    fields: [],
    symmetric: false,
    transitive: false,
  },
  {
    id: "fs:Performs",
    name: "Performs",
    description: "Assigns an actor or role to a phase.",
    source_types: ["fs:Actor"],
    target_types: ["fs:Phase"],
    fields: [],
    symmetric: false,
    transitive: false,
  },
  {
    id: "fs:VisibleTo",
    name: "VisibleTo",
    description: "Tags a primitive with audience visibility.",
    source_types: ALL_PRIMITIVE_IDS,
    target_types: ["fs:Audience"],
    fields: [],
    symmetric: false,
    transitive: false,
  },
  {
    id: "fs:TermRelation",
    name: "TermRelation",
    description: "Semantic relationship between definitions.",
    source_types: ["fs:Definition"],
    target_types: ["fs:Definition"],
    metadata_schema: [
      enumOf("kind", "Terminological relationship kind.", [
        "synonym",
        "specializes",
        "equivalent",
        "antonym",
      ]),
    ],
    fields: [],
    symmetric: false,
    transitive: false,
  },
  // CR-001 relation types
  {
    id: "fs:Implements",
    name: "Implements",
    description: "Component implements an equation.",
    source_types: ["fs:Component"],
    target_types: ["fs:Equation"],
    fields: [],
    symmetric: false,
    transitive: false,
  },
  {
    id: "fs:ComposedOf",
    name: "ComposedOf",
    description: "Component contains a sub-component.",
    source_types: ["fs:Component"],
    target_types: ["fs:Component"],
    metadata_schema: [
      int("order", "Order within parent."),
      str("repeat", "Repeat expression.", { required: false }),
    ],
    fields: [],
    symmetric: false,
    transitive: false,
  },
  {
    id: "fs:ParameterOf",
    name: "ParameterOf",
    description: "Hyperparameter parametrises a component.",
    source_types: ["fs:Hyperparameter"],
    target_types: ["fs:Component"],
    fields: [],
    symmetric: false,
    transitive: false,
  },
  {
    id: "fs:EvaluatedOn",
    name: "EvaluatedOn",
    description: "Experiment evaluated on a dataset.",
    source_types: ["fs:Experiment"],
    target_types: ["fs:Dataset"],
    fields: [],
    symmetric: false,
    transitive: false,
  },
  {
    id: "fs:ProducedBy",
    name: "ProducedBy",
    description: "Result produced by an experiment.",
    source_types: ["fs:Result"],
    target_types: ["fs:Experiment"],
    fields: [],
    symmetric: false,
    transitive: false,
  },
  {
    id: "fs:ComparesTo",
    name: "ComparesTo",
    description: "Result compared to another result.",
    source_types: ["fs:Result"],
    target_types: ["fs:Result"],
    metadata_schema: [
      str("metric", "Comparison metric."),
      str("delta", "Difference value."),
    ],
    fields: [],
    symmetric: false,
    transitive: false,
  },
  {
    id: "fs:AblationOf",
    name: "AblationOf",
    description: "Ablation study of a configuration.",
    source_types: ["fs:AblationStudy"],
    target_types: ["fs:Configuration"],
    fields: [],
    symmetric: false,
    transitive: false,
  },
  {
    id: "fs:Cites",
    name: "Cites",
    description: "Any primitive cites a citation.",
    source_types: ALL_PRIMITIVE_IDS,
    target_types: ["fs:Citation"],
    metadata_schema: [str("claim", "Claim being supported.", { required: false })],
    fields: [],
    symmetric: false,
    transitive: false,
  },
  {
    id: "fs:Depicts",
    name: "Depicts",
    description: "Figure depicts one or more primitives.",
    source_types: ["fs:Figure"],
    target_types: ALL_PRIMITIVE_IDS,
    fields: [],
    symmetric: false,
    transitive: false,
  },
  {
    id: "fs:DataFlow",
    name: "DataFlow",
    description: "Data flows between components.",
    source_types: ["fs:Component"],
    target_types: ["fs:Component"],
    metadata_schema: [
      str("tensor", "Tensor being passed."),
      bool("is_residual", "Whether this is a residual connection."),
    ],
    fields: [],
    symmetric: false,
    transitive: false,
  },
  {
    id: "fs:SharedWeights",
    name: "SharedWeights",
    description: "Components share weight parameters.",
    source_types: ["fs:Component"],
    target_types: ["fs:Component"],
    metadata_schema: [str("parameter_name", "Shared parameter name.")],
    transitive: true,
    fields: [],
    symmetric: false,
  },
  {
    id: "fs:DerivedFrom",
    name: "DerivedFrom",
    description: "Equation derived from another equation.",
    source_types: ["fs:Equation"],
    target_types: ["fs:Equation"],
    metadata_schema: [
      enumOf("derivation_kind", "Kind of derivation.", [
        "specialises",
        "combines",
        "approximates",
      ]),
    ],
    fields: [],
    symmetric: false,
    transitive: false,
  },
  // v3.1 additions: gap-closers
  {
    id: "fs:OccursIn",
    name: "OccursIn",
    description:
      "Failure mode can occur within the given phase. Resolves orphan FailureMode nodes that previously had no relation to the phase graph.",
    source_types: ["fs:FailureMode"],
    target_types: ["fs:Phase"],
    fields: [],
    symmetric: false,
    transitive: false,
  },
  {
    id: "fs:Qualifies",
    name: "Qualifies",
    description:
      "Limitation or formal property qualifies the validity scope of a phase or section — i.e., the target is valid only under the constraint expressed by the source.",
    source_types: ["fs:Limitation", "fs:FormalProperty"],
    target_types: ["fs:Phase", "fs:Section"],
    fields: [],
    symmetric: false,
    transitive: false,
  },
  {
    id: "fs:SupersededBy",
    name: "SupersededBy",
    description:
      "Assumption has been superseded by a newer assumption. Preserves the ledger trail: the source entry is not deleted but marked with a forward pointer. Pairs with Assumption.superseded_by field for bi-directional traceability.",
    source_types: ["fs:Assumption"],
    target_types: ["fs:Assumption"],
    fields: [],
    symmetric: false,
    transitive: false,
  },
  {
    id: "fs:Enforces",
    name: "Enforces",
    description:
      "Invariant must be upheld by the target phase, section, or contract. Stronger than fs:Validates (which expresses property verification); fs:Enforces expresses obligation. Enforcement level is carried in metadata.",
    source_types: ["fs:Invariant"],
    target_types: ["fs:Phase", "fs:Section", "fs:Contract"],
    metadata_schema: [
      enumOf(
        "enforcement",
        "How this invariant is enforced at the target: CI (automated gate) or Review (human retro-validation).",
        ["CI", "Review"],
      ),
    ],
    fields: [],
    symmetric: false,
    transitive: false,
  },
];
