import type { ValidationRuleDef } from "../../src/core/models/meta.js";

/**
 * Validation rules — mirrors src/fdpm/plugins/formal_specification.py
 * lines 2864-3137. Predicates use the legacy DSL (non_trivial, min_items,
 * has_incoming, has_outgoing, acyclic, field). The CLI v1.1 Core does
 * not evaluate these predicates by default — they are stored verbatim
 * and surface to plugin-supplied evaluators or external tooling.
 *
 * MIGRATION (2026-05-04): Predicates migrated from legacy DSL to CEL
 * canonical form (§4.3 SPEC-CEL-VALIDATOR).
 */
type Rule = Omit<ValidationRuleDef, "level"> & { level: "error" | "warning" | "info" };

const rule = (
  id: string,
  name: string,
  level: "error" | "warning" | "info",
  applies_to: string[],
  predicate: string,
  expression: string,
  description: string,
): Rule => ({
  id,
  name,
  level,
  applies_to,
  targets: applies_to,
  predicate,
  expression,
  description,
});

export const VALIDATION_RULES: ValidationRuleDef[] = [
  rule(
    "fs:val:phase-has-question",
    "Phase must have a question",
    "error",
    ["fs:Phase"],
    "non_trivial(question)",
    "has(instance.field_values.question) && type(instance.field_values.question) == string && instance.field_values.question.trim().size() > 0",
    "Every phase must state the question it answers.",
  ),
  rule(
    "fs:val:contract-complete",
    "Contract must have pre and postcondition",
    "error",
    ["fs:Contract"],
    "non_trivial(precondition) and non_trivial(postcondition)",
    "has(instance.field_values.precondition) && type(instance.field_values.precondition) == string && instance.field_values.precondition.trim().size() > 0 && has(instance.field_values.postcondition) && type(instance.field_values.postcondition) == string && instance.field_values.postcondition.trim().size() > 0",
    "A contract requires both pre and postcondition.",
  ),
  rule(
    "fs:val:property-has-intuition",
    "Property should explain intuition",
    "warning",
    ["fs:FormalProperty"],
    "non_trivial(intuition)",
    "has(instance.field_values.intuition) && type(instance.field_values.intuition) == string && instance.field_values.intuition.trim().size() > 0",
    "Formal properties should explain why they hold.",
  ),
  rule(
    "fs:val:failure-has-recovery",
    "Failure mode must specify recovery",
    "error",
    ["fs:FailureMode"],
    "non_trivial(recovery)",
    "has(instance.field_values.recovery) && type(instance.field_values.recovery) == string && instance.field_values.recovery.trim().size() > 0",
    "Every failure mode must describe a recovery.",
  ),
  rule(
    "fs:val:example-has-content",
    "Example must have content",
    "error",
    ["fs:Example"],
    "non_trivial(content)",
    "has(instance.field_values.content) && type(instance.field_values.content) == string && instance.field_values.content.trim().size() > 0",
    "Every example must have non-trivial content.",
  ),
  rule(
    "fs:val:invariant-has-statement",
    "Invariant must have statement",
    "error",
    ["fs:Invariant"],
    "non_trivial(statement)",
    "has(instance.field_values.statement) && type(instance.field_values.statement) == string && instance.field_values.statement.trim().size() > 0",
    "Every invariant must state what must hold.",
  ),
  rule(
    "fs:val:testcase-has-expected",
    "TestCase must have expected output",
    "error",
    ["fs:TestCase"],
    "non_trivial(expected_output)",
    "has(instance.field_values.expected_output) && type(instance.field_values.expected_output) == string && instance.field_values.expected_output.trim().size() > 0",
    "Every test case must define expected output.",
  ),
  rule(
    "fs:val:decision-has-alternatives",
    "DesignDecision should have alternatives",
    "warning",
    ["fs:DesignDecision"],
    "min_items(alternatives, 1)",
    "has(instance.field_values.alternatives) && type(instance.field_values.alternatives) == list && instance.field_values.alternatives.size() >= 1",
    "Design decisions should list alternatives.",
  ),
  rule(
    "fs:val:equation-has-variables",
    "Equation must declare variables",
    "error",
    ["fs:Equation"],
    "min_items(variables, 1)",
    "has(instance.field_values.variables) && type(instance.field_values.variables) == list && instance.field_values.variables.size() >= 1",
    "Every equation must declare at least one variable.",
  ),
  rule(
    "fs:val:component-has-io",
    "Component must have inputs and outputs",
    "error",
    ["fs:Component"],
    "min_items(inputs, 1) and min_items(outputs, 1)",
    "has(instance.field_values.inputs) && type(instance.field_values.inputs) == list && instance.field_values.inputs.size() >= 1 && has(instance.field_values.outputs) && type(instance.field_values.outputs) == list && instance.field_values.outputs.size() >= 1",
    "Every component must specify inputs and outputs.",
  ),
  rule(
    "fs:val:experiment-has-result",
    "Experiment should have results",
    "warning",
    ["fs:Experiment"],
    "has_incoming(fs:ProducedBy)",
    "graph.incoming(\"fs:ProducedBy\").size() >= 1",
    "Every experiment should have at least one associated result.",
  ),
  rule(
    "fs:val:result-has-comparison",
    "Result should have comparison",
    "warning",
    ["fs:Result"],
    "has_outgoing(fs:ComparesTo) or field(is_external_baseline) == true",
    "graph.outgoing(\"fs:ComparesTo\").size() >= 1 || (has(instance.field_values.is_external_baseline) && instance.field_values.is_external_baseline == true)",
    "Non-baseline results should compare to at least one other result.",
  ),
  rule(
    "fs:val:config-has-values",
    "Configuration must assign values",
    "error",
    ["fs:Configuration"],
    "min_items(values, 1)",
    "has(instance.field_values.values) && type(instance.field_values.values) == list && instance.field_values.values.size() >= 1",
    "A configuration must assign at least one hyperparameter value.",
  ),
  rule(
    "fs:val:ablation-has-variations",
    "Ablation must have variations",
    "error",
    ["fs:AblationStudy"],
    "min_items(variations, 2)",
    "has(instance.field_values.variations) && type(instance.field_values.variations) == list && instance.field_values.variations.size() >= 2",
    "An ablation must contain at least two variations to be meaningful.",
  ),
  rule(
    "fs:val:citation-has-year",
    "Citation must have year",
    "error",
    ["fs:Citation"],
    "non_trivial(year)",
    "has(instance.field_values.year)",
    "Every citation must include a publication year.",
  ),
  rule(
    "fs:val:figure-has-depicts",
    "Figure should reference depicted primitives",
    "warning",
    ["fs:Figure"],
    "min_items(depicts, 1)",
    "has(instance.field_values.depicts) && type(instance.field_values.depicts) == list && instance.field_values.depicts.size() >= 1",
    "Figures should reference the primitives they depict.",
  ),
  rule(
    "fs:val:component-acyclic",
    "Component composition must be acyclic",
    "error",
    ["fs:Component"],
    "acyclic(fs:ComposedOf)",
    "graph.acyclic(\"fs:ComposedOf\")",
    "The fs:ComposedOf relation graph must be a DAG.",
  ),
  rule(
    "fs:val:invariant-has-enforcement",
    "Invariant must declare enforcement level",
    "error",
    ["fs:Invariant"],
    "non_trivial(enforcement)",
    "has(instance.field_values.enforcement) && type(instance.field_values.enforcement) == string && instance.field_values.enforcement.trim().size() > 0",
    "Every invariant must specify whether it is CI-enforced (hard) or review-enforced (soft). Without this, the Invariant Ledger is not auditable.",
  ),
  rule(
    "fs:val:assumption-has-status",
    "Assumption should declare ledger status",
    "warning",
    ["fs:Assumption"],
    "non_trivial(status)",
    "has(instance.field_values.status) && type(instance.field_values.status) == string && instance.field_values.status.trim().size() > 0",
    "Assumptions used in execution roadmaps should carry a lifecycle status to make the Assumption Ledger queryable.",
  ),
  rule(
    "fs:val:assumption-assumed-needs-owner",
    "'assumed' entry requires risk_owner",
    "error",
    ["fs:Assumption"],
    "field(status) != 'assumed' or non_trivial(risk_owner)",
    "!has(instance.field_values.status) || instance.field_values.status != 'assumed' || (has(instance.field_values.risk_owner) && type(instance.field_values.risk_owner) == string && instance.field_values.risk_owner.trim().size() > 0)",
    "An assumption with status 'assumed' must name a risk owner. An ownerless assumed entry is an unaccountable risk.",
  ),
  rule(
    "fs:val:assumption-superseded-needs-pointer",
    "'superseded' entry requires superseded_by",
    "error",
    ["fs:Assumption"],
    "field(status) != 'superseded' or non_trivial(superseded_by)",
    "!has(instance.field_values.status) || instance.field_values.status != 'superseded' || (has(instance.field_values.superseded_by) && type(instance.field_values.superseded_by) == string && instance.field_values.superseded_by.trim().size() > 0)",
    "An assumption with status 'superseded' must carry a forward pointer to its replacement, preserving the ledger trail.",
  ),
  rule(
    "fs:val:phase-has-failure-mode",
    "Phase should have at least one failure mode",
    "warning",
    ["fs:Phase"],
    "has_incoming(fs:OccursIn)",
    "graph.incoming(\"fs:OccursIn\").size() >= 1",
    "Every phase should document at least one failure mode via an fs:OccursIn relation. Phases without failure modes are under-specified.",
  ),
  rule(
    "fs:val:citation-not-stale",
    "Citation should have a currency_date",
    "warning",
    ["fs:Citation"],
    "non_trivial(currency_date)",
    "has(instance.field_values.currency_date) && type(instance.field_values.currency_date) == string && instance.field_values.currency_date.trim().size() > 0",
    "Citations used in documents with a references_currency discipline should carry a currency_date so stale references can be flagged.",
  ),
];
