/**
 * Promote a registered profile into a plugin skeleton.
 *
 * PURPOSE.md draws the line this module crosses: "A plugin that ships only
 * a profile is a schema. A plugin that ships verbs, resources, prompts, and
 * renderers is a complete domain vocabulary." A profile registered through
 * `fdpm.profile.register` is stuck on the schema side of that line — no
 * verbs, so every write is generic and the operation log records mechanism
 * rather than domain intent; no prompts, so the orientation layer is empty;
 * no renderers beyond Core's generic one. Promotion is the route across:
 * it writes a real, loadable plugin whose `activate()` registers the
 * profile, with the capability slots an author fills in next.
 *
 * TWO DELIBERATE CONSTRAINTS
 *
 * 1. It never writes into a plugin discovery path. PURPOSE.md keeps plugin
 *    authorship in-house and defers signing/sandboxing until after the
 *    eval; a plugin generated from agent-authored input that lands in
 *    `~/.fdpm/plugins` is active at the next host start with no human in
 *    the loop. The refusal IS the review gate: an operator reads the
 *    emitted directory and copies it in deliberately. There is no override
 *    flag, because a flag is exactly the thing an agent would set.
 *
 * 2. The entry module is JavaScript, not TypeScript. In-tree plugins are
 *    `.ts` because the dev CLI runs under tsx and the build compiles them;
 *    an emitted plugin has neither. A packaged `fdpm` importing
 *    `~/.fdpm/plugins/<id>/index.ts` fails at load with no transform in
 *    sight, so the emitted entry is the form that runs everywhere the host
 *    can discover it (CLAUDE.md's TypeScript default exempts a target
 *    runtime that cannot execute it).
 *
 * The profile itself is emitted as `profile.json` and read at activation
 * rather than transcribed into TypeScript: a profile can carry hundreds of
 * types, and a transcription is a second copy that drifts from the
 * registry's.
 */

import { promises as fs } from "node:fs";
import { existsSync } from "node:fs";
import { isAbsolute, join, resolve, sep } from "node:path";
import type { Host } from "../host.js";
import type { DomainProfile } from "../models/meta.js";
import { FDPMException } from "../errors/fdpm-exception.js";
import { HOST_VERSION } from "../version/spec.js";
import { formatProfileRef, parseProfileRef } from "./version.js";
import { defaultPluginPaths, BUILTIN_PLUGIN_DIRS_DEFAULT } from "../../plugin/discovery.js";

export interface PromoteOptions {
  /** Directory to create the plugin directory INSIDE. */
  outDir: string;
  /** Overwrite an existing plugin directory of the same name. */
  force?: boolean;
  /** Plugin id override. Must satisfy the manifest's id pattern. */
  pluginId?: string;
  /** Discovery paths to refuse writing into. Defaults to the real ones. */
  discoveryPaths?: string[];
}

export interface PromoteResult {
  plugin_id: string;
  profile_ref: string;
  dir: string;
  files: string[];
}

const PLUGIN_ID_PATTERN = /^[a-z0-9]+(\.[a-z0-9-]+)+$/;

/**
 * `profile:acme-deck:0.1` → `acme-deck-0-1`: lowercase, every run of
 * non-alphanumerics collapsed to one dash, no leading or trailing dash.
 * The result feeds both the plugin id's last segment and the capability's
 * `local_name`, which share the `[a-z0-9-]+` shape.
 */
function slugify(id: string): string {
  const slug = id
    .toLowerCase()
    .replace(/^profile[:.]/, "")
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/^-+|-+$/g, "");
  return slug.length > 0 ? slug : "profile";
}

function isInside(child: string, parent: string): boolean {
  const c = resolve(child);
  const p = resolve(parent);
  return c === p || c.startsWith(p.endsWith(sep) ? p : p + sep);
}

function manifestFor(pluginId: string, profile: DomainProfile, slug: string): unknown {
  return {
    id: pluginId,
    version: profile.version,
    spec_version: "1.2.0",
    kind: "server",
    name: profile.label ?? profile.name ?? profile.id,
    description: `Promoted from the registered profile ${formatProfileRef(profile.id, profile.version)}. Ships the profile as-is; verbs, renderers and prompts are the author's next step.`,
    host_compatibility: { fdpm: `>=${HOST_VERSION.split(".").slice(0, 2).join(".")},<2` },
    capabilities: [
      { capability_id: "cap:profile", local_name: slug, entry: "PROFILE" },
    ],
    permissions: [],
  };
}

function entryModuleFor(pluginId: string, profileRef: string): string {
  return `/**
 * Entry module for ${pluginId}, generated by \`fdpm profile promote\`
 * from the registered profile ${profileRef}.
 *
 * WHAT IS HERE: the profile, registered on activation. That is a schema,
 * not yet a domain vocabulary.
 *
 * WHAT TO ADD NEXT, in the order an agent meets them:
 *   - verbs      — domain operation kinds, so the log records intent
 *                  rather than generic primitive.create calls
 *   - renderers  — ctx.registerRenderer({ target, rendererId, fn }), the
 *                  human-review artifact for this domain
 *   - prompts    — ctx.registerPrompt(...), the orientation layer a cold
 *                  agent reads before it acts
 *   - validators — ctx.registerValidator(...) for the rules the profile's
 *                  declarative predicates cannot express
 *
 * Declare each one in fdpm-plugin.json's \`capabilities\` as you add it:
 * the manifest and what activate() registers are one contract.
 */
import { readFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, join } from "node:path";

const here = dirname(fileURLToPath(import.meta.url));

export const PROFILE = JSON.parse(readFileSync(join(here, "profile.json"), "utf8"));
export const manifest = JSON.parse(readFileSync(join(here, "fdpm-plugin.json"), "utf8"));

export function activate(ctx) {
  ctx.registerProfile(PROFILE);
  ctx.logger.info(
    \`${pluginId} activated: \${PROFILE.primitive_types.length} primitive types, \` +
      \`\${PROFILE.relation_types.length} relation types. Profile: \${PROFILE.id}@\${PROFILE.version}.\`,
  );
}

export default { manifest, activate };
`;
}

function readmeFor(
  pluginId: string,
  profile: DomainProfile,
  profileRef: string,
  generatedBy: string,
): string {
  const today = new Date().toISOString().slice(0, 10);
  return `---
disclaimer:
  notice: >-
    No information within this document should be taken for granted.
    Any statement or premise not backed by a real logical definition
    or verifiable reference may be invalid, erroneous, or a hallucination.
  generated_by: "${generatedBy}"
  date: "${today}"
---

# ${profile.label ?? profile.name ?? profile.id}

\`${pluginId}\` — promoted from the registered profile \`${profileRef}\`.

## Disclaimer

This work is subject to the methodological caveats and commitments described in [@DISCLAIMER.md](../../DISCLAIMER.md).
> No statement or premise not backed by a real logical definition or verifiable reference should be taken for granted.

| Field | Value |
| --- | --- |
| Plugin id | \`${pluginId}\` |
| Plugin version | \`${profile.version}\` |
| Profile | \`${profileRef}\` |
| Primitive types | ${profile.primitive_types.length} |
| Relation types | ${profile.relation_types.length} |
| Entry point | [\`index.js\`](./index.js) |

## Install

This directory was written OUTSIDE any plugin discovery path on purpose:
a generated plugin is not an activated one. Read it, then install it
deliberately — and note the second gate: a plugin discovered on the
filesystem is \`community\` trust, so it stays disabled until you enable it
by name.

\`\`\`bash
cp -r ${pluginId} ~/.fdpm/plugins/
fdpm plugin list                 # discovered, state: disabled
fdpm plugin enable ${pluginId}
\`\`\`

## What this ships, and what it does not

It ships the profile — primitive types, relation types, and whatever
declarative validation rules the profile carried. It does **not** ship
verbs, renderers, prompts, or code validators; \`index.js\` names each slot
and where to register it.

A profile-only plugin is a schema. Add the vocabulary and it becomes a
domain an agent can be dropped into cold.
`;
}

/**
 * Write the plugin skeleton. `ref` is a profile id (newest revision) or an
 * `id@version` ref; the emitted plugin's version is the profile revision's,
 * so a promotion always names exactly what it copied.
 */
export async function promoteProfile(
  host: Host,
  ref: string,
  opts: PromoteOptions,
): Promise<PromoteResult> {
  const parsed = parseProfileRef(ref);
  if (!host.profiles.has(ref)) {
    throw new FDPMException("not_found", `profile not found: ${ref}`, {
      evidence: {
        profile_id: parsed.id,
        registered_versions: host.profiles.versionsOf(parsed.id),
      },
    });
  }
  const profile = host.profiles.getRaw(ref);
  const profileRef = formatProfileRef(profile.id, profile.version);
  const slug = slugify(profile.id);
  const pluginId = opts.pluginId ?? `promoted.${slug}`;
  if (!PLUGIN_ID_PATTERN.test(pluginId)) {
    throw new FDPMException(
      "verification",
      `plugin id "${pluginId}" must match ${PLUGIN_ID_PATTERN.source}`,
      { evidence: { plugin_id: pluginId, derived_from: profile.id } },
    );
  }

  const outDir = isAbsolute(opts.outDir) ? opts.outDir : resolve(process.cwd(), opts.outDir);
  const discoveryPaths = opts.discoveryPaths ?? [
    ...defaultPluginPaths(),
    ...BUILTIN_PLUGIN_DIRS_DEFAULT,
  ];
  const blocked = discoveryPaths.find((d) => isInside(outDir, d) || isInside(d, outDir));
  if (blocked) {
    throw new FDPMException(
      "permission",
      `refusing to write a generated plugin into the discovery path ${blocked}: it would activate on the next host start without review. Write it elsewhere and copy it in.`,
      { evidence: { reason: "discovery_path", out_dir: outDir, discovery_path: blocked } },
    );
  }

  const dir = join(outDir, pluginId);
  if (existsSync(dir) && !opts.force) {
    throw new FDPMException(
      "conflict",
      `${dir} already exists; pass --force to overwrite it`,
      { evidence: { reason: "directory_exists", dir } },
    );
  }
  await fs.mkdir(dir, { recursive: true });

  const generatedBy = `fdpm profile promote (fdpm-cli ${HOST_VERSION})`;
  const files: Array<[string, string]> = [
    ["fdpm-plugin.json", JSON.stringify(manifestFor(pluginId, profile, slug), null, 2) + "\n"],
    ["profile.json", JSON.stringify(profile, null, 2) + "\n"],
    ["index.js", entryModuleFor(pluginId, profileRef)],
    ["README.md", readmeFor(pluginId, profile, profileRef, generatedBy)],
  ];
  for (const [name, content] of files) {
    await fs.writeFile(join(dir, name), content, "utf8");
  }

  return {
    plugin_id: pluginId,
    profile_ref: profileRef,
    dir,
    files: files.map(([name]) => join(dir, name)),
  };
}
