import type { RendererFn, RendererOutput } from "../../../src/plugin/types.js";
import type { PrimitiveInstance, RelationInstance } from "../../../src/core/models/instance.js";
import { projectThroughViewInstance } from "./_view.js";

/**
 * `text/markdown` renderer for `sw:Decision` (ADR) primitives.
 *
 * Output is a single concatenated Markdown document — one section per
 * decision, ordered by id. The classic ADR template is followed:
 *
 *   ## ADR — `<id>`: <title>
 *   - **Status:** <status>
 *   - **Supersedes:** `<other-id>` (only if a `sw:Supersedes` edge exists)
 *   - **Superseded by:** `<other-id>` (inverse direction of the same edge)
 *   ### Context
 *   <context>
 *   ### Decision
 *   <rationale>
 *   ### Consequences
 *   <consequences>
 *   ### Alternatives considered
 *   - **<alternative.name>** — <alternative.reason_rejected>
 *   ### Evidence
 *   - `<evidence_id>` (<kind>): <description> — `<source>`
 *
 * Anything that is not present in the workbook graph is omitted; nothing
 * is invented. If there are no `sw:Decision` primitives at all, the
 * renderer emits a documented stub so the file is never silently empty.
 */

type Alternative = { name: string; reason_rejected: string };

function fv<T = unknown>(p: PrimitiveInstance, key: string): T | undefined {
  return (p.field_values as Record<string, unknown>)[key] as T | undefined;
}

function asArray<T>(v: T | T[] | undefined | null): T[] {
  if (v === undefined || v === null) return [];
  return Array.isArray(v) ? v : [v];
}

function escapeInline(s: string): string {
  // Backslash-escape characters that have inline-Markdown meaning in the
  // header line. Body paragraphs are passed through verbatim — they're
  // expected to be already-Markdown-friendly prose.
  return s.replace(/([\\`*_{}\[\]()#+!|])/g, "\\$1");
}

function blockOrEmpty(label: string, body: string | undefined): string[] {
  if (!body || body.trim().length === 0) return [];
  return [`### ${label}`, "", body.trim(), ""];
}

export const renderAdr: RendererFn = (input): RendererOutput => {
  const { profile, primitives, relations, workbookId } = input;

  const decisions = primitives
    .filter((p) => p.type_id === "sw:Decision")
    .slice()
    .sort((a, b) => a.id.localeCompare(b.id));

  // sw:Supersedes — Decision → Decision (transitive).
  const supersedes = new Map<string, string[]>();   // src → [tgt]
  const supersededBy = new Map<string, string[]>(); // tgt → [src]
  // sw:Justifies — Evidence → Decision (one of the allowed targets).
  const evidenceByDecision = new Map<string, string[]>(); // decisionId → [evidenceId]
  for (const r of relations) {
    if (r.type_id === "sw:Supersedes") {
      const arrA = supersedes.get(r.source_id) ?? [];
      arrA.push(r.target_id);
      supersedes.set(r.source_id, arrA);
      const arrB = supersededBy.get(r.target_id) ?? [];
      arrB.push(r.source_id);
      supersededBy.set(r.target_id, arrB);
    } else if (r.type_id === "sw:Justifies") {
      const arr = evidenceByDecision.get(r.target_id) ?? [];
      arr.push(r.source_id);
      evidenceByDecision.set(r.target_id, arr);
    }
  }
  const evidenceById = new Map(
    primitives.filter((p) => p.type_id === "sw:Evidence").map((p) => [p.id, p]),
  );

  const lines: string[] = [];
  lines.push(`# Architectural Decision Records — ${workbookId}`);
  lines.push("");
  lines.push(
    `> Profile: \`${profile.id}\` v${profile.version}. ` +
      `Generated by \`sw:ADRRenderer\` from ${decisions.length} \`sw:Decision\` primitive${decisions.length === 1 ? "" : "s"}.`,
  );
  lines.push("");

  if (decisions.length === 0) {
    lines.push("_No `sw:Decision` primitives found in this workbook._");
    lines.push("");
    return toOutput(lines);
  }

  // gap-pass-2 #17 — surface any sw:Views that include sw:Decision in their
  // included_type_ids. Each view gets a one-line summary: viewers can use
  // them as an index of which decisions matter to which audience.
  const views = primitives.filter((p) => p.type_id === "sw:View");
  const viewsTouchingDecisions = views.filter((v) => {
    try {
      const proj = projectThroughViewInstance(
        { primitives, relations, profile },
        v,
      );
      return proj.primitives.some((p) => p.type_id === "sw:Decision");
    } catch {
      return false;
    }
  });
  if (viewsTouchingDecisions.length > 0) {
    lines.push("## Views referencing decisions");
    lines.push("");
    for (const v of viewsTouchingDecisions) {
      const proj = projectThroughViewInstance(
        { primitives, relations, profile },
        v,
      );
      const inViewDecisions = proj.primitives
        .filter((p) => p.type_id === "sw:Decision")
        .map((p) => p.id);
      const summary = (fv<string>(v, "summary") ?? "").trim();
      lines.push(
        `- \`${v.id}\` — ${summary || "(no summary)"} (${inViewDecisions.length} decision${inViewDecisions.length === 1 ? "" : "s"})`,
      );
    }
    lines.push("");
    lines.push("---");
    lines.push("");
  }

  // Index of contents.
  lines.push("## Index");
  lines.push("");
  for (const d of decisions) {
    const title = (fv<string>(d, "title") ?? d.id).trim();
    const status = (fv<string>(d, "status") ?? "Unknown").trim();
    lines.push(`- [\`${d.id}\`](#adr--${slug(d.id)}) — ${escapeInline(title)} _(${status})_`);
  }
  lines.push("");
  lines.push("---");
  lines.push("");

  for (const d of decisions) {
    const title = (fv<string>(d, "title") ?? d.id).trim();
    const status = (fv<string>(d, "status") ?? "Unknown").trim();
    const context = fv<string>(d, "context");
    const rationale = fv<string>(d, "rationale");
    const consequences = fv<string>(d, "consequences");
    const alternatives = asArray<Alternative>(fv(d, "alternatives"));

    lines.push(`## ADR — \`${d.id}\`: ${escapeInline(title)}`);
    lines.push("");
    lines.push(`- **Status:** ${escapeInline(status)}`);
    // gap-pass-2 #1 — date + deciders, when present.
    const date = fv<string>(d, "date");
    if (date && date.trim().length > 0) {
      lines.push(`- **Date:** ${escapeInline(date.trim())}`);
    }
    const deciders = fv<string[]>(d, "deciders");
    if (Array.isArray(deciders) && deciders.length > 0) {
      lines.push(
        `- **Deciders:** ${deciders.map((s) => escapeInline(s)).join(", ")}`,
      );
    }
    // gap-pass-2 #13 — review provenance.
    const lastReviewed = fv<string>(d, "last_reviewed_at");
    if (lastReviewed && lastReviewed.trim().length > 0) {
      lines.push(`- **Last reviewed:** ${escapeInline(lastReviewed.trim())}`);
    }
    const sup = supersedes.get(d.id) ?? [];
    if (sup.length > 0) {
      lines.push(`- **Supersedes:** ${sup.map((id) => `\`${id}\``).join(", ")}`);
    }
    const supBy = supersededBy.get(d.id) ?? [];
    if (supBy.length > 0) {
      lines.push(`- **Superseded by:** ${supBy.map((id) => `\`${id}\``).join(", ")}`);
    }
    lines.push("");

    lines.push(...blockOrEmpty("Context", context));
    lines.push(...blockOrEmpty("Decision", rationale));
    lines.push(...blockOrEmpty("Consequences", consequences));

    if (alternatives.length > 0) {
      lines.push("### Alternatives considered");
      lines.push("");
      for (const a of alternatives) {
        if (!a || typeof a.name !== "string") continue;
        const name = escapeInline(a.name);
        const reason =
          typeof a.reason_rejected === "string" && a.reason_rejected.trim().length > 0
            ? ` — ${a.reason_rejected.trim()}`
            : "";
        lines.push(`- **${name}**${reason}`);
      }
      lines.push("");
    }

    const evIds = evidenceByDecision.get(d.id) ?? [];
    if (evIds.length > 0) {
      lines.push("### Evidence");
      lines.push("");
      for (const eid of evIds) {
        const e = evidenceById.get(eid);
        if (!e) {
          lines.push(`- \`${eid}\``);
          continue;
        }
        const kind = fv<string>(e, "kind") ?? "?";
        const source = fv<string>(e, "source") ?? "";
        const desc = fv<string>(e, "description") ?? "";
        lines.push(`- \`${eid}\` (${kind}): ${desc}${source ? ` — \`${source}\`` : ""}`);
      }
      lines.push("");
    }

    lines.push("---");
    lines.push("");
  }

  return toOutput(lines);
};

function slug(id: string): string {
  return id.toLowerCase().replace(/[^a-z0-9]+/g, "-").replace(/(^-|-$)/g, "");
}

function toOutput(lines: string[]): RendererOutput {
  const text = lines.join("\n");
  return {
    bytes: new TextEncoder().encode(text),
    contentType: "text/markdown",
    filename: "decisions.md",
  };
}
