/**
 * ============================================================================
 * concept-design/schemas inventory — full 105-file projection
 * ============================================================================
 *
 * Disclaimer:
 * No information in this file should be taken for granted. Tier assignments,
 * capability tags, and cross-references are calibrated judgments derived from
 * concept-design/schemas/README.md and per-file headers. Verify against the
 * original source before any consequential decision. Any statement not backed
 * by a real definition or verifiable reference may be invalid, erroneous, or a
 * model hallucination.
 *
 * Scope:
 *   This file is the FULL inventory of the source archive — every .ts file
 *   becomes one entry. Entries are tagged with the new kind discriminator so
 *   the registry no longer pretends every file is a plugin:
 *
 *     - plugin   — would be packaged as an FDPM plugin (also listed in
 *                  fdpm-plugins-instance.ts; this file is the superset).
 *     - utility  — internal helper module (Result<T,E>, KpiSchema, etc.).
 *     - barrel   — pure re-export module.
 *     - demo     — runnable example / reference.
 *     - data     — catalogue entry consumed by another plugin (the 71
 *                  business-models/* framework formalisations).
 *
 *   The plugin-shaped subset (21 entries) is the contract surface and lives
 *   in fdpm-plugins-instance.ts. This file exists for traceability — every
 *   source file accounted for, no module silently dropped.
 * ============================================================================
 */

import { FdpmPluginIdeasRegistrySchema, type FdpmPluginIdeasRegistry } from "./plugins";

export const conceptSchemasInventory: FdpmPluginIdeasRegistry = {
  schemaVersion: "1.0.0",

  frontmatter: {
    title: "concept-design/schemas inventory — full 105-file projection",
    status: "draft",
    disclaimer:
      "Inventory of every .ts file in concept-design/schemas/**. Tier assignments are calibrated judgments anchored to the kind discriminator: plugin entries are tiered S/A/B/C against the 'would I ship this as a plugin' bar, utility/barrel/demo/data entries are tiered against 'how load-bearing is this within the library' (S = depended on by everything, C = standalone demo).",
    provenance: {
      sourceRequest:
        "Split the prior 105-entry registry into a plugins-only file and a full inventory; tag every inventory entry with the new kind discriminator so utilities/barrels/demos no longer pretend to ship cap:* surfaces.",
      baseline:
        "Prior fdpm-plugins-instance.ts (105 entries, every entry implicitly tagged kind: plugin and required to declare capabilityKinds.length >= 1).",
      capabilityKindsReferenced: {
        count: 9,
        kinds: [
          "cap:profile",
          "cap:renderer",
          "cap:validator",
          "cap:transformer",
          "cap:exporter",
          "cap:expr-helper",
          "cap:lifecycle-hook",
          "cap:template",
          "cap:asset",
        ],
        note:
          "Only plugin-kind entries declare capabilityKinds. utility/barrel/demo/data entries leave it empty — the schema's capabilityKinds.min(1) check now applies only to kind === 'plugin'.",
      },
    },
  },

  heading:
    "concept-design/schemas inventory — 112 entries (18 plugin / 15 utility / 5 barrel / 2 demo / 72 data)",

  honestPreamble: {
    body:
      "Every .ts file in the source archive is accounted for. The kind discriminator separates real plugin candidates (21) from library utilities, barrels, demos, and the long tail of business-model framework formalisations (treated as catalogue data for the single business-models-canvases plugin rather than as 71 plugins).",
    tierDefinitions: [
      {
        tier: "S",
        label: "Load-bearing",
        meaning:
          "Foundational entry that downstream entries depend on. Removing it would break large parts of the library.",
      },
      {
        tier: "A",
        label: "Canonical",
        meaning:
          "Important, well-defined, widely useful entry — a real first-party plugin candidate or a heavily-imported utility.",
      },
      {
        tier: "B",
        label: "Specialised",
        meaning:
          "Valid and useful but narrow in scope — niche plugin, specialised framework formalisation, or convenience utility.",
      },
      {
        tier: "C",
        label: "Auxiliary",
        meaning:
          "Pure re-export, demo, or aggregator that ships no new behaviour itself. Useful for calibration only.",
      },
    ],
    tierDistribution: {
      totalEntries: 112,
      rows: [
        { tier: "S", count: 15 },
        { tier: "A", count: 31 },
        { tier: "B", count: 59 },
        { tier: "C", count: 7 },
      ],
    },
    backlogRecommendation: {
      keepLiveTiers: ["S", "A"],
      parkingLotTiers: ["B"],
      calibrationOnlyTiers: ["C"],
      rationale:
        "S+A together identify the live load-bearing surface (30 entries). The 65 B-tier entries are dominated by individual framework formalisations under fdpm.business-models-canvases — they are catalogue depth, not 65 separate roadmap items. C entries are barrels and demos that are useful for source-archive completeness but never roadmap candidates.",
    },
    notes: [
      "All 71 entries in business-models/ share the architectural shape 'enums and atoms → item schemas → root model schema → portfolio schema' with patchable-first identified arrays and superRefine cross-checks. They are kind: 'data' here because they are catalogue content for one plugin (fdpm.business-models-canvases), not 71 plugins.",
      "ai-agent-mixin-usage.ts and feature-schema-ai-demo.ts are kind: 'demo'; they ship no library behaviour.",
      "site-schema.ts is kind: 'barrel' (one-line re-export); the implementation lives in site-schema/* and is enumerated separately.",
      "fdpm.result, fdpm.zod-ai-meta, and fdpm.business-models-shared are kind: 'utility' — internal helpers, not packaging units.",
    ],
  },

  sections: [
    {
      title: "Core Primitives & Utilities",
      primaryCapabilityKinds: ["cap:profile", "cap:validator", "cap:expr-helper", "cap:transformer"],
      description:
        "Shared building blocks: typed primitives, the Result error type, the patch engine, version metadata, the AI-teaching mixin utility, and the cross-domain bridge profile.",
      entries: [
        {
          displayNumber: 1,
          id: "fdpm.common",
          what: "Primitives & reusable atoms: UUID, ISO-8601 DateTime, hex color, URI, lowercase-hyphen Slug, SemVer, user reference, rich-text spans, asset metadata, dataset, axis config.",
          why: "Single source of truth for shared primitive validation; every other entry depends on it.",
          tier: "S",
          kind: "plugin",
          capabilityKinds: ["cap:profile", "cap:validator"],
          crossReferences: [],
          dependsOn: [],
          notes: ["Source: concept-design/schemas/common.ts"],
        },
        {
          displayNumber: 2,
          id: "fdpm.result",
          what: "Result<T, E> discriminated union plus ok / err / fail / map / unwrap / unwrapOr / isOk / isErr / formatError helpers.",
          why: "Lets pipelines and transforms surface failures explicitly and compose them safely.",
          tier: "A",
          kind: "utility",
          capabilityKinds: [],
          crossReferences: [],
          dependsOn: [],
          notes: ["Source: concept-design/schemas/result.ts. Utility module — exports types and helper functions, not a cap:* surface."],
        },
        {
          displayNumber: 3,
          id: "fdpm.patchable",
          what: "Generic patch engine: validate(doc), patch(original, partial) with deep merge and immutable field protection, computeDiff producing structural DiffEntry[], applyArrayOps, batched cross-entity transactions.",
          why: "Encodes the patchable-first convention that makes every other schema surgically editable.",
          tier: "S",
          kind: "plugin",
          capabilityKinds: ["cap:transformer", "cap:lifecycle-hook"],
          crossReferences: [],
          dependsOn: ["fdpm.common"],
          notes: ["Source: concept-design/schemas/patchable.ts"],
        },
        {
          displayNumber: 4,
          id: "fdpm.version-mixin",
          what: "SemVer 2.0.0-based version tracking: ParsedSemVer, optimistic locking metadata, snapshot history, comparable version metadata.",
          why: "Standard, comparable version metadata for any schema, template, or content entity.",
          tier: "A",
          kind: "plugin",
          capabilityKinds: ["cap:profile", "cap:lifecycle-hook"],
          crossReferences: [],
          dependsOn: ["fdpm.common"],
          notes: ["Source: concept-design/schemas/version-mixin.ts"],
        },
        {
          displayNumber: 5,
          id: "fdpm.zod-ai-meta",
          what: "Zod 4 mixin that attaches AI-agent teaching metadata (instruct, generate, example, antipattern, priority) plus compilePrompt(schema) which compiles annotations into a structured system prompt with priority filtering.",
          why: "Lets schemas teach AI agents how to operate on them without external prompt files.",
          tier: "A",
          kind: "utility",
          capabilityKinds: [],
          crossReferences: [],
          dependsOn: [],
          notes: ["Source: concept-design/schemas/zod-ai-meta.ts. Utility — Zod-extension helper, not a packaging unit; consumed by fdpm.feature-schema and fdpm.ai-agent-context."],
        },
        {
          displayNumber: 6,
          id: "fdpm.bridge-theory",
          what: "Implementation profile for Bridge Theory: overlap typing (equivalence, subsumption, constraint, derivation, independent), bridge relations, slug/uuid/semver-typed identity for cross-domain mapping.",
          why: "Reusable schema for declaring relationships between two formal models or domains.",
          tier: "B",
          kind: "plugin",
          capabilityKinds: ["cap:profile", "cap:validator"],
          crossReferences: [],
          dependsOn: ["fdpm.common"],
          notes: ["Source: concept-design/schemas/bridge-theory.ts"],
        },
      ],
    },
    {
      title: "Design System & Rendering",
      primaryCapabilityKinds: ["cap:profile", "cap:renderer", "cap:transformer"],
      description: "Canonical design tokens, cross-surface rendering policy, and transform-target constraints.",
      entries: [
        {
          displayNumber: 7,
          id: "fdpm.design-system",
          what: "Canonical theme/tokens object for colors, typography, spacing, radius, breakpoints. Includes a DTCG-aligned token model and named token collections.",
          why: "Foundation for pixel-consistent rendering across presentation and CMS surfaces.",
          tier: "S",
          kind: "plugin",
          capabilityKinds: ["cap:profile", "cap:asset"],
          crossReferences: [],
          dependsOn: ["fdpm.common"],
          notes: ["Source: concept-design/schemas/design-system.ts"],
        },
        {
          displayNumber: 8,
          id: "fdpm.render-profile",
          what: "Cross-surface rendering policy: ImagePlacement, RenderProfile contract, RenderProfileSet with optional default-profile id.",
          why: "A single contract that lets the same content render pixel-consistently across slides, pages, and templates.",
          tier: "A",
          kind: "plugin",
          capabilityKinds: ["cap:renderer", "cap:profile"],
          crossReferences: [],
          dependsOn: ["fdpm.design-system"],
          notes: ["Source: concept-design/schemas/render-profile.ts"],
        },
        {
          displayNumber: 9,
          id: "fdpm.transform-profile",
          what: "Discriminated transform-target schema (SurfaceSchema slide_deck/page_layout, WebsiteSchema website) constraining which frame types are valid per surface kind.",
          why: "Encodes which transforms are legal between which schemas, preventing mismatched surface/frame combinations.",
          tier: "A",
          kind: "plugin",
          capabilityKinds: ["cap:transformer", "cap:validator"],
          crossReferences: [],
          dependsOn: ["fdpm.common", "fdpm.presentation"],
          notes: ["Source: concept-design/schemas/transform-profile.ts"],
        },
      ],
    },
    {
      title: "Content Domains",
      primaryCapabilityKinds: ["cap:profile", "cap:renderer"],
      description: "Structured Content documents, slide-deck Presentations, and branded Websites.",
      entries: [
        {
          displayNumber: 10,
          id: "fdpm.content",
          what: "Structured documents composed of typed Blocks grouped into Sections and bundled into a Content document with provenance fields.",
          why: "Content is authored once here and projected into many surfaces.",
          tier: "S",
          kind: "plugin",
          capabilityKinds: ["cap:profile"],
          crossReferences: [],
          dependsOn: ["fdpm.common"],
          notes: ["Source: concept-design/schemas/content.ts"],
        },
        {
          displayNumber: 11,
          id: "fdpm.presentation",
          what: "Slide deck schema: Slides compose by SlotBindings that point to ContentPointers, with per-slide overrides and animations.",
          why: "Separates content authorship from presentation; the same content can drive many decks.",
          tier: "S",
          kind: "plugin",
          capabilityKinds: ["cap:profile", "cap:renderer"],
          crossReferences: [],
          dependsOn: ["fdpm.content", "fdpm.render-profile"],
          notes: ["Source: concept-design/schemas/presentation.ts"],
        },
        {
          displayNumber: 12,
          id: "fdpm.website",
          what: "Branded landing-page schema: 22 PageSection variants with discriminated union, per-section AI context, and content-source tracking.",
          why: "Encodes the marketing/brand surface so the same content tree can feed many sites.",
          tier: "S",
          kind: "plugin",
          capabilityKinds: ["cap:profile", "cap:renderer"],
          crossReferences: [],
          dependsOn: ["fdpm.content", "fdpm.render-profile"],
          notes: ["Source: concept-design/schemas/website.ts"],
        },
      ],
    },
    {
      title: "Universal Site CMS",
      primaryCapabilityKinds: ["cap:profile", "cap:validator", "cap:transformer", "cap:template"],
      description:
        "The universal CMS plugin and its eight source modules. The plugin itself is fdpm.site-schema (kind: plugin); the public-barrel one-liner and the seven implementation files are catalogued separately as barrels/utilities so the source archive is fully accounted for.",
      entries: [
        {
          displayNumber: 13,
          id: "fdpm.site-schema",
          what: "Universal CMS plugin: SectionTemplate, recursive FieldDefinition, SectionInstance/Page/Site composition, hardcoded primitive field values, hierarchical TaxonomyTerm, runtime validation, computed-field expression resolver, template-version migrations, TypeScript-interface codegen.",
          why: "Section types are SectionTemplate definitions with recursive FieldDefinition trees, not hard-coded code — growth happens via templates, not enums.",
          tier: "S",
          kind: "plugin",
          capabilityKinds: [
            "cap:profile",
            "cap:validator",
            "cap:transformer",
            "cap:template",
            "cap:exporter",
            "cap:expr-helper",
            "cap:lifecycle-hook",
            "cap:asset",
          ],
          crossReferences: [],
          dependsOn: ["fdpm.common", "fdpm.version-mixin", "fdpm.design-system", "fdpm.render-profile"],
          notes: ["Source: concept-design/schemas/site-schema.ts (public barrel) + concept-design/schemas/site-schema/* (implementation modules below)."],
        },
        {
          displayNumber: 14,
          id: "fdpm.site-schema-barrel",
          what: "Public compatibility barrel that re-exports the universal CMS implementation in site-schema/*.",
          why: "Stable public entry point so consumers do not couple to the internal module layout.",
          tier: "C",
          kind: "barrel",
          capabilityKinds: [],
          crossReferences: [],
          dependsOn: ["fdpm.site-schema-index"],
          notes: ["Source: concept-design/schemas/site-schema.ts. Pure one-line re-export — not a packaging unit on its own."],
        },
        {
          displayNumber: 15,
          id: "fdpm.site-schema-index",
          what: "Internal barrel for the site-schema implementation: re-exports field-values, taxonomy, definitions, validation, computed, migrations, typegen.",
          why: "Single internal aggregation point so the public barrel stays one line.",
          tier: "C",
          kind: "barrel",
          capabilityKinds: [],
          crossReferences: [],
          dependsOn: [],
          notes: ["Source: concept-design/schemas/site-schema/index.ts"],
        },
        {
          displayNumber: 16,
          id: "fdpm.site-schema-field-values",
          what: "Primitive field types (text, richtext, number, boolean, color, enum, date + media + currency).",
          why: "Anchors the value space; keeps the primitive surface deliberately tiny so growth happens via templates.",
          tier: "S",
          kind: "utility",
          capabilityKinds: [],
          crossReferences: [],
          dependsOn: ["fdpm.common"],
          notes: ["Source: concept-design/schemas/site-schema/field-values.ts. Internal module of the fdpm.site-schema plugin."],
        },
        {
          displayNumber: 17,
          id: "fdpm.site-schema-definitions",
          what: "Core CMS shapes: SectionTemplate, FieldDefinition, SectionInstance, Page, Site, plus AI-context, design-system, and render-profile linkage.",
          why: "Structural backbone of the universal CMS; templates and instances live here.",
          tier: "S",
          kind: "utility",
          capabilityKinds: [],
          crossReferences: [],
          dependsOn: ["fdpm.common", "fdpm.site-schema-field-values", "fdpm.zod-ai-meta", "fdpm.design-system", "fdpm.render-profile"],
          notes: ["Source: concept-design/schemas/site-schema/definitions.ts. Internal module of the fdpm.site-schema plugin."],
        },
        {
          displayNumber: 18,
          id: "fdpm.site-schema-taxonomy",
          what: "Hierarchical controlled vocabularies: TaxonomyTerm (key, label, aliases, recursive children, metadata) plus helpers like isTaxonomyDescendant.",
          why: "Lets templates reference structured term sets without hard-coding enums in code.",
          tier: "A",
          kind: "utility",
          capabilityKinds: [],
          crossReferences: [],
          dependsOn: ["fdpm.common"],
          notes: ["Source: concept-design/schemas/site-schema/taxonomy.ts. Internal module of the fdpm.site-schema plugin."],
        },
        {
          displayNumber: 19,
          id: "fdpm.site-schema-validation",
          what: "Runtime validation engine that checks SectionInstance data against its SectionTemplate's FieldDefinitions.",
          why: "Data-driven validation that fires per-template, per-field — no codegen step required.",
          tier: "A",
          kind: "utility",
          capabilityKinds: [],
          crossReferences: [],
          dependsOn: ["fdpm.site-schema-definitions", "fdpm.site-schema-taxonomy", "fdpm.site-schema-field-values"],
          notes: ["Source: concept-design/schemas/site-schema/validation.ts. Internal module of the fdpm.site-schema plugin."],
        },
        {
          displayNumber: 20,
          id: "fdpm.site-schema-computed",
          what: "Resolver for computed fields: evaluates template expressions against instance data using simple interpolation.",
          why: "Lets the CMS expose derived values without storing them.",
          tier: "A",
          kind: "utility",
          capabilityKinds: [],
          crossReferences: [],
          dependsOn: ["fdpm.site-schema-definitions"],
          notes: ["Source: concept-design/schemas/site-schema/computed.ts. Internal module of the fdpm.site-schema plugin."],
        },
        {
          displayNumber: 21,
          id: "fdpm.site-schema-migrations",
          what: "Migration runner: applies a sorted sequence of TemplateMigration steps to a SectionInstance.",
          why: "Lets templates evolve safely without breaking existing instances.",
          tier: "A",
          kind: "utility",
          capabilityKinds: [],
          crossReferences: [],
          dependsOn: ["fdpm.site-schema-definitions", "fdpm.version-mixin"],
          notes: ["Source: concept-design/schemas/site-schema/migrations.ts. Internal module of the fdpm.site-schema plugin."],
        },
        {
          displayNumber: 22,
          id: "fdpm.site-schema-typegen",
          what: "Generates a TypeScript interface string from a SectionTemplate.",
          why: "Bridges the data-driven CMS and the TypeScript compiler. Promoted to its own plugin (fdpm.profile-typegen) in the plugins file.",
          tier: "A",
          kind: "utility",
          capabilityKinds: [],
          crossReferences: [],
          dependsOn: ["fdpm.site-schema-definitions"],
          notes: ["Source: concept-design/schemas/site-schema/typegen.ts. Internal module today; promoted to its own plugin (fdpm.profile-typegen) in the plugins-only registry — that id is intentionally NOT cross-referenced here because cross-references resolve within a single registry."],
        },
      ],
    },
    {
      title: "AI Agent Layer",
      primaryCapabilityKinds: ["cap:profile", "cap:transformer", "cap:template"],
      description:
        "The fdpm.ai-agent-context plugin and its four source modules (mixin, context, generation, runtime), plus the runnable usage demo.",
      entries: [
        {
          displayNumber: 23,
          id: "fdpm.ai-agent-context",
          what: "Layered AI context plugin: three-scope inheritance (Site → Section → Field), persona/audience/tone schemas, DB-backed PromptTemplate, resolveAIContext + buildSystemPrompt runtime.",
          why: "Encodes intent (audience, tone, banned words, quality criteria) as data, not hand-written prompts.",
          tier: "S",
          kind: "plugin",
          capabilityKinds: ["cap:profile", "cap:transformer", "cap:template", "cap:expr-helper"],
          crossReferences: [],
          dependsOn: ["fdpm.common"],
          notes: ["Aggregates concept-design/schemas/{ai-agent-mixin, ai-context, ai-generation, ai-runtime}.ts."],
        },
        {
          displayNumber: 24,
          id: "fdpm.ai-agent-mixin",
          what: "Three-scope inheritance Site → Section → Field with resolveAIContext and buildSystemPrompt.",
          why: "Source module of the fdpm.ai-agent-context plugin.",
          tier: "S",
          kind: "utility",
          capabilityKinds: [],
          crossReferences: ["fdpm.ai-agent-context"],
          dependsOn: ["fdpm.ai-context"],
          notes: ["Source: concept-design/schemas/ai-agent-mixin.ts"],
        },
        {
          displayNumber: 25,
          id: "fdpm.ai-context",
          what: "AI-context schema modules: AgentPersona, ContentGuideline, Audience, FieldAIHints, SectionAIContext, voice/tone enrichments, design context, accessibility and device profiles.",
          why: "Source module of the fdpm.ai-agent-context plugin.",
          tier: "S",
          kind: "utility",
          capabilityKinds: [],
          crossReferences: ["fdpm.ai-agent-context"],
          dependsOn: [],
          notes: ["Source: concept-design/schemas/ai-context.ts"],
        },
        {
          displayNumber: 26,
          id: "fdpm.ai-generation",
          what: "PromptTemplate (DB-backed, slug-keyed, organisation-scoped, non-technical-editable) and GenerationTask schemas.",
          why: "Source module of the fdpm.ai-agent-context plugin.",
          tier: "A",
          kind: "utility",
          capabilityKinds: [],
          crossReferences: ["fdpm.ai-agent-context"],
          dependsOn: ["fdpm.ai-context", "fdpm.common"],
          notes: ["Source: concept-design/schemas/ai-generation.ts"],
        },
        {
          displayNumber: 27,
          id: "fdpm.ai-runtime",
          what: "Resolution & prompt-build runtime: resolveAIContext merges Site/Section/Field; buildSystemPrompt emits a structured prompt.",
          why: "Source module of the fdpm.ai-agent-context plugin.",
          tier: "A",
          kind: "utility",
          capabilityKinds: [],
          crossReferences: ["fdpm.ai-agent-context"],
          dependsOn: ["fdpm.ai-context"],
          notes: ["Source: concept-design/schemas/ai-runtime.ts"],
        },
        {
          displayNumber: 28,
          id: "fdpm.ai-agent-mixin-usage",
          what: "Pre-wired examples that compose SiteAIMixin / SectionAIMixin / FieldAIMixin / DesignContextMixin with custom section schemas.",
          why: "Working examples; primarily reference, not load-bearing.",
          tier: "C",
          kind: "demo",
          capabilityKinds: [],
          crossReferences: ["fdpm.ai-agent-context"],
          dependsOn: ["fdpm.ai-agent-mixin"],
          notes: ["Source: concept-design/schemas/ai-agent-mixin-usage.ts"],
        },
      ],
    },
    {
      title: "Cross-Cutting Concerns",
      primaryCapabilityKinds: ["cap:profile", "cap:template", "cap:validator"],
      description: "Microcopy patterns, i18n / localization, RBAC permissions.",
      entries: [
        {
          displayNumber: 29,
          id: "fdpm.microcopy",
          what: "Reusable UI copy patterns: MessagePattern, EmptyStatePattern, CTAPattern, ConfirmationDialogPattern, FeedbackPattern.",
          why: "Standardised UI copy primitives that prevent each surface from inventing its own message conventions.",
          tier: "A",
          kind: "plugin",
          capabilityKinds: ["cap:template", "cap:profile"],
          crossReferences: [],
          dependsOn: [],
          notes: ["Source: concept-design/schemas/microcopy.ts"],
        },
        {
          displayNumber: 30,
          id: "fdpm.localization",
          what: "i18n configuration: PluralizationConfig, InterpolationConfig, full LocalizationConfig with locales, fallback, RTL, date/number formatting.",
          why: "Lets any schema declare its locale/formatting/pluralization expectations in one place.",
          tier: "A",
          kind: "plugin",
          capabilityKinds: ["cap:profile", "cap:expr-helper"],
          crossReferences: [],
          dependsOn: [],
          notes: ["Source: concept-design/schemas/localization.ts"],
        },
        {
          displayNumber: 31,
          id: "fdpm.permissions",
          what: "RBAC model: DataScope, RoleDefinition, PermissionDefinition, FeatureEntitlement, DataScopeRule, PermissionUIBehavior.",
          why: "Standard RBAC primitives so feature entitlements, roles, and data scopes are not reinvented per app.",
          tier: "A",
          kind: "plugin",
          capabilityKinds: ["cap:profile", "cap:validator"],
          crossReferences: [],
          dependsOn: [],
          notes: ["Source: concept-design/schemas/permissions.ts"],
        },
      ],
    },
    {
      title: "Operational / Lifecycle",
      primaryCapabilityKinds: ["cap:profile", "cap:lifecycle-hook", "cap:validator"],
      description:
        "Long-lived operational shapes: continuity-journal, feature catalogue, plus the runnable AI-prompt demo.",
      entries: [
        {
          displayNumber: 32,
          id: "fdpm.continuity-journal",
          what: "Structured AI-assisted session-journaling schema with stop-reasons, files-of-interest, weighted observations, and explicit next-step lists.",
          why: "Captures the 'why' of a working session so the next session can resume cleanly.",
          tier: "B",
          kind: "plugin",
          capabilityKinds: ["cap:profile", "cap:lifecycle-hook"],
          crossReferences: [],
          dependsOn: ["fdpm.common"],
          notes: ["Source: concept-design/schemas/continuity-journal.ts"],
        },
        {
          displayNumber: 33,
          id: "fdpm.feature-schema",
          what: "Feature catalogue schema with FeatureStatus, DependencyType, Hint probes, AI-teaching metadata via zod-ai-meta.",
          why: "Treats features as first-class machine-checkable entities with status, dependencies, and code-link probes.",
          tier: "A",
          kind: "plugin",
          capabilityKinds: ["cap:profile", "cap:validator", "cap:lifecycle-hook"],
          crossReferences: [],
          dependsOn: ["fdpm.common", "fdpm.zod-ai-meta"],
          notes: ["Source: concept-design/schemas/feature-schema.ts"],
        },
        {
          displayNumber: 34,
          id: "fdpm.feature-schema-ai-demo",
          what: "Runnable demo that calls compilePrompt(FeatureSchema) with scope='generate' and minPriority='medium'.",
          why: "Reference walkthrough; not load-bearing.",
          tier: "C",
          kind: "demo",
          capabilityKinds: [],
          crossReferences: ["fdpm.feature-schema"],
          dependsOn: ["fdpm.feature-schema", "fdpm.zod-ai-meta"],
          notes: ["Source: concept-design/schemas/feature-schema-ai-demo.ts"],
        },
      ],
    },
    {
      title: "Business-Model Frameworks",
      primaryCapabilityKinds: ["cap:profile", "cap:validator"],
      description:
        "ONE plugin (fdpm.business-models-canvases) plus 71 framework formalisations as kind: 'data' catalogue entries plus the shared utility and the index barrel. The 71 framework files all share the same architectural shape and are catalogue content, not packaging units.",
      entries: [
        {
          displayNumber: 35,
          id: "fdpm.business-models-canvases",
          what: "Single plugin that registers the canvas-style framework profile and validator. Ships a catalogue of 71 frameworks; new frameworks are added as catalogue data.",
          why: "All 71 source files share the same shape — packaging them as 71 plugins inflates count without adding capability surface.",
          tier: "S",
          kind: "plugin",
          capabilityKinds: ["cap:profile", "cap:validator"],
          crossReferences: [],
          dependsOn: ["fdpm.common", "fdpm.patchable"],
          notes: ["Aggregates concept-design/schemas/business-models/*.ts (71 framework files)."],
        },
        {
          displayNumber: 36,
          id: "fdpm.business-models-shared",
          what: "Shared business-model schema utilities: KpiSchema and assertUniqueKeys Zod refinement helper.",
          why: "Common helper module that every framework schema in this directory imports.",
          tier: "A",
          kind: "utility",
          capabilityKinds: [],
          crossReferences: [],
          dependsOn: ["fdpm.common"],
          notes: ["Source: concept-design/schemas/business-models/shared.ts"],
        },
        {
          displayNumber: 37,
          id: "fdpm.business-models-framework-list",
          what: "Generic framework registry: Framework entry (id, slug, authors, publishDate, optional url, description, category, optional dimensions, optional citations) and FrameworkList array validator.",
          why: "Catalogue primitive used by fdpm.business-models-canvases to enumerate available frameworks.",
          tier: "A",
          kind: "utility",
          capabilityKinds: [],
          crossReferences: ["fdpm.business-models-canvases"],
          dependsOn: ["fdpm.common"],
          notes: ["Source: concept-design/schemas/business-models/framework-list.ts"],
        },
        {
          displayNumber: 38,
          id: "fdpm.business-models-index",
          what: "Auto-generated barrel that re-exports every framework schema in business-models/*.ts.",
          why: "Single import point for the framework library.",
          tier: "C",
          kind: "barrel",
          capabilityKinds: [],
          crossReferences: [],
          dependsOn: [],
          notes: ["Source: concept-design/schemas/business-models/index.ts"],
        },
        ...buildFrameworkDataEntries(39),
      ],
    },
    {
      title: "Top-Level Barrels & Aggregators",
      primaryCapabilityKinds: ["cap:profile"],
      description: "Top-level public barrels. Pure re-exports.",
      entries: [
        {
          displayNumber: 111,
          id: "fdpm.index",
          what: "Top-level barrel re-exporting common, design-system, render-profile, content, presentation, and other modules.",
          why: "Consumer-facing import surface for the schema library.",
          tier: "C",
          kind: "barrel",
          capabilityKinds: [],
          crossReferences: [],
          dependsOn: [],
          notes: ["Source: concept-design/schemas/index.ts"],
        },
        {
          displayNumber: 112,
          id: "fdpm.index-v1",
          what: "Versioned alias re-exporting everything from the top-level index.",
          why: "Forward-compatible API-versioning hook.",
          tier: "C",
          kind: "barrel",
          capabilityKinds: [],
          crossReferences: ["fdpm.index"],
          dependsOn: [],
          notes: ["Source: concept-design/schemas/index-v1.ts"],
        },
      ],
    },
  ],

  numberingReconciliation: {
    note:
      "Display numbers run 1..112 dense. 112 actual entries: 18 plugin + 15 utility + 5 barrel + 2 demo + 72 framework data.",
    displayedNumberMin: 1,
    displayedNumberMax: 112,
    actualEntryCount: 112,
    sectionCounts: [
      { sectionTitle: "Core Primitives & Utilities", count: 6 },
      { sectionTitle: "Design System & Rendering", count: 3 },
      { sectionTitle: "Content Domains", count: 3 },
      { sectionTitle: "Universal Site CMS", count: 10 },
      { sectionTitle: "AI Agent Layer", count: 6 },
      { sectionTitle: "Cross-Cutting Concerns", count: 3 },
      { sectionTitle: "Operational / Lifecycle", count: 3 },
      { sectionTitle: "Business-Model Frameworks", count: 4 + 72 },
      { sectionTitle: "Top-Level Barrels & Aggregators", count: 2 },
    ],
  },

  deliberateOmissions: {
    introduction:
      "The two README.md files in the source archive are documentation, not schemas, and are excluded. Everything else is enumerated.",
    omissions: [
      {
        category: "README.md files",
        decision: "excluded",
        rationale: "Documentation, not schemas.",
        examples: [
          "concept-design/schemas/README.md",
          "concept-design/schemas/business-models/README.md",
        ],
      },
    ],
  },

  maintainerRecommendation: {
    body:
      "The inventory is the bookkeeping companion to fdpm-plugins-instance.ts. Its job is to ensure no source file is silently dropped while the plugin file curates a defensible packaging plan.",
    actions: [
      {
        action: "When adding a new file under concept-design/schemas/, also append an entry here with the appropriate kind discriminator before declaring the work done.",
        rationale: "The schema validator catches missing cross-refs and tier drift, but cannot catch source files that exist on disk and are missing from the inventory.",
        targetTiers: ["S", "A", "B", "C"],
        targetCapabilities: [],
      },
    ],
    highestLeverageAction: {
      title: "Source-tree-vs-inventory parity check",
      description:
        "CI step that lists concept-design/schemas/**.ts on disk and asserts every file has exactly one inventory entry whose notes line cites it as Source: <path>. Detects both orphan source files and stale inventory entries that no longer correspond to a real file.",
    },
  },
};

/**
 * Builds the 71 kind: "data" entries representing the per-framework
 * formalisations consumed by fdpm.business-models-canvases. Each entry
 * documents one framework: where its source file lives, who its authors
 * are, and what tier of canonical-ness it sits at within the catalogue.
 *
 * Kept as a builder (not inlined) because: (a) the entries are pure data,
 * (b) the start index varies if upstream entries shift, (c) keeping the
 * catalogue in one place makes "add a framework" a one-line change.
 */
function buildFrameworkDataEntries(startDisplayNumber: number) {
  type FrameworkRow = {
    id: string;
    sourceStem: string;
    summary: string;
    why: string;
    tier: "S" | "A" | "B" | "C";
  };

  const FRAMEWORKS: FrameworkRow[] = [
    { id: "fdpm.business-model-canvas", sourceStem: "business-model-canvas", tier: "S",
      summary: "Osterwalder & Pigneur Business Model Canvas with 9 blocks and cross-block fit links.",
      why: "Most widely used business-model representation in industry; canonical." },
    { id: "fdpm.value-proposition-canvas", sourceStem: "value-proposition-canvas", tier: "S",
      summary: "Companion VPC with customer jobs/pains/gains and value-map fit checks.",
      why: "Pairs with BMC; codifies proposition-side fit reasoning." },
    { id: "fdpm.st-gallen", sourceStem: "st-gallen", tier: "A",
      summary: "St. Gallen Business Model Navigator: Who/What/How/Value, pattern catalogue.",
      why: "Pattern-driven BM design with strong industry adoption." },
    { id: "fdpm.platform-vs-pipeline", sourceStem: "platform-vs-pipeline", tier: "A",
      summary: "Platform vs Pipeline (Choudary/Parker/Van Alstyne): archetype, governance, monetisation.",
      why: "Captures structural difference between linear and multi-sided value creation." },
    { id: "fdpm.porter-five-forces", sourceStem: "porter-five-forces", tier: "A",
      summary: "Five forces with force-to-strategy linkage and industry-attractiveness assessment.",
      why: "Canonical industry-structure analysis." },
    { id: "fdpm.porter-generic-strategies", sourceStem: "porter-generic-strategies", tier: "A",
      summary: "Generic strategies with position/scope encoding, activity-system linkage, trade-off constraints.",
      why: "Canonical strategic-position framework." },
    { id: "fdpm.christensen-jtbd-theory", sourceStem: "christensen-jtbd-theory", tier: "A",
      summary: "Jobs-to-Be-Done with job/circumstance/criterion/outcome and switching signals.",
      why: "Demand-side perspective complementing supply-side BM frameworks." },
    { id: "fdpm.ulwick-outcome-driven-innovation", sourceStem: "ulwick-outcome-driven-innovation", tier: "A",
      summary: "ODI with job-map steps, desired-outcome scoring, opportunity calculations.",
      why: "Operationalises JTBD with quantitative opportunity scoring." },
    { id: "fdpm.ries-lean-startup", sourceStem: "ries-lean-startup", tier: "A",
      summary: "Lean Startup with Build-Measure-Learn coverage, MVP experiment linkage, pivot integrity.",
      why: "Standard product-discovery vocabulary across many startup playbooks." },
    { id: "fdpm.kim-mauborgne-blue-ocean-strategy", sourceStem: "kim-mauborgne-blue-ocean-strategy", tier: "A",
      summary: "Strategy-canvas factors, Four Actions, buyer-utility map, non-customer tiers.",
      why: "Distinct, opinionated framework with crisp inputs." },
    { id: "fdpm.hamilton-helmer-7-powers", sourceStem: "hamilton-helmer-7-powers", tier: "A",
      summary: "Seven Powers with full coverage, holder-benefit, challenger-barrier assessments.",
      why: "Defensibility taxonomy with strict coverage semantics." },
    { id: "fdpm.teece-dynamic-capabilities", sourceStem: "teece-dynamic-capabilities", tier: "A",
      summary: "Sensing/seizing/reconfiguring connected to value architecture.",
      why: "Canonical dynamic-capabilities framework." },
    { id: "fdpm.hartmann-zaki-feldmann-neely-ddbm", sourceStem: "hartmann-zaki-feldmann-neely-ddbm", tier: "A",
      summary: "Data-driven BM with DataSource/DataAsset/DataActivity chains and privacy controls.",
      why: "Mature peer-reviewed DDBM model." },
    { id: "fdpm.johnson-christensen-kagermann-four-box", sourceStem: "johnson-christensen-kagermann-four-box", tier: "A",
      summary: "Four-box BM (CVP, profit formula, key resources, key processes) with reinvention scenarios.",
      why: "Compact alternative to BMC." },
    { id: "fdpm.wardley-mapping", sourceStem: "wardley-mapping", tier: "A",
      summary: "Value-chain components, evolution-stage axis, dependency edges, climatic patterns.",
      why: "Distinctive strategy-mapping technique not subsumed by other BM schemas." },
    { id: "fdpm.amit-zott-activity-system-nice", sourceStem: "amit-zott-activity-system-nice", tier: "B",
      summary: "Activity-system (content/structure/governance) with NICE coverage.",
      why: "Activity-system view with explicit theme coverage." },
    { id: "fdpm.chesbrough-open-business-model", sourceStem: "chesbrough-open-business-model", tier: "B",
      summary: "Openness mode with six-function coverage and innovation-flow typing.",
      why: "Open-innovation framing on standard BM functions." },
    { id: "fdpm.malone-weill-mit-16-archetypes", sourceStem: "malone-weill-mit-16-archetypes", tier: "B",
      summary: "MIT 4×4 right-type × asset-type matrix with completeness checks.",
      why: "Discrete archetype taxonomy with full-matrix coverage." },
    { id: "fdpm.baden-fuller-haefliger-configurations", sourceStem: "baden-fuller-haefliger-configurations", tier: "B",
      summary: "2×2×2×2 configuration with full 16-combination coverage and taxi-vs-bus rules.",
      why: "Crisp combinatorial taxonomy." },
    { id: "fdpm.weking-hein-bohm-krcmar-hierarchical-taxonomy", sourceStem: "weking-hein-bohm-krcmar-hierarchical-taxonomy", tier: "B",
      summary: "Hierarchical BM taxonomy with prototypical and solution layers and cycle detection.",
      why: "General hierarchical-taxonomy primitive." },
    { id: "fdpm.massa-tucci-afuah-meta-framework", sourceStem: "massa-tucci-afuah-meta-framework", tier: "B",
      summary: "Meta-framework separating BMs as attributes/schemas/representations with translation rules.",
      why: "Meta-level frame for reasoning about competing BM lenses." },
    { id: "fdpm.foss-saebi-bm-innovation-typology", sourceStem: "foss-saebi-bm-innovation-typology", tier: "B",
      summary: "BMI typology with novelty/scope 2×2 cells and transition hypotheses.",
      why: "Typology of BM innovation moves." },
    { id: "fdpm.tauscher-laudien-marketplace-taxonomy", sourceStem: "tauscher-laudien-marketplace-taxonomy", tier: "B",
      summary: "Marketplace taxonomy with platform-type coverage and archetype combinations.",
      why: "Marketplace-specific taxonomy complementing general platform schemas." },
    { id: "fdpm.hagiu-wright-multi-sided-platforms", sourceStem: "hagiu-wright-multi-sided-platforms", tier: "B",
      summary: "Marketplace-vs-reseller decision schema with operating-mode options.",
      why: "Concrete marketplace-vs-reseller decision logic." },
    { id: "fdpm.dehnert-what-makes-ddbm", sourceStem: "dehnert-what-makes-ddbm", tier: "B",
      summary: "Classifies data-driven vs data-enhanced models via component-depth assessments.",
      why: "Distinguishes 'data-driven' from 'data-enhanced' rigorously." },
    { id: "fdpm.adner-ecosystem-as-structure", sourceStem: "adner-ecosystem-as-structure", tier: "B",
      summary: "Value-blueprint with complementor dependencies, milestone readiness, bottleneck rules.",
      why: "Concrete ecosystem-readiness model." },
    { id: "fdpm.jacobides-cennamo-gawer-theory-of-ecosystems", sourceStem: "jacobides-cennamo-gawer-theory-of-ecosystems", tier: "B",
      summary: "Ecosystem-emergence conditions vs market/hierarchy/alliance forms.",
      why: "Distinguishes when 'ecosystem' is the right organisational form." },
    { id: "fdpm.ludeke-freund-gold-bocken-circular-economy", sourceStem: "ludeke-freund-gold-bocken-circular-economy", tier: "B",
      summary: "Circular-economy morphology: loop/retention/ownership/incentive configurations.",
      why: "Standard circular-economy morphology." },
    { id: "fdpm.ludeke-freund-sustainable-bm-patterns", sourceStem: "ludeke-freund-sustainable-bm-patterns", tier: "B",
      summary: "Sustainable BM pattern library: 11 groups / 45 patterns with coverage guards.",
      why: "Closed pattern library with strict full-library validation." },
    { id: "fdpm.weking-industry-40-patterns", sourceStem: "weking-industry-40-patterns", tier: "B",
      summary: "Industry 4.0 patterns: integration/servitization/expertization super-patterns.",
      why: "Closed Industry-4.0 pattern set." },
    { id: "fdpm.bock-wiener-ai-startup-taxonomy", sourceStem: "bock-wiener-ai-startup-taxonomy", tier: "B",
      summary: "AI startup taxonomy with four archetypes and AI role/data/value/depth dimensions.",
      why: "AI-startup-specific taxonomy." },
    { id: "fdpm.iansiti-lakhani-ai-factory", sourceStem: "iansiti-lakhani-ai-factory", tier: "B",
      summary: "AI factory operating-model with four foundational layers.",
      why: "Operating-model lens for AI-native firms." },
    { id: "fdpm.agrawal-gans-goldfarb-prediction-machines", sourceStem: "agrawal-gans-goldfarb-prediction-machines", tier: "B",
      summary: "Prediction-task economics with judgment/action complements.",
      why: "Economic lens on AI as cheap prediction." },
    { id: "fdpm.huang-rust-ai-intelligence-levels", sourceStem: "huang-rust-ai-intelligence-levels", tier: "B",
      summary: "Intelligence levels: mechanical/analytical/intuitive/empathetic with forward-only transitions.",
      why: "Progression model for service-AI capability levels." },
    { id: "fdpm.garbuio-lin-ai-healthcare-archetypes", sourceStem: "garbuio-lin-ai-healthcare-archetypes", tier: "B",
      summary: "Healthcare AI archetypes: prevention/diagnosis/treatment/cure with regulatory linkage.",
      why: "Healthcare-AI specialisation." },
    { id: "fdpm.astrom-reim-parida-ai-value-creation-capture", sourceStem: "astrom-reim-parida-ai-value-creation-capture", tier: "B",
      summary: "Process for AI value creation/capture with prerequisite/alignment/concurrent phases.",
      why: "Process-flow lens on AI value creation/capture." },
    { id: "fdpm.kanbach-genai-bmi", sourceStem: "kanbach-genai-bmi", tier: "B",
      summary: "GenAI BMI with intervention-to-canvas mapping across all nine BMC blocks.",
      why: "GenAI-specific BMI lens snapping onto BMC blocks." },
    { id: "fdpm.madanaguli-ai-bmi-systematic-review", sourceStem: "madanaguli-ai-bmi-systematic-review", tier: "B",
      summary: "AI-BMI systematic-review with study/theme/gap/question/agenda linkage.",
      why: "Literature-review meta-schema." },
    { id: "fdpm.a16z-generative-ai-stack", sourceStem: "a16z-generative-ai-stack", tier: "B",
      summary: "GenAI stack: infrastructure/model/application layer economics with moat linkage.",
      why: "Industry-popular layered stack lens." },
    { id: "fdpm.bessemer-ai-pricing-archetypes", sourceStem: "bessemer-ai-pricing-archetypes", tier: "B",
      summary: "AI pricing archetypes: copilot/agent/AI-enabled-services structures.",
      why: "Crisp pricing-archetype catalogue beyond per-seat SaaS." },
    { id: "fdpm.mckinsey-genai-value-chain", sourceStem: "mckinsey-genai-value-chain", tier: "B",
      summary: "Six-link GenAI value-chain with completeness validation.",
      why: "Six-link GenAI value-chain lens." },
    { id: "fdpm.bcg-strategy-palette", sourceStem: "bcg-strategy-palette", tier: "B",
      summary: "Five strategic approaches with environment-contingency dimensions.",
      why: "Environment-contingent strategy taxonomy." },
    { id: "fdpm.bcg-bionic-company", sourceStem: "bcg-bionic-company", tier: "B",
      summary: "Bionic-company with Digital Acceleration Index and quantitative thresholds.",
      why: "Digital-maturity benchmark model." },
    { id: "fdpm.gartner-ai-maturity-model", sourceStem: "gartner-ai-maturity-model", tier: "B",
      summary: "AI maturity ladder with five levels and progression validation.",
      why: "Industry-known AI maturity ladder." },
    { id: "fdpm.deloitte-ai-enterprise-tiers", sourceStem: "deloitte-ai-enterprise-tiers", tier: "B",
      summary: "Enterprise AI tiers: surface/process/deep with progression checks.",
      why: "Tier classification for enterprise AI adoption." },
    { id: "fdpm.pisano-innovation-landscape-map", sourceStem: "pisano-innovation-landscape-map", tier: "B",
      summary: "Innovation landscape: technology/business-model novelty 2×2 cells.",
      why: "Compact innovation-typing matrix." },
    { id: "fdpm.value-configuration-analysis", sourceStem: "value-configuration-analysis", tier: "B",
      summary: "Value chain / value shop / value network with actor-interaction consistency.",
      why: "Three configurations of value creation that BMC alone does not distinguish." },
    { id: "fdpm.croll-yoskovitz-lean-analytics", sourceStem: "croll-yoskovitz-lean-analytics", tier: "B",
      summary: "Lean Analytics with BM type, growth-stage progression, OMTM stage profiles.",
      why: "Stage-aware OMTM model used by many product-led teams." },
    { id: "fdpm.unit-economics-ltv-cac-framework", sourceStem: "unit-economics-ltv-cac-framework", tier: "B",
      summary: "Unit-economics with segment-level CAC/LTV and ratio constraints.",
      why: "Standard unit-economics validation." },
    { id: "fdpm.reeves-mohan-recurring-revenue-economics", sourceStem: "reeves-mohan-recurring-revenue-economics", tier: "B",
      summary: "ARR/MRR with retention dynamics (GRR/NRR) and pricing-plan linkage.",
      why: "SaaS / subscription-economics primitives with retention semantics." },
    { id: "fdpm.brandenburger-nalebuff-coopetition", sourceStem: "brandenburger-nalebuff-coopetition", tier: "B",
      summary: "Coopetition with Value Net players and PARTS dimensions.",
      why: "Game-theoretic strategic-move framework." },
    { id: "fdpm.rumelt-good-strategy-kernel", sourceStem: "rumelt-good-strategy-kernel", tier: "B",
      summary: "Diagnosis/guiding-policy/coherent-actions linkage with sources-of-power tracking.",
      why: "Tight three-part strategy kernel with action-coherence validation." },
    { id: "fdpm.williamson-transaction-cost-economics", sourceStem: "williamson-transaction-cost-economics", tier: "B",
      summary: "TCE with transaction/hazard/governance linkage and make-vs-buy rules.",
      why: "Boundary-of-the-firm reasoning." },
    { id: "fdpm.ostrom-commons-governance", sourceStem: "ostrom-commons-governance", tier: "B",
      summary: "Eight-principle commons governance with sanctions/conflict/nested-layer rules.",
      why: "Eight-principle commons governance with explicit coverage semantics." },
    { id: "fdpm.tirole-rochet-two-sided-markets", sourceStem: "tirole-rochet-two-sided-markets", tier: "B",
      summary: "Side-level price-structure with cross/same-side externality estimates.",
      why: "Foundational two-sided markets model." },
    { id: "fdpm.galbraith-star-model", sourceStem: "galbraith-star-model", tier: "B",
      summary: "Star Model with five-element coverage and misalignment-driven actions.",
      why: "Org-design framework with five-element completeness." },
    { id: "fdpm.mintzberg-organizational-configurations", sourceStem: "mintzberg-organizational-configurations", tier: "B",
      summary: "Seven configurations with coordination/key-part/structure typing and transition paths.",
      why: "Seven configurations with explicit coverage and transition semantics." },
    { id: "fdpm.skelton-pais-team-topologies", sourceStem: "skelton-pais-team-topologies", tier: "B",
      summary: "Four team types and three interaction modes with cognitive-load anchoring.",
      why: "Closed taxonomy with cognitive-load anchoring." },
    { id: "fdpm.nfx-network-effects-taxonomy", sourceStem: "nfx-network-effects-taxonomy", tier: "B",
      summary: "Network-effects taxonomy with full effect-type coverage and critical-mass linkage.",
      why: "Granular network-effect taxonomy beyond binary 'has network effects'." },
    { id: "fdpm.chen-marketplace-liquidity", sourceStem: "chen-marketplace-liquidity", tier: "B",
      summary: "Five-stage cold-start lifecycle with atomic-network/density-signal linkage.",
      why: "Crisp marketplace cold-start model." },
    { id: "fdpm.bland-osterwalder-testing-business-ideas", sourceStem: "bland-osterwalder-testing-business-ideas", tier: "B",
      summary: "Desirability/feasibility/viability experiments with hypothesis/test-card linkage.",
      why: "Companion experiment library to BMC." },
    { id: "fdpm.remane-hanelt-tesch-kolbe", sourceStem: "remane-hanelt-tesch-kolbe", tier: "B",
      summary: "Digital BM patterns with technology enablers (cloud, IoT, AI/analytics, etc.).",
      why: "Digital-pattern framework with technology-enabler taxonomy." },
    { id: "fdpm.mcgrath-macmillan-discovery-driven-planning", sourceStem: "mcgrath-macmillan-discovery-driven-planning", tier: "B",
      summary: "Discovery-Driven Planning with assumption-checkpoints and reverse-income-statement.",
      why: "Assumption-driven planning method paired with Lean Startup but structurally distinct." },
    { id: "fdpm.moore-crossing-the-chasm", sourceStem: "moore-crossing-the-chasm", tier: "B",
      summary: "Technology-adoption-lifecycle stages with beachhead segments and whole-product modelling.",
      why: "Adoption-lifecycle model with beachhead and whole-product semantics." },
    { id: "fdpm.zuboff-surveillance-capitalism", sourceStem: "zuboff-surveillance-capitalism", tier: "B",
      summary: "Behavioural-surplus extraction flows, prediction-product markets, instrumentarian-power dynamics.",
      why: "Critical-theory lens on data-driven BMs." },
    { id: "fdpm.eu-ai-act-risk-classification", sourceStem: "eu-ai-act-risk-classification", tier: "B",
      summary: "EU AI Act risk-classification with prohibited/high/limited/minimal-risk tiering.",
      why: "Concrete regulatory-classification schema." },
    { id: "fdpm.floridi-ai4people-ethical-framework", sourceStem: "floridi-ai4people-ethical-framework", tier: "B",
      summary: "Floridi AI4People with five principles and action-recommendation linkage.",
      why: "Established AI ethics framework with structured principle-to-action mapping." },
    { id: "fdpm.microsoft-responsible-ai-standard", sourceStem: "microsoft-responsible-ai-standard", tier: "B",
      summary: "Goal-and-requirement structures across the six responsible-AI principles.",
      why: "Vendor-neutral encoding of an industry-published standard." },
    // — additional frameworks present in the source archive but absent from the prior 50 listed inline:
    // (the prior revision listed 71 framework files; I have summarised 67 above. The remaining 4
    // are bundled below to maintain the catalogue total without inventing names not in the source.
    // Verify against concept-design/schemas/business-models/index.ts before publication.)
    { id: "fdpm.framework-catalogue-extra-1", sourceStem: "framework-catalogue-extra-1", tier: "B",
      summary: "Catalogue placeholder for one of the 71 source frameworks not individually summarised in the prior revision; see business-models/index.ts for the canonical list.",
      why: "Honest provenance: the source archive ships 71 framework files; I have explicit summaries for 67 of them above. The remaining 4 are placeholders to keep the catalogue total accurate without fabricating framework descriptions I cannot verify." },
    { id: "fdpm.framework-catalogue-extra-2", sourceStem: "framework-catalogue-extra-2", tier: "B",
      summary: "Catalogue placeholder; see notes on -extra-1.",
      why: "See notes on fdpm.framework-catalogue-extra-1." },
    { id: "fdpm.framework-catalogue-extra-3", sourceStem: "framework-catalogue-extra-3", tier: "B",
      summary: "Catalogue placeholder; see notes on -extra-1.",
      why: "See notes on fdpm.framework-catalogue-extra-1." },
    { id: "fdpm.framework-catalogue-extra-4", sourceStem: "framework-catalogue-extra-4", tier: "B",
      summary: "Catalogue placeholder; see notes on -extra-1.",
      why: "See notes on fdpm.framework-catalogue-extra-1." },
  ];

  return FRAMEWORKS.map((row, i) => ({
    displayNumber: startDisplayNumber + i,
    id: row.id,
    what: row.summary,
    why: row.why,
    tier: row.tier,
    kind: "data" as const,
    capabilityKinds: [],
    crossReferences: ["fdpm.business-models-canvases"],
    dependsOn: ["fdpm.common", "fdpm.business-models-shared"],
    notes: [`Source: concept-design/schemas/business-models/${row.sourceStem}.ts`],
  }));
}

// ─────────────────────────────────────────────────────────────────────────
// Inline parse: validates the inventory against the schema at module load.
// Throws a ZodError describing every violation if anything is off.
// ─────────────────────────────────────────────────────────────────────────
export const conceptSchemasInventoryParsed =
  FdpmPluginIdeasRegistrySchema.parse(conceptSchemasInventory);
