/**
 * Schema instance for docs/drafts/customer-service-250-additional-domain-profiles.md.
 *
 * 250 customer-service domain-profile entries (#34-#283), all under the
 * single section "Domain profiles — Customer Service / Support Operations".
 *
 * Notes on shape mismatches with the FDPM-shaped schema:
 *
 * - IDs use the `customer-service.` namespace, not `fdpm.`. The schema's
 *   FdpmPluginIdSchema accepts any kebab-namespace.<segment>(.<segment>)*
 *   form, so this is fine — but the schema name is FDPM-flavored. Treat
 *   this instance as "the plugin-ideas-registry shape applied to a
 *   different namespace."
 *
 * - Source has only one section. `cap:profile` is the only capability.
 *
 * - Display numbers run #34-#283. The first 33 entries from the original
 *   sample document are not in this file; they were the reference data
 *   used to model the expansion. No cross-references to those omitted
 *   entries appear in the rows, so the schema's cross-reference check
 *   is satisfied.
 *
 * - Tier definitions in the source live in a "Notes" section at the
 *   bottom rather than a preamble; lifted into honestPreamble.tierDefinitions
 *   here. Tier C definition is loosely worded in source ("niche, domain-
 *   specific, or included mostly for coverage completeness") — preserved
 *   verbatim.
 */

import {
  FdpmPluginIdeasRegistrySchema,
  type FdpmPluginIdeasRegistry,
  type PluginEntry,
  type Tier,
} from "./plugins.js";

const profile = (
  displayNumber: number,
  id: string,
  what: string,
  why: string,
  tier: Tier,
): PluginEntry => ({
  displayNumber,
  id,
  what,
  why,
  tier,
  capabilityKinds: ["cap:profile"],
  crossReferences: [],
  notes: [],
});

export const customerService250Registry: FdpmPluginIdeasRegistry = {
  schemaVersion: "1.0.0",

  frontmatter: {
    title: "Customer Service domain profile ideas — 250 additional entries",
    status: "draft",
    disclaimer:
      "No information in this document should be taken for granted. The 250 entries below are a brainstorm extending a 33-entry Atendimento / Customer Service sample; tier ratings are subjective calibration aids, not verdicts. Capability mapping is uniform (cap:profile) because the source contains only domain profiles.",
    provenance: {
      sourceRequest: "Use this document as model. Create 250 more. English pls.",
      baseline:
        "fdpm-250-plugins.md and the pasted Customer Service table (33 entries, #1-#33, not included in this file)",
      capabilityKindsReferenced: {
        count: 1,
        kinds: ["cap:profile"],
        note: "Source contains only domain-profile entries; no other capability kinds appear.",
      },
    },
  },

  heading: "Customer Service domain profile ideas — 250 additional entries",

  honestPreamble: {
    body:
      "This file extends the provided Customer Service table in English, preserving the same columns: #, id, what, why, and tier.",
    tierDefinitions: [
      { tier: "S", meaning: "core operational object with strong first-party value." },
      {
        tier: "A",
        meaning:
          "strong and likely useful, but may depend on industry, maturity, or integration depth.",
      },
      {
        tier: "B",
        meaning: "plausible but more situational or overlapping with stronger objects.",
      },
      {
        tier: "C",
        meaning: "niche, domain-specific, or included mostly for coverage completeness.",
      },
    ],
    tierDistribution: {
      totalEntries: 250,
      rows: [
        { tier: "S", count: 105 },
        { tier: "A", count: 123 },
        { tier: "B", count: 21 },
        { tier: "C", count: 1 },
      ],
    },
    notes: [],
  },

  sections: [
    {
      title: "Domain profiles — Customer Service / Support Operations",
      primaryCapabilityKinds: ["cap:profile"],
      description:
        "Single-section document. Display numbers continue after the 33-entry sample (#1-#33), starting at #34.",
      entries: [
        profile(34, "customer-service.account", "Commercial or service account that groups customers, contracts, entitlements, and interactions", "Many service operations are account-centric rather than person-centric; account context improves routing and SLA interpretation", "S"),
        profile(35, "customer-service.identity-verification", "Verification events, methods, confidence levels, and failed authentication attempts", "Protects customers and agents before sensitive actions are performed", "S"),
        profile(36, "customer-service.consent", "Permissions for recording, messaging, data use, callbacks, and marketing follow-up", "Customer communication and privacy workflows require explicit consent tracking", "S"),
        profile(37, "customer-service.preference", "Customer language, channel, accessibility, time-window, and communication preferences", "Personalized service depends on respecting stable customer preferences", "A"),
        profile(38, "customer-service.segment", "Operational customer segment such as SMB, enterprise, VIP, regulated, or vulnerable customer", "Segmentation affects prioritization, language, escalation, and reporting", "A"),
        profile(39, "customer-service.entitlement", "Support rights, plan limits, covered products, response commitments, and renewal state", "Agents need to know what service the customer is contractually entitled to receive", "S"),
        profile(40, "customer-service.contract", "Service contract, subscription, warranty, or support agreement attached to an account", "Contract metadata changes SLA, escalation, refund, and remediation policy", "S"),
        profile(41, "customer-service.product-owned", "Products, devices, policies, services, or subscriptions held by the customer", "Most support intent is about a specific owned product or service", "S"),
        profile(42, "customer-service.customer-health", "Composite relationship health indicators built from usage, tickets, sentiment, and risk", "Helps teams intervene before dissatisfaction becomes churn", "A"),
        profile(43, "customer-service.churn-risk", "Risk state, drivers, confidence, and mitigation plan for possible customer loss", "Customer service often detects churn signals earlier than sales or success teams", "A"),
        profile(44, "customer-service.vulnerability-flag", "Sensitive-service flag for elderly, disabled, financially distressed, or otherwise vulnerable customers", "Some customers require protected handling, different scripts, or stronger review", "S"),
        profile(45, "customer-service.customer-note", "Structured internal note with author, visibility, expiry, and evidence links", "Notes are useful but dangerous unless scoped, auditable, and time-bounded", "A"),
        profile(46, "customer-service.relationship", "Links between customer, account, payer, beneficiary, administrator, and authorized representative", "Complex service contexts need relationship-aware authorization and explanation", "A"),
        profile(47, "customer-service.authorized-representative", "Third party allowed to act on behalf of a customer under defined conditions", "Common in finance, healthcare, telecom, insurance, and enterprise support", "A"),
        profile(48, "customer-service.do-not-contact", "Suppression state for channels, reasons, legal basis, and exception rules", "Prevents unwanted or unlawful contact while preserving necessary service notices", "S"),
        profile(49, "customer-service.language-profile", "Preferred language, fallback language, translation requirement, and interpreter need", "Language-aware service improves comprehension and reduces resolution errors", "A"),
        profile(50, "customer-service.accessibility-need", "Accessibility accommodations such as screen-reader-friendly text, captions, relay calls, or simplified language", "Inclusive service requires the need to be known and operationally respected", "A"),
        profile(51, "customer-service.customer-location", "Service-relevant geography such as country, region, store, delivery area, or regulatory jurisdiction", "Location changes policy, availability, tax, logistics, and compliance handling", "A"),
        profile(52, "customer-service.customer-value", "Service-relevant value band, revenue impact, strategic status, or retention priority", "Used carefully, value context helps allocate scarce expert attention", "B"),
        profile(53, "customer-service.lifecycle-stage", "Customer stage such as onboarding, active use, renewal, cancellation, winback, or post-incident", "The right response often depends on where the customer is in the relationship", "A"),
        profile(54, "customer-service.household", "Household or organization grouping multiple customer identities and shared entitlements", "Needed when support concerns shared services, family plans, or corporate accounts", "B"),
        profile(55, "customer-service.customer-portal-profile", "Customer-facing portal identity, permissions, saved forms, and visible history", "Self-service depends on a coherent portal representation", "A"),
        profile(56, "customer-service.impersonation-session", "Audited agent session viewing or acting as the customer with explicit scope", "Prevents abuse and improves traceability when agents reproduce customer issues", "S"),
        profile(57, "customer-service.privacy-requester", "Requester identity and authority for privacy, deletion, access, or correction requests", "Privacy workflows must prove who requested what and under which authority", "S"),
        profile(58, "customer-service.account-merge", "Proposed or completed merge of duplicate customer or account records with conflict resolution", "Duplicate identities fragment context and create service mistakes", "A"),
        profile(59, "customer-service.case", "Canonical service case aggregating tickets, interactions, tasks, evidence, and resolution", "A case-level object avoids losing context across channels and sub-tickets", "S"),
        profile(60, "customer-service.subcase", "Child case representing a separable workstream under a larger case", "Complex issues require parallel investigation without losing parent context", "A"),
        profile(61, "customer-service.incident-link", "Relationship between a customer case and a broader service incident or outage", "Prevents treating systemic incidents as isolated customer failures", "S"),
        profile(62, "customer-service.problem-record", "Root-cause work item collecting many related cases and suspected causes", "Turns repeated tickets into durable product or operations improvement", "S"),
        profile(63, "customer-service.service-request", "Structured customer request for an allowed service action, not necessarily a defect", "Separates requests from complaints, defects, incidents, and questions", "S"),
        profile(64, "customer-service.complaint", "Formal dissatisfaction record with regulatory, severity, acknowledgement, and response obligations", "Complaints often carry different legal and executive-handling requirements", "S"),
        profile(65, "customer-service.dispute", "Customer contesting a charge, decision, outcome, shipment, policy, or service action", "Disputes need evidence, deadlines, decision rationale, and appeal paths", "S"),
        profile(66, "customer-service.appeal", "Request to review a previous decision, denial, closure, or remediation outcome", "Appeal handling must preserve original rationale and review independence", "A"),
        profile(67, "customer-service.refund-request", "Request, eligibility analysis, approval path, amount, and payment status for a refund", "Refunds combine customer experience, policy, finance, and fraud concerns", "A"),
        profile(68, "customer-service.credit-adjustment", "Goodwill credit, billing adjustment, fee waiver, or compensation action", "Compensation decisions require limits, approvals, and auditability", "A"),
        profile(69, "customer-service.return-request", "Return merchandise authorization, eligibility, shipping, inspection, and refund status", "Retail and hardware support need an explicit lifecycle beyond the ticket", "A"),
        profile(70, "customer-service.replacement-order", "Replacement item, reason, warranty basis, logistics, and customer confirmation", "Replacement flows have inventory, fraud, and shipping dependencies", "A"),
        profile(71, "customer-service.field-service-order", "On-site visit, technician assignment, parts, appointment, and completion evidence", "Some support cannot be resolved remotely and needs field execution tracking", "A"),
        profile(72, "customer-service.repair-order", "Repair intake, diagnostics, estimate, approval, parts, labor, and return shipment", "Repair operations need a more detailed lifecycle than generic tickets", "A"),
        profile(73, "customer-service.callback-request", "Customer-requested or agent-scheduled callback with time window and ownership", "Callbacks reduce wait time but fail without precise ownership and reminders", "S"),
        profile(74, "customer-service.follow-up-task", "Internal action item after an interaction, with due date, owner, and dependency", "Many service failures are missed follow-ups rather than bad first responses", "S"),
        profile(75, "customer-service.customer-action-required", "Pending customer-provided information, approval, document, payment, or confirmation", "Clarifies why a case is waiting and prevents false SLA violations", "S"),
        profile(76, "customer-service.internal-action-required", "Pending internal dependency such as engineering input, finance approval, or supervisor review", "Distinguishes customer wait from internal blocking work", "S"),
        profile(77, "customer-service.case-state-transition", "State change event with actor, timestamp, reason, previous state, and next state", "State transitions are the audit spine of a service workflow", "S"),
        profile(78, "customer-service.reopen", "Reopened case event with reason, triggering evidence, and ownership decision", "Reopens expose weak resolutions and should feed quality improvement", "S"),
        profile(79, "customer-service.duplicate-case", "Confirmed duplicate relationship between cases with survivor, merged history, and customer-visible status", "Deduplication reduces noise but must preserve evidence and customer expectations", "A"),
        profile(80, "customer-service.related-case", "Non-duplicate relationship between cases that share a customer, issue, product, or incident", "Agents need related context without forcing destructive merges", "A"),
        profile(81, "customer-service.case-watch", "Watcher or subscriber list for case changes, including internal stakeholders", "High-impact cases need explicit visibility without changing ownership", "B"),
        profile(82, "customer-service.case-freeze", "Temporary hold preventing closure or sensitive actions until a condition is satisfied", "Useful for legal hold, fraud review, regulator review, or executive escalation", "A"),
        profile(83, "customer-service.case-priority-change", "Priority reclassification event with justification, source, and approval if required", "Priority changes are often contested and should be explainable", "A"),
        profile(84, "customer-service.case-severity", "Impact-based severity independent from customer-assigned urgency", "Severity improves triage by separating actual impact from perceived urgency", "S"),
        profile(85, "customer-service.case-urgency", "Time sensitivity, deadline, customer pressure, or external constraint", "Urgency and severity combine to drive priority but should remain distinct", "A"),
        profile(86, "customer-service.impact-assessment", "Affected users, revenue, safety, legal, operational, or reputational impact estimate", "Impact estimates make escalation and prioritization defensible", "S"),
        profile(87, "customer-service.resolution-code", "Structured code describing how the case was resolved", "Resolution codes power analytics, automation, and product improvement", "S"),
        profile(88, "customer-service.closure-reason", "Reason for case closure including resolved, duplicate, no response, out of scope, or withdrawn", "Closure is not always resolution; the distinction matters analytically", "S"),
        profile(89, "customer-service.no-response-policy", "Rules and events for closing cases after missing customer response windows", "Prevents arbitrary closure while preserving operational throughput", "A"),
        profile(90, "customer-service.sla-pause", "Explicit SLA pause interval with reason, scope, and policy basis", "SLA clocks need auditable pause semantics to avoid gaming and confusion", "S"),
        profile(91, "customer-service.sla-breach", "Breach event, breached target, root cause, customer impact, and remediation", "Breach records are necessary for accountability and contract reporting", "S"),
        profile(92, "customer-service.service-credit-claim", "Claim for contractual service credit following SLA breach or outage", "Service credits connect support evidence to commercial obligations", "A"),
        profile(93, "customer-service.case-retention-rule", "Retention, deletion, legal hold, and anonymization policy for service records", "Service records often contain sensitive data and need governed retention", "S"),
        profile(94, "customer-service.routing-rule", "Deterministic rule assigning cases by channel, skill, priority, segment, or jurisdiction", "Routing quality directly determines response time and resolution quality", "S"),
        profile(95, "customer-service.routing-decision", "Specific routing outcome with matched rule, alternatives, and override reason", "Auditable routing explains why a customer reached a given queue or agent", "S"),
        profile(96, "customer-service.skill", "Agent capability such as language, product, certification, seniority, or regulatory permission", "Skill-based routing depends on a typed skill inventory", "S"),
        profile(97, "customer-service.skill-proficiency", "Agent skill level, certification date, expiry, and evidence of proficiency", "Having a skill is not binary in serious support operations", "A"),
        profile(98, "customer-service.queue-priority-policy", "Policy determining ordering inside a queue", "Queues without visible priority policy become opaque and unfair", "A"),
        profile(99, "customer-service.queue-threshold", "Configured queue limits for backlog, wait time, abandonment, and overflow", "Thresholds trigger staffing, overflow, or incident-like responses", "A"),
        profile(100, "customer-service.overflow-routing", "Fallback route when queue thresholds or operating hours are exceeded", "Prevents silent service degradation during demand spikes", "A"),
        profile(101, "customer-service.operating-hours", "Service availability windows by channel, team, region, and holiday calendar", "Promised response depends on when the service is actually open", "S"),
        profile(102, "customer-service.holiday-calendar", "Non-working days and special schedules affecting SLA and staffing", "SLA and workforce calculations need an explicit calendar", "A"),
        profile(103, "customer-service.agent-shift", "Scheduled working interval, channel assignment, breaks, and capacity", "Shift data connects demand to real capacity", "A"),
        profile(104, "customer-service.agent-presence", "Real-time availability state such as available, busy, away, training, or offline", "Live routing depends on presence rather than static assignments", "A"),
        profile(105, "customer-service.workload", "Current assigned cases, active chats, complexity score, and capacity remaining", "Fair allocation requires knowing workload, not just availability", "S"),
        profile(106, "customer-service.workload-balance-policy", "Policy for distributing work across agents or teams", "Reduces burnout and prevents hidden cherry-picking or unfair queues", "A"),
        profile(107, "customer-service.supervisor", "Supervisor identity, scope, approval powers, and coaching responsibilities", "Escalation and quality workflows need accountable supervisors", "A"),
        profile(108, "customer-service.escalation-policy", "Rules defining when and how cases move to supervisors, specialists, legal, or engineering", "Escalation needs deterministic criteria, not ad hoc judgment alone", "S"),
        profile(109, "customer-service.escalation-decision", "Actual escalation event with trigger, owner, accepted team, and response commitment", "Captures whether escalation rules were followed and accepted", "S"),
        profile(110, "customer-service.swarming-session", "Multi-agent collaborative session to resolve a complex case", "Modern support often solves difficult cases through swarm collaboration", "A"),
        profile(111, "customer-service.warm-transfer", "Transfer where context is handed off before the customer moves channels or agents", "Warm transfer reduces repeated explanations and improves experience", "A"),
        profile(112, "customer-service.cold-transfer", "Transfer without live context handoff, with reason and risk flag", "Cold transfers are a known source of friction and should be measurable", "B"),
        profile(113, "customer-service.assignment", "Ownership assignment of a case, task, interaction, or approval", "Assignment is the basic unit of accountability", "S"),
        profile(114, "customer-service.assignment-override", "Manual override of automatic assignment with actor and justification", "Overrides are necessary but should be auditable", "A"),
        profile(115, "customer-service.backlog", "Accumulated unworked or aging work by queue, priority, team, and channel", "Backlog is the main operational pressure indicator", "S"),
        profile(116, "customer-service.capacity-plan", "Expected staffing, demand forecast, service levels, and risk assumptions", "Capacity planning ties service promises to realistic resources", "A"),
        profile(117, "customer-service.intraday-adjustment", "Same-day staffing or routing change responding to unexpected demand", "Service operations need a record of tactical adjustments", "B"),
        profile(118, "customer-service.training-assignment", "Assignment of training, certification, or knowledge modules to an agent", "Agent capability improves through explicit training loops", "A"),
        profile(119, "customer-service.coaching-session", "Supervisor coaching record linked to quality findings or performance goals", "Quality improvement requires a bridge from measurement to coaching", "A"),
        profile(120, "customer-service.agent-performance-goal", "Target for agent quality, efficiency, adherence, or development", "Goals shape behavior and must be explicit to avoid metric confusion", "B"),
        profile(121, "customer-service.occupancy", "Agent utilization metric across active work, after-call work, idle time, and breaks", "Occupancy helps balance efficiency against burnout and quality risk", "B"),
        profile(122, "customer-service.adherence", "Comparison of scheduled versus actual agent activity by interval", "Workforce adherence affects service level and fairness", "B"),
        profile(123, "customer-service.forecast-variance", "Difference between forecasted and actual demand, handle time, or staffing", "Variance analysis improves the next planning cycle", "A"),
        profile(124, "customer-service.conversation", "Threaded customer-agent exchange across one or more channels", "Conversation context is the human-readable surface of service", "S"),
        profile(125, "customer-service.omnichannel-thread", "Unified thread combining email, chat, voice transcript, app, SMS, and social messages", "Customers switch channels; the service record must preserve continuity", "S"),
        profile(126, "customer-service.voice-call", "Phone or VoIP call metadata, participants, duration, recording, and outcome", "Voice remains central in high-stakes service", "S"),
        profile(127, "customer-service.call-recording", "Audio recording reference with consent, retention, redaction, and access policy", "Recordings are evidence but create privacy and compliance obligations", "S"),
        profile(128, "customer-service.call-transcript", "Machine or human transcript with timestamps, speaker labels, and confidence", "Transcripts unlock search, QA, summarization, and evidence review", "S"),
        profile(129, "customer-service.chat-session", "Live chat session with start, end, wait time, bot handoff, and transcript", "Chat has real-time operational dynamics distinct from email", "S"),
        profile(130, "customer-service.email-thread", "Email conversation grouped by headers, participants, attachments, and response state", "Email needs threading semantics and reply ownership", "A"),
        profile(131, "customer-service.sms-thread", "SMS exchange with opt-in state, delivery status, and short-form constraints", "SMS is operationally useful but regulated and easy to misuse", "A"),
        profile(132, "customer-service.whatsapp-thread", "WhatsApp conversation with template rules, session window, and delivery receipts", "WhatsApp service has channel-specific constraints that affect workflow", "A"),
        profile(133, "customer-service.social-message", "Public or private social media message requiring service handling", "Social support carries public reputation risk and special escalation patterns", "A"),
        profile(134, "customer-service.app-message", "In-app message, notification, or support chat initiated from product context", "In-app context can include product state and deep links that reduce diagnosis time", "A"),
        profile(135, "customer-service.store-visit", "In-person interaction at a branch, store, kiosk, or service counter", "Physical service creates different evidence, wait, and handoff patterns", "A"),
        profile(136, "customer-service.message-delivery-status", "Sent, delivered, read, failed, bounced, or blocked status per outbound message", "Agents need to know whether a customer actually received a response", "A"),
        profile(137, "customer-service.message-redaction", "Redacted segment, reason, actor, original retention state, and audit reference", "Sensitive conversations need controlled visibility without deleting evidence", "S"),
        profile(138, "customer-service.translation", "Translated message, source language, target language, translator, confidence, and review state", "Translation changes meaning risk and must be traceable", "A"),
        profile(139, "customer-service.interpreter-session", "Live interpreter involvement for voice, video, or chat", "Interpreter use affects timing, consent, quality, and accessibility", "A"),
        profile(140, "customer-service.sentiment-signal", "Detected or manually tagged customer sentiment at message, interaction, or case level", "Sentiment can guide escalation but must be treated as a signal, not a fact", "A"),
        profile(141, "customer-service.emotion-signal", "Specific emotion indicator such as anger, confusion, fear, gratitude, or frustration", "Emotion labels help coaching and recovery when handled carefully", "B"),
        profile(142, "customer-service.intent-detection", "Detected customer intent with confidence, source text, and alternative intents", "Intent detection drives triage, automation, and knowledge suggestions", "S"),
        profile(143, "customer-service.entity-extraction", "Extracted order number, product, policy, location, person, date, or error code from conversation", "Structured extraction reduces manual search and improves downstream automation", "A"),
        profile(144, "customer-service.conversation-summary", "Human or AI summary of the interaction with provenance and confidence", "Summaries improve handoff but require traceability to source messages", "S"),
        profile(145, "customer-service.handoff-summary", "Specialized summary prepared for transfer, escalation, or shift change", "Handoff summaries reduce customer repetition and downstream errors", "S"),
        profile(146, "customer-service.after-call-work", "Post-interaction wrap-up activity, notes, codes, and time spent", "After-call work is part of true handle time and quality", "A"),
        profile(147, "customer-service.wrap-up-code", "Structured post-interaction classification selected by the agent", "Wrap-up codes are a major input to analytics and routing improvement", "A"),
        profile(148, "customer-service.disposition", "Final interaction outcome such as answered, abandoned, resolved, transferred, or callback scheduled", "Disposition separates interaction outcome from case resolution", "S"),
        profile(149, "customer-service.abandonment", "Customer left queue or channel before reaching service, with wait context", "Abandonment is a direct signal of capacity and experience failure", "S"),
        profile(150, "customer-service.hold-event", "Customer placed on hold with duration, reason, and return outcome", "Hold behavior affects experience and regulatory compliance in some domains", "B"),
        profile(151, "customer-service.silence-event", "Detected silence, long pause, or inactivity interval during conversation", "Silence may indicate friction, agent search, or customer disengagement", "C"),
        profile(152, "customer-service.screen-share-session", "Remote support session with consent, duration, permissions, and recording state", "Technical support often needs controlled co-browsing or screen share", "A"),
        profile(153, "customer-service.co-browse-session", "Agent-assisted browser session with masked fields and customer consent", "Co-browsing needs strict privacy controls and audit trails", "A"),
        profile(154, "customer-service.knowledge-article-version", "Versioned article content with author, approver, effective date, and rollback point", "Knowledge changes must be traceable because bad guidance creates bad service", "S"),
        profile(155, "customer-service.knowledge-gap", "Observed missing, stale, conflicting, or insufficient knowledge needed to resolve work", "Knowledge-base improvement should be driven by actual service failures", "S"),
        profile(156, "customer-service.article-feedback", "Agent or customer feedback on a knowledge article", "Article quality improves when feedback is captured where the article is used", "A"),
        profile(157, "customer-service.article-effectiveness", "Measured article deflection, reuse, resolution association, and quality outcomes", "Knowledge teams need evidence of which content actually helps", "A"),
        profile(158, "customer-service.search-query", "Customer or agent knowledge-search query with results, clicks, and outcome", "Search logs reveal vocabulary mismatch and missing content", "A"),
        profile(159, "customer-service.zero-result-search", "Search event with no useful result and contextual case or intent", "Zero-result searches are high-value knowledge backlog inputs", "S"),
        profile(160, "customer-service.content-approval", "Approval workflow for scripts, macros, articles, and customer-facing templates", "Customer-facing content needs review, ownership, and effective dates", "S"),
        profile(161, "customer-service.content-expiry", "Expiration, review deadline, owner, and renewal state for service content", "Expired guidance creates risk and should fail visibly", "S"),
        profile(162, "customer-service.script", "Guided agent script with conditional branches and required disclosures", "Scripts support consistency in regulated or high-volume workflows", "A"),
        profile(163, "customer-service.script-step", "Individual script instruction, question, disclosure, or decision point", "Script steps allow granular analytics and compliance validation", "A"),
        profile(164, "customer-service.decision-tree", "Structured troubleshooting or eligibility tree with branches and terminal outcomes", "Decision trees make repeatable service logic auditable", "S"),
        profile(165, "customer-service.troubleshooting-step", "Atomic diagnostic or resolution action with expected result and next branch", "Troubleshooting becomes reusable and measurable when steps are typed", "S"),
        profile(166, "customer-service.bot-flow", "Chatbot or voicebot flow with intents, prompts, transitions, and fallback paths", "Automation must be managed as a governed service artifact", "S"),
        profile(167, "customer-service.bot-handoff", "Transition from automation to human support with reason and context package", "Handoff quality determines whether automation helps or harms", "S"),
        profile(168, "customer-service.fallback-intent", "Unrecognized or low-confidence automation intent routed for review", "Fallbacks are where automation improvement work begins", "A"),
        profile(169, "customer-service.deflection-event", "Customer avoided human contact through self-service, automation, or knowledge content", "Deflection should be measured with evidence rather than assumed", "A"),
        profile(170, "customer-service.self-service-session", "Customer journey through help center, bot, portal, or guided workflow before contact", "Pre-contact behavior explains context and frustration", "S"),
        profile(171, "customer-service.portal-form", "Structured customer-submitted form with validation, attachments, and routing metadata", "Forms provide cleaner input and drive deterministic routing", "A"),
        profile(172, "customer-service.guided-intake", "Step-by-step intake flow that captures issue-specific facts before case creation", "Better intake reduces rework and first-response delays", "S"),
        profile(173, "customer-service.dynamic-form-field", "Conditional form field shown based on product, issue, region, or customer type", "Dynamic forms keep intake focused while preserving structure", "A"),
        profile(174, "customer-service.macro-usage", "Application of a macro by agent, context, edits, and outcome", "Macro usage reveals productivity, misuse, and template improvement opportunities", "A"),
        profile(175, "customer-service.macro-variant", "Localized, segmented, or policy-specific variant of a reusable macro", "Macros need variants without copy-paste drift", "A"),
        profile(176, "customer-service.response-personalization", "Controlled personalization variables, allowed transformations, and preview state", "Personalization improves tone but needs guardrails", "B"),
        profile(177, "customer-service.tone-policy", "Brand and compliance rules for empathy, apology, certainty, and escalation language", "Tone is operationally important and should be enforceable", "A"),
        profile(178, "customer-service.disclosure-requirement", "Required legal, safety, privacy, or policy disclosure triggered by context", "Missing required disclosures creates compliance and customer-trust risk", "S"),
        profile(179, "customer-service.prohibited-language", "Words, claims, promises, or phrases that agents and bots must avoid", "Prevents risky guarantees, blame language, or regulated misstatements", "A"),
        profile(180, "customer-service.next-best-action", "Recommended next step for an agent or automation with rationale and confidence", "Recommendations need explicit provenance to be trusted and audited", "A"),
        profile(181, "customer-service.automation-rule", "Rule that creates, routes, updates, tags, or closes service work", "Automation should be documented as operational logic, not hidden configuration", "S"),
        profile(182, "customer-service.automation-run", "Execution instance of an automation rule with inputs, outputs, and errors", "Debugging automation requires run-level observability", "S"),
        profile(183, "customer-service.automation-exception", "Automation failure, skipped action, blocked condition, or human-review requirement", "Exceptions are where service quality silently degrades", "S"),
        profile(184, "customer-service.ai-draft-response", "AI-generated draft response with source citations, confidence, and agent edits", "AI assistance should be traceable to evidence and human approval", "S"),
        profile(185, "customer-service.ai-summary-review", "Human review outcome for an AI-generated conversation or case summary", "Summaries can distort facts; review state should be explicit", "A"),
        profile(186, "customer-service.ai-suggestion-feedback", "Agent feedback on an AI suggestion, including accepted, edited, rejected, and reason", "Feedback loops improve models and reveal unsafe suggestions", "A"),
        profile(187, "customer-service.prompt-template", "Versioned prompt used for service summarization, classification, drafting, or triage", "Prompt behavior is part of the service system and needs version control", "A"),
        profile(188, "customer-service.prompt-evaluation", "Evaluation dataset and scores for a service prompt or automation model", "AI changes should be evaluated before being trusted in production", "S"),
        profile(189, "customer-service.quality-review", "Structured review of an interaction or case against a quality rubric", "Quality programs need consistent scoring and evidence", "S"),
        profile(190, "customer-service.quality-rubric", "Criteria, weights, scoring scale, and failure conditions for service quality", "Rubrics prevent subjective and inconsistent QA decisions", "S"),
        profile(191, "customer-service.quality-score", "Result of a review with criterion-level scores and evidence references", "Score details are needed for coaching and dispute resolution", "S"),
        profile(192, "customer-service.critical-error", "Severe quality failure such as privacy breach, wrong advice, abuse, or compliance miss", "Critical errors require immediate escalation and root-cause action", "S"),
        profile(193, "customer-service.qa-sampling-plan", "Rules for selecting interactions or cases for quality review", "Sampling affects fairness and representativeness of QA", "A"),
        profile(194, "customer-service.calibration-session", "Reviewer calibration meeting comparing scores and resolving interpretation drift", "QA accuracy requires reviewer alignment over time", "A"),
        profile(195, "customer-service.agent-dispute-qa", "Agent challenge to a QA finding with evidence and final decision", "Fair quality programs need appeal paths", "A"),
        profile(196, "customer-service.compliance-review", "Review against legal, regulatory, policy, or contractual requirements", "Compliance review is distinct from general service quality", "S"),
        profile(197, "customer-service.policy-exception", "Approved deviation from normal policy with owner, rationale, expiry, and scope", "Exceptions happen; unmanaged exceptions become hidden policy", "S"),
        profile(198, "customer-service.risk-acceptance", "Explicit acceptance of residual service risk by an authorized owner", "High-risk deviations need accountable sign-off", "A"),
        profile(199, "customer-service.customer-harm", "Actual or potential harm caused by service action, omission, delay, or misinformation", "Harm tracking turns service defects into accountable remediation", "S"),
        profile(200, "customer-service.safety-issue", "Safety-sensitive report requiring special triage, response, or regulator workflow", "Safety issues cannot be handled as ordinary complaints", "S"),
        profile(201, "customer-service.abuse-report", "Report of abuse, harassment, threat, fraud, or platform misuse", "Abuse workflows require evidence, urgency, and protected handling", "A"),
        profile(202, "customer-service.fraud-signal", "Suspicious behavior, pattern, or case attribute suggesting fraud or account takeover", "Support is a common attack surface and needs risk-aware handling", "S"),
        profile(203, "customer-service.fraud-review", "Manual or automated review of suspected fraud with decision and rationale", "Fraud decisions affect customers and must be explainable", "A"),
        profile(204, "customer-service.chargeback-support", "Support evidence package for payment chargeback response", "Service records often decide whether chargebacks can be defended", "B"),
        profile(205, "customer-service.legal-hold", "Preservation requirement preventing deletion or modification of service evidence", "Legal holds override normal retention policies", "S"),
        profile(206, "customer-service.evidence-item", "File, message, log, recording, screenshot, or external reference used as evidence", "Strong service decisions require evidence, not just notes", "S"),
        profile(207, "customer-service.chain-of-custody", "Custody history for evidence access, transfer, export, or redaction", "High-stakes complaints, disputes, and legal cases need evidence integrity", "A"),
        profile(208, "customer-service.redaction-policy", "Rules for masking PII, payment data, secrets, health data, or privileged content", "Service data is sensitive and must be shareable safely", "S"),
        profile(209, "customer-service.data-access-audit", "Record of who accessed service records, why, and under what role", "Access accountability is essential for privacy and trust", "S"),
        profile(210, "customer-service.role-permission", "Permission model for viewing, editing, exporting, or approving service artifacts", "Sensitive workflows need fine-grained access control", "A"),
        profile(211, "customer-service.approval-request", "Request for supervisor, compliance, finance, legal, or product approval", "Approvals are common bottlenecks and must be traceable", "S"),
        profile(212, "customer-service.approval-decision", "Approval outcome with approver, constraints, expiration, and evidence", "Decision-level audit is required when approvals change customer outcomes", "S"),
        profile(213, "customer-service.audit-finding", "Internal or external audit finding linked to service controls and remediation tasks", "Audits should connect directly to operational artifacts", "A"),
        profile(214, "customer-service.corrective-action", "Action created to correct quality, compliance, or process failures", "Findings without corrective actions do not improve the system", "S"),
        profile(215, "customer-service.preventive-action", "Action intended to prevent recurrence of a known or plausible failure mode", "Prevention distinguishes mature operations from reactive firefighting", "A"),
        profile(216, "customer-service.root-cause-analysis", "Structured cause analysis using 5 Whys, fishbone, timeline, or fault tree", "Repeated service failures need cause structure, not just blame", "S"),
        profile(217, "customer-service.fmea", "Failure mode and effects analysis for service processes or automations", "FMEA anticipates service failure before customers experience it", "A"),
        profile(218, "customer-service.control-test", "Test of a service control such as disclosure, approval, retention, or access rule", "Controls should be testable, not merely documented", "A"),
        profile(219, "customer-service.regulatory-deadline", "Deadline imposed by law, regulator, ombudsman, contract, or dispute scheme", "Regulatory deadlines must override ordinary queue behavior", "S"),
        profile(220, "customer-service.regulator-response", "Formal response package to regulator, ombudsman, or external authority", "External responses require evidence, approvals, and version control", "A"),
        profile(221, "customer-service.customer-data-request", "Access, deletion, correction, portability, restriction, or objection request", "Privacy requests are customer service workflows with legal deadlines", "S"),
        profile(222, "customer-service.data-deletion-proof", "Evidence that requested service data was deleted, anonymized, or retained under exception", "Privacy work needs proof of completion, not just status", "A"),
        profile(223, "customer-service.ethics-review", "Review of service policy, automation, or AI impact on fairness, vulnerability, or harm", "AI and policy changes can create subtle service harms", "B"),
        profile(224, "customer-service.metric-definition", "Formal definition of a service metric, formula, denominator, exclusions, and owner", "Metric drift creates false alignment; definitions must be explicit", "S"),
        profile(225, "customer-service.service-level", "Measured percentage of work handled within target by interval, queue, and channel", "Service level is the canonical capacity-performance metric", "S"),
        profile(226, "customer-service.first-response-time", "Time from customer contact to first meaningful human or automated response", "First response strongly shapes perceived service quality", "S"),
        profile(227, "customer-service.first-contact-resolution", "Indicator that the customer need was resolved without follow-up or repeat contact", "FCR connects efficiency to customer experience", "S"),
        profile(228, "customer-service.average-handle-time", "Total handling time including talk, chat, hold, and after-call work", "AHT is useful but must be interpreted alongside quality", "A"),
        profile(229, "customer-service.customer-effort-score", "Post-service effort measure with survey question, scale, and context", "Effort is often a stronger service-improvement signal than satisfaction alone", "A"),
        profile(230, "customer-service.csat", "Customer satisfaction survey response with scale, timing, channel, and verbatim text", "CSAT is one of the most common customer service signals", "S"),
        profile(231, "customer-service.nps-response", "Promoter score response linked to account, interaction, journey, or relationship context", "NPS needs context to be actionable in service operations", "A"),
        profile(232, "customer-service.survey-invitation", "Survey send event, eligibility, sampling rule, and delivery outcome", "Survey bias starts with who was invited", "A"),
        profile(233, "customer-service.survey-response", "Structured survey answer set with metadata and consent constraints", "Raw responses power more than one metric", "A"),
        profile(234, "customer-service.verbatim-analysis", "Categorization of free-text feedback into themes, sentiment, and drivers", "Text feedback contains root causes that numeric scores hide", "A"),
        profile(235, "customer-service.voice-of-customer-theme", "Recurring customer pain point, request, complaint, or praise theme", "Themes turn unstructured service feedback into product and process input", "S"),
        profile(236, "customer-service.theme-evidence", "Specific messages, calls, tickets, or survey verbatims supporting a theme", "Themes should remain grounded in customer evidence", "S"),
        profile(237, "customer-service.product-feedback", "Customer-originated product issue, request, confusion, or improvement idea", "Support is one of the richest sources of product feedback", "S"),
        profile(238, "customer-service.feature-request", "Customer request for a new or changed product capability", "Feature requests need frequency, value, evidence, and affected segments", "A"),
        profile(239, "customer-service.bug-report", "Customer-reported defect with reproduction context, logs, severity, and product link", "Bug reports from support need structure to be actionable by engineering", "S"),
        profile(240, "customer-service.known-issue", "Confirmed recurring issue with workaround, status, affected versions, and customer messaging", "Known issues reduce repeated investigation and inconsistent responses", "S"),
        profile(241, "customer-service.workaround", "Temporary mitigation offered before final product or operational fix", "Workarounds should be tracked because they can become hidden permanent policy", "A"),
        profile(242, "customer-service.demand-driver", "Underlying reason causing contact volume, such as outage, billing confusion, UI change, or policy change", "Reducing demand requires understanding why customers contact support", "S"),
        profile(243, "customer-service.contact-volume", "Inbound demand count by interval, channel, intent, segment, and queue", "Volume is the baseline for staffing and trend analysis", "S"),
        profile(244, "customer-service.repeat-contact", "Customer contact repeated within a defined window for the same or related reason", "Repeat contact is a strong signal of unresolved needs", "S"),
        profile(245, "customer-service.recontact-window", "Definition of the time window and matching logic for repeat-contact metrics", "Repeat-contact metrics are meaningless without an explicit window and match rule", "A"),
        profile(246, "customer-service.cost-to-serve", "Estimated service cost by customer, account, product, channel, or issue type", "Cost context helps prioritize automation and product fixes", "A"),
        profile(247, "customer-service.revenue-at-risk", "Revenue associated with unresolved, escalated, or churn-risk service issues", "Executive prioritization often depends on commercial exposure", "B"),
        profile(248, "customer-service.sla-dashboard", "Aggregated view of SLA attainment, breaches, pauses, and upcoming risks", "SLA reporting needs consistent inputs and explanations", "A"),
        profile(249, "customer-service.quality-dashboard", "Aggregated QA scores, critical errors, calibration drift, and coaching follow-through", "Quality programs need visibility beyond individual reviews", "A"),
        profile(250, "customer-service.operations-review", "Recurring performance review artifact combining metrics, themes, risks, and actions", "Operations improve through cadence and explicit action tracking", "A"),
        profile(251, "customer-service.executive-brief", "Short leadership-facing summary of service health, risks, wins, and decisions needed", "Executives need synthesized service intelligence, not raw dashboards", "A"),
        profile(252, "customer-service.anomaly-detection", "Detected unusual spike, drop, pattern, or outlier in service data", "Anomalies enable faster response to incidents and process failures", "A"),
        profile(253, "customer-service.cohort-analysis", "Service outcomes compared by product, segment, region, lifecycle stage, or acquisition cohort", "Cohorts reveal where service quality differs systematically", "B"),
        profile(254, "customer-service.crm-link", "Reference to CRM account, contact, opportunity, renewal, or success plan", "Support context improves when connected to commercial relationship data", "A"),
        profile(255, "customer-service.order-link", "Reference to order, shipment, invoice, payment, return, or fulfillment object", "Many service issues depend on transactional state", "S"),
        profile(256, "customer-service.billing-link", "Reference to billing account, invoice, charge, credit, tax, or payment method", "Billing service requires precise financial context", "S"),
        profile(257, "customer-service.subscription-link", "Reference to subscription, plan, renewal, cancellation, or entitlement state", "Subscription state determines eligibility and customer expectations", "A"),
        profile(258, "customer-service.product-telemetry-link", "Link from a case to product logs, events, sessions, or error traces", "Telemetry grounds troubleshooting in evidence rather than customer memory alone", "S"),
        profile(259, "customer-service.session-replay-link", "Reference to product session replay with privacy controls and consent state", "Session replay can resolve UI issues quickly but creates privacy risk", "A"),
        profile(260, "customer-service.error-log-link", "Application, device, API, or infrastructure log reference attached to a support case", "Logs convert vague reports into diagnosable evidence", "S"),
        profile(261, "customer-service.engineering-ticket-link", "Link from service case to engineering issue, bug, incident, or backlog item", "Support-to-engineering handoff is a common failure point", "S"),
        profile(262, "customer-service.release-link", "Product release, deployment, migration, or config change related to service demand", "Release context explains sudden contact spikes and regressions", "A"),
        profile(263, "customer-service.status-page-link", "Public or internal status-page incident associated with customer cases", "Status pages coordinate customer messaging and incident linkage", "A"),
        profile(264, "customer-service.inventory-link", "Reference to stock, part, device, replacement unit, or warehouse state", "Hardware and retail support need inventory-aware resolution", "A"),
        profile(265, "customer-service.shipping-link", "Carrier, tracking, delivery exception, address validation, and delivery proof reference", "Shipping issues require external state and evidence", "A"),
        profile(266, "customer-service.payment-provider-link", "Reference to payment processor event, authorization, dispute, or settlement", "Payment disputes require provider evidence and timelines", "B"),
        profile(267, "customer-service.identity-provider-link", "Reference to SSO, IAM, password reset, MFA, or account access event", "Access support depends on identity-system evidence", "A"),
        profile(268, "customer-service.device-diagnostic-link", "Reference to device health report, firmware, serial number, or diagnostic bundle", "Device support needs machine evidence tied to the customer case", "A"),
        profile(269, "customer-service.iottwin-link", "Reference to IoT device twin, state shadow, commands, and telemetry", "Connected-device support requires current and historical device state", "B"),
        profile(270, "customer-service.third-party-vendor-case", "Case opened with vendor, partner, carrier, supplier, or outsourced provider", "Customer support often depends on external parties and their SLAs", "A"),
        profile(271, "customer-service.partner-handoff", "Structured transfer to partner or outsourced team with context and obligations", "External handoff needs stronger context packaging and accountability", "A"),
        profile(272, "customer-service.outsourcer-performance", "Performance, quality, SLA, and compliance metrics for BPO or partner teams", "Outsourced service needs visibility equivalent to internal teams", "B"),
        profile(273, "customer-service.webhook-event", "External event ingested into the service workspace with signature and replay metadata", "Event-driven support needs reliable integration records", "A"),
        profile(274, "customer-service.api-call-log", "Service-platform API call record relevant to automation, sync, or customer action", "Integration debugging needs request-level traceability", "B"),
        profile(275, "customer-service.sync-error", "Failed synchronization with CRM, billing, order, identity, or knowledge systems", "Sync failures create incorrect context and bad customer outcomes", "S"),
        profile(276, "customer-service.integration-mapping", "Field mapping between service objects and external systems", "Mappings are operational contracts and drift over time", "A"),
        profile(277, "customer-service.master-data-conflict", "Conflict between systems of record for customer, account, entitlement, or product data", "Data conflicts are a frequent cause of wrong service decisions", "A"),
        profile(278, "customer-service.system-of-record", "Declared authoritative source for a field, object, or decision", "Service agents need to know which data wins when systems disagree", "A"),
        profile(279, "customer-service.webhook-retry-policy", "Retry, backoff, idempotency, dead-letter, and replay rules for service integrations", "Integration reliability depends on explicit retry semantics", "B"),
        profile(280, "customer-service.data-export", "Export package of service records for customer, regulator, legal, audit, or analytics use", "Exports need scoping, redaction, approval, and traceability", "A"),
        profile(281, "customer-service.data-import", "Imported service history, tickets, contacts, or knowledge from another platform", "Migration and consolidation require provenance for imported records", "A"),
        profile(282, "customer-service.sandbox-case", "Synthetic or test case used for training, QA, automation, or integration testing", "Test data prevents production records from being abused for experiments", "A"),
        profile(283, "customer-service.environment", "Service-platform environment such as production, staging, sandbox, or training", "Automation and tests must not confuse environments", "B"),
      ],
    },
  ],

  numberingReconciliation: {
    note:
      "Display numbers continue from the 33-entry Atendimento / Customer Service sample (#1-#33), starting at #34 and ending at #283. The 33 baseline entries are not part of this file. Total rows in this document: 250.",
    displayedNumberMin: 34,
    displayedNumberMax: 283,
    actualEntryCount: 250,
    sectionCounts: [
      {
        sectionTitle: "Domain profiles — Customer Service / Support Operations",
        count: 250,
      },
    ],
  },
};

/**
 * Validate against the schema. Expected: success — the source markdown's
 * audit table matches the actual rows (250 entries, S=105 / A=123 / B=21
 * / C=1) and there are no cross-references that could dangle.
 */
export const customerService250Validation = FdpmPluginIdeasRegistrySchema.safeParse(
  customerService250Registry,
);
