/**
 * Schema instance for docs/drafts/fdpm-250-plugins.md (250-entry baseline).
 *
 * This file mirrors the section rows in the source markdown verbatim. It
 * does NOT mirror the document's self-reported audit numbers (65/35/50/...)
 * which disagree with the actual rows. The schema's superRefine will flag
 * those discrepancies — that is the correct behavior. PALS's Law: the
 * document is unverified LLM output; the validator is the verifier.
 *
 * Scope decision: this instance covers entries 1-267 (the original "250"
 * baseline whose section headers run 1-9). The +50 expansion (section 10,
 * entries 268-317) is a later layer that adds a tenth section and was not
 * included in the document's audit table or tier distribution. Mapping it
 * would require the upstream document to either (a) restate the audit and
 * tier distribution to cover 300 entries, or (b) be split into two
 * registry documents. Until that decision is made upstream, mapping the
 * +50 here would manufacture facts the source document does not assert.
 */

import {
  FdpmPluginIdeasRegistrySchema,
  type FdpmPluginIdeasRegistry,
} from "./plugins.js";

/**
 * Construct without parsing first, so a reader can run
 * FdpmPluginIdeasRegistrySchema.safeParse(fdpm250Registry)
 * and see exactly which invariants the markdown violates.
 */
export const fdpm250Registry: FdpmPluginIdeasRegistry = {
  schemaVersion: "1.0.0",

  frontmatter: {
    title: "FDPM plugin ideas — 250 entries",
    status: "brainstorm",
    disclaimer:
      "No information in this document should be taken for granted. Statements about FDPM internals — capability kinds, primitive names (fs:*, sw:*, plan:*, cap:*), the contents of PURPOSE.md, and existing plugin behavior — are reproduced from the prior conversation only. I do not have direct access to the codebase, the schemas, or PURPOSE.md. Any claim not backed by an explicit definition, a verifiable reference, or evidence in this workspace may be invalid, erroneous, or a hallucination. The \"tier\" ratings are subjective calibration aids, not verdicts; they exist to separate \"I would defend this in review\" from \"I'm here to fill the count.\" Cross-references between entries (e.g., #27, #46) preserve the original numbering for the first 50 entries; numbers 51–250 are new.",
    provenance: {
      sourceRequest: "expand to 250",
      baseline: "50-entry list provided by the user in the same turn",
      capabilityKindsReferenced: {
        count: 11,
        kinds: [
          "cap:profile",
          "cap:renderer",
          "cap:validator",
          "cap:transformer",
          "cap:importer",
          "cap:exporter",
          "cap:expr-helper",
          "cap:lifecycle-hook",
          "cap:template",
          "cap:asset",
          "verb",
        ],
        note: 'Markdown frontmatter says "11 capability kinds ... plus verb/prompt surfaces attributed to PURPOSE.md by the user, not independently verified". Listing 10 cap:* + verb to honor the count of 11; prompt surface is acknowledged in the document but not counted toward the 11.',
      },
    },
  },

  heading: "FDPM plugin ideas — 250 entries",

  honestPreamble: {
    body:
      "The original 50 were curated against a real bar: each entry had to ship at least one of the 11 capability kinds and have a reason to exist beyond \"another domain profile.\" The \"deliberately left off\" section made that bar explicit (no generic LLM wrappers, no interchangeable niche markup renderers, no domain profiles without grounding evidence). Pushing from 50 to 250 inevitably crosses that bar. To stay calibrated, I applied a tier rating to every entry — including the original 50 — and I made the cliff visible rather than hiding it.",
    tierDefinitions: [
      {
        tier: "S",
        meaning:
          "solid case for existence; capability differentiator clear; a real workflow demands it; defensible on first contact.",
      },
      {
        tier: "A",
        meaning:
          "strong; would defend in review; some risk of overlap with adjacent plugins or entrenched external tooling.",
      },
      {
        tier: "B",
        meaning:
          "plausible, but the FDPM-specific value-add is thin or domain demand is uncertain. Could be folded into a sibling plugin or skipped without loss.",
      },
      {
        tier: "C",
        meaning:
          "included to hit 250. The case is weak — usually a generic LLM wrapper, a niche markup that's interchangeable with stronger renderers already on the list, or a domain profile lacking grounding evidence. I'd cut these in a real spec.",
      },
    ],
    /**
     * The markdown declares 250 entries with S=49, A=142, B=41, C=18.
     * Counting the actual rows yields 267 entries with S=63, A=150,
     * B=38, C=16. The schema validator will flag this; that is correct.
     * We mirror the document's claim here so the diff is visible.
     */
    tierDistribution: {
      totalEntries: 250,
      rows: [
        { tier: "S", count: 49 },
        { tier: "A", count: 142 },
        { tier: "B", count: 41 },
        { tier: "C", count: 18 },
      ],
    },
    backlogRecommendation: {
      keepLiveTiers: ["S", "A"],
      parkingLotTiers: ["B"],
      calibrationOnlyTiers: ["C"],
      rationale:
        "keep S+A (191 entries) as the live list; B (41 entries) as a parking lot pending demand; C (18 entries) as the acknowledged \"this is what 250 costs you\" set, useful only for showing where the curve breaks.",
    },
    notes: [
      "Two new sections were added that the original 50 had no entries for: cap:template (10 entries) and cap:asset (5 entries). The 11-capability list mentions both but the original 50 reached zero for each. These are fill, but the gap was real.",
      "The \"deliberately left off\" categories from the original — generic LLM wrappers, interchangeable niche markup renderers, profiles unrooted in evidence — are honored. Near-misses (Org-mode, AsciiDoc, DocBook, TEI, Day One) were added as low-tier entries rather than as exclusions. Fitness training and tabletop RPG campaigns remain excluded as in the original.",
    ],
  },

  sections: [
    {
      title: "Domain profiles",
      primaryCapabilityKinds: ["cap:profile"],
      description:
        "Section header in source markdown declares 65 entries; rows actually present number 80. Validator will flag.",
      entries: [
        {
          displayNumber: 1,
          id: "fdpm.threat-modeling",
          what: "STRIDE/DREAD primitives, attack-tree relations, mitigation traceability",
          why: "Maps cleanly to sw:Risk + sw:Mitigates patterns; a real workflow most security teams already do informally",
          tier: "S",
          capabilityKinds: ["cap:profile"],
          crossReferences: [],
          notes: [],
        },
        {
          displayNumber: 2,
          id: "fdpm.api-contracts",
          what: "OpenAPI-derived Endpoint/Schema/Contract with consumer-driven contract tests",
          why: "OpenAPI is the lingua franca; round-trip with #26/#27 makes specs editable as workbooks",
          tier: "S",
          capabilityKinds: ["cap:profile"],
          crossReferences: ["fdpm.openapi-import", "fdpm.openapi-export"],
          notes: [],
        },
        {
          displayNumber: 3,
          id: "fdpm.data-lineage",
          what: "Datasets, transformations, downstream consumers, freshness invariants",
          why: "fs:Phase-style I/O typing fits ETL graphs; lineage queries become structural",
          tier: "S",
          capabilityKinds: ["cap:profile"],
          crossReferences: [],
          notes: [],
        },
        {
          displayNumber: 4,
          id: "fdpm.runbooks",
          what: "Incident runbooks: triggers, decision trees, escalation paths, post-mortems",
          why: "Each step is a Phase; failure modes already model branching; renders to operator-facing markdown",
          tier: "S",
          capabilityKinds: ["cap:profile"],
          crossReferences: [],
          notes: [],
        },
        {
          displayNumber: 5,
          id: "fdpm.compliance-controls",
          what: "SOC2 / ISO 27001 / GDPR controls + evidence + audit trails",
          why: "Evidence already first-class via sw:Evidence/fs:Citation; controls map to Invariant",
          tier: "S",
          capabilityKinds: ["cap:profile"],
          crossReferences: [],
          notes: [],
        },
        {
          displayNumber: 6,
          id: "fdpm.legal-clauses",
          what: "Contract clauses, parties, obligations, termination triggers",
          why: "Clauses are typed primitives; cross-references make obligation mapping queryable",
          tier: "A",
          capabilityKinds: ["cap:profile"],
          crossReferences: [],
          notes: [],
        },
        {
          displayNumber: 7,
          id: "fdpm.research-papers",
          what: "Sections, claims, evidence, citations, contested points",
          why: "Already 70% there in formal-specification; specialises with peer-review primitives (Reviewer, Critique, Rebuttal)",
          tier: "S",
          capabilityKinds: ["cap:profile"],
          crossReferences: [],
          notes: [],
        },
        {
          displayNumber: 8,
          id: "fdpm.product-discovery",
          what: "Hypotheses, experiments, learnings, killed/iterated branches",
          why: "fs:Assumption.status enum already does ledger semantics; product teams need the same vocabulary",
          tier: "A",
          capabilityKinds: ["cap:profile"],
          crossReferences: [],
          notes: [],
        },
        {
          displayNumber: 9,
          id: "fdpm.user-research",
          what: "Interviews, themes, codes, evidence-quote primitives, theme saturation",
          why: "Qualitative coding maps to typed-relation graphs; saturation becomes a CEL rule",
          tier: "A",
          capabilityKinds: ["cap:profile"],
          crossReferences: [],
          notes: [],
        },
        {
          displayNumber: 10,
          id: "fdpm.curriculum-design",
          what: "Learning objectives, prerequisites, assessments, mastery edges",
          why: "Phase ordering = course sequencing; AC primitives for assessments",
          tier: "A",
          capabilityKinds: ["cap:profile"],
          crossReferences: [],
          notes: [],
        },
        {
          displayNumber: 11,
          id: "fdpm.recipe-cookbook",
          what: "Ingredients, steps, nutritional totals, allergen invariants, substitution graphs",
          why: "Concrete worked example for non-software domains; substitution = relation",
          tier: "A",
          capabilityKinds: ["cap:profile"],
          crossReferences: [],
          notes: [],
        },
        {
          displayNumber: 12,
          id: "fdpm.gardening-plot",
          what: "Plants, plant guilds, sun/water requirements, succession planting",
          why: "Real-world fs:Phase-as-season; companion-plant constraints as CEL rules",
          tier: "B",
          capabilityKinds: ["cap:profile"],
          crossReferences: [],
          notes: [],
        },
        {
          displayNumber: 13,
          id: "fdpm.music-theory",
          what: "Chord progressions, voice leading, modulations, formal structure",
          why: "Composition has typed sequencing; voice-leading rules are pure CEL predicates",
          tier: "B",
          capabilityKinds: ["cap:profile"],
          crossReferences: [],
          notes: [],
        },
        {
          displayNumber: 14,
          id: "fdpm.medical-protocols",
          what: "Diagnostic decision trees, treatment phases, contraindications, dosage invariants",
          why: "Same shape as runbooks but with stronger required-field gates and provenance",
          tier: "S",
          capabilityKinds: ["cap:profile"],
          crossReferences: [],
          notes: [],
        },
        {
          displayNumber: 15,
          id: "fdpm.architecture-decisions",
          what: "Pure ADR profile (Markdown ADR ↔ workbook round-trip)",
          why: "Lighter than software-architecture; many teams want just ADRs",
          tier: "A",
          capabilityKinds: ["cap:profile"],
          crossReferences: [],
          notes: [],
        },
        {
          displayNumber: 51,
          id: "fdpm.ml-experiments",
          what: "Training runs, datasets, hyperparameters, metrics, checkpoints, lineage",
          why: "Reproducibility + provenance are first-class FDPM strengths; bridges directly to #52",
          tier: "S",
          capabilityKinds: ["cap:profile"],
          crossReferences: ["fdpm.ml-evals"],
          notes: [],
        },
        {
          displayNumber: 52,
          id: "fdpm.ml-evals",
          what: "Eval suites, prompts, model versions, scored results, regressions, sample audits",
          why: "Eval as a controlled artefact with chain-of-evidence is exactly what FDPM is good at",
          tier: "S",
          capabilityKinds: ["cap:profile"],
          crossReferences: [],
          notes: [],
        },
        {
          displayNumber: 53,
          id: "fdpm.ml-model-cards",
          what: "Model card primitives: intended use, training data, limitations, fairness evals",
          why: "Model cards are structurally a workbook; the schema already exists in literature",
          tier: "A",
          capabilityKinds: ["cap:profile"],
          crossReferences: [],
          notes: [],
        },
        {
          displayNumber: 54,
          id: "fdpm.data-products",
          what: "Data products with owners, contracts, SLAs, downstream consumers",
          why: "Data-mesh vocabulary is essentially typed relations; complements #3",
          tier: "A",
          capabilityKinds: ["cap:profile"],
          crossReferences: ["fdpm.data-lineage"],
          notes: [],
        },
        {
          displayNumber: 55,
          id: "fdpm.security-incident-response",
          what: "Incidents, indicators, timeline events, decisions, blast radius, post-incident actions",
          why: "Distinct from runbooks (#4): incidents are individual histories with chain-of-custody-like evidence",
          tier: "S",
          capabilityKinds: ["cap:profile"],
          crossReferences: ["fdpm.runbooks"],
          notes: [],
        },
        {
          displayNumber: 56,
          id: "fdpm.cve-triage",
          what: "CVE entries, affected components, exploit context, remediation status",
          why: "Ties CVE feeds (#158) to actual asset graph; status tracking is the workflow",
          tier: "A",
          capabilityKinds: ["cap:profile"],
          crossReferences: ["fdpm.cve-feed-import"],
          notes: [
            "Markdown cross-reference #158 is unstable: in the source, ID 158 is fdpm.roam-json-import. The CVE-feed importer is actually #174 (fdpm.cve-feed-import). Mirroring the textual #158 here would create a dangling reference, so the cross-reference points at the semantically intended target.",
          ],
        },
        {
          displayNumber: 57,
          id: "fdpm.pen-test-report",
          what: "Findings, severity, evidence, reproduction steps, retest status",
          why: "Each finding has structured evidence and provenance; renders to client report",
          tier: "A",
          capabilityKinds: ["cap:profile"],
          crossReferences: [],
          notes: [],
        },
        {
          displayNumber: 58,
          id: "fdpm.dpia",
          what: "Data Protection Impact Assessments per GDPR Art. 35: processing activities, risks, mitigations",
          why: "Required artefact for many EU operations; structured-evidence fit is strong",
          tier: "A",
          capabilityKinds: ["cap:profile"],
          crossReferences: [],
          notes: [],
        },
        {
          displayNumber: 59,
          id: "fdpm.pii-inventory",
          what: "Personal data fields, lawful basis, retention, transfer mechanisms",
          why: "Compliance graph; relations to data-products (#54) make impact analyses queryable",
          tier: "A",
          capabilityKinds: ["cap:profile"],
          crossReferences: ["fdpm.data-products"],
          notes: [],
        },
        {
          displayNumber: 60,
          id: "fdpm.data-classification",
          what: "Classification scheme, data assets, owners, controls per class",
          why: "Partner to #58/#59/#5; classification graph has clear typed relations",
          tier: "A",
          capabilityKinds: ["cap:profile"],
          crossReferences: ["fdpm.dpia", "fdpm.pii-inventory", "fdpm.compliance-controls"],
          notes: [],
        },
        {
          displayNumber: 61,
          id: "fdpm.slo-catalog",
          what: "SLI definitions, SLOs, error budgets, burn rates, decisions",
          why: "SLO docs live forever in Confluence; structured form enables cross-service rollups",
          tier: "S",
          capabilityKinds: ["cap:profile"],
          crossReferences: [],
          notes: [],
        },
        {
          displayNumber: 62,
          id: "fdpm.capacity-planning",
          what: "Resources, demand forecasts, headroom, scenarios",
          why: "Resource invariants + scenario branching fit FDPM well",
          tier: "A",
          capabilityKinds: ["cap:profile"],
          crossReferences: [],
          notes: [],
        },
        {
          displayNumber: 63,
          id: "fdpm.finops-tracker",
          what: "Cost units, budgets, variance, optimisation actions, savings claims with evidence",
          why: "Provenance for \"we saved $X\" claims is the FDPM-specific value",
          tier: "A",
          capabilityKinds: ["cap:profile"],
          crossReferences: [],
          notes: [],
        },
        {
          displayNumber: 64,
          id: "fdpm.cloud-architecture-review",
          what: "AWS WA / Azure WAF style: pillars, questions, evidence, action items",
          why: "The review itself is structured; result is queryable across reviews",
          tier: "A",
          capabilityKinds: ["cap:profile"],
          crossReferences: [],
          notes: [],
        },
        {
          displayNumber: 65,
          id: "fdpm.compliance-mapping",
          what: "Cross-framework control mappings (SOC2 ↔ ISO27001 ↔ NIST 800-53 ↔ CIS)",
          why: "Mapping graph is exactly typed relations; reduces N-way compliance work",
          tier: "S",
          capabilityKinds: ["cap:profile"],
          crossReferences: [],
          notes: [],
        },
        {
          displayNumber: 66,
          id: "fdpm.policy-as-code",
          what: "Policy intent, code rule, evidence, exceptions, owners",
          why: "Bridges human policy language to OPA/Cedar/Rego (#160/#161)",
          tier: "A",
          capabilityKinds: ["cap:profile"],
          crossReferences: ["fdpm.opa-rego-export", "fdpm.cedar-policy-export"],
          notes: [
            "Source #160/#161 are evernote-enex/dayone-json by display number. Cross-reference points at the semantically intended targets (fdpm.opa-rego-export #176, fdpm.cedar-policy-export #177).",
          ],
        },
        {
          displayNumber: 67,
          id: "fdpm.procurement-rfp",
          what: "Requirements, vendors, scoring criteria, evidence, decisions",
          why: "Decision provenance + scoring rationale survive vendor turnover",
          tier: "A",
          capabilityKinds: ["cap:profile"],
          crossReferences: [],
          notes: [],
        },
        {
          displayNumber: 68,
          id: "fdpm.vendor-risk-assessment",
          what: "Vendors, controls, evidence, residual risk, review cadence",
          why: "Tied to #65; renewal cadence as fs:Phase-as-time",
          tier: "A",
          capabilityKinds: ["cap:profile"],
          crossReferences: ["fdpm.compliance-mapping"],
          notes: [],
        },
        {
          displayNumber: 69,
          id: "fdpm.localization-glossary",
          what: "Terms, translations per locale, do-not-translate list, gendered forms",
          why: "Glossary as typed graph; CEL rule \"no untranslated UI key for active locale\"",
          tier: "A",
          capabilityKinds: ["cap:profile"],
          crossReferences: [],
          notes: [],
        },
        {
          displayNumber: 70,
          id: "fdpm.accessibility-audit",
          what: "WCAG 2.x criteria, evidence, components-affected, remediation",
          why: "WCAG criteria as Invariants is a strong fit; evidence-per-criterion is the workflow",
          tier: "S",
          capabilityKinds: ["cap:profile"],
          crossReferences: [],
          notes: [],
        },
        {
          displayNumber: 71,
          id: "fdpm.brand-guidelines",
          what: "Voice, visual tokens, do/don't, examples, exceptions",
          why: "Centralised guidelines that are queryable across product surfaces",
          tier: "A",
          capabilityKinds: ["cap:profile"],
          crossReferences: [],
          notes: [],
        },
        {
          displayNumber: 72,
          id: "fdpm.editorial-calendar",
          what: "Pieces, drafts, reviewers, publish dates, approvals",
          why: "Multi-channel content plan; status enum + provenance fit existing pattern",
          tier: "A",
          capabilityKinds: ["cap:profile"],
          crossReferences: [],
          notes: [],
        },
        {
          displayNumber: 73,
          id: "fdpm.investigative-journalism",
          what: "Claims, sources, evidence, contested points, FOIAs, redactions",
          why: "Source provenance + contested-claim primitives are the FDPM bullseye",
          tier: "S",
          capabilityKinds: ["cap:profile"],
          crossReferences: [],
          notes: [],
        },
        {
          displayNumber: 74,
          id: "fdpm.litigation-case",
          what: "Pleadings, exhibits, depositions, motions, rulings, chain-of-custody",
          why: "Strong fit on paper; entrenched tooling (Relativity etc.) is the threat",
          tier: "A",
          capabilityKinds: ["cap:profile"],
          crossReferences: [],
          notes: [],
        },
        {
          displayNumber: 75,
          id: "fdpm.patent-claims",
          what: "Claim chart, prior art, novelty arguments, embodiments",
          why: "Claim-element relations + prior-art evidence are typed relations",
          tier: "A",
          capabilityKinds: ["cap:profile"],
          crossReferences: [],
          notes: [],
        },
        {
          displayNumber: 76,
          id: "fdpm.grant-proposal",
          what: "Aims, milestones, budget, deliverables, evaluation plan",
          why: "Milestones + deliverables + evidence map cleanly to existing primitives",
          tier: "S",
          capabilityKinds: ["cap:profile"],
          crossReferences: [],
          notes: [],
        },
        {
          displayNumber: 77,
          id: "fdpm.peer-review-conference",
          what: "Submissions, reviewers, reviews, rebuttals, decisions",
          why: "Generalises #7 to conference workflow",
          tier: "A",
          capabilityKinds: ["cap:profile"],
          crossReferences: ["fdpm.research-papers"],
          notes: [],
        },
        {
          displayNumber: 78,
          id: "fdpm.test-strategy",
          what: "Test goals, levels, coverage, environments, gates",
          why: "Overlaps planning but distinct artefact; gate invariants are CEL",
          tier: "A",
          capabilityKinds: ["cap:profile"],
          crossReferences: [],
          notes: [],
        },
        {
          displayNumber: 79,
          id: "fdpm.performance-benchmarks",
          what: "Baselines, targets, regressions, hardware/run context",
          why: "Benchmark provenance is critical and usually missing",
          tier: "A",
          capabilityKinds: ["cap:profile"],
          crossReferences: [],
          notes: [],
        },
        {
          displayNumber: 80,
          id: "fdpm.lab-notebook",
          what: "Hypotheses, experiments, samples, observations, conclusions",
          why: "ELN replacement; provenance + invariants are core to the scientific record",
          tier: "S",
          capabilityKinds: ["cap:profile"],
          crossReferences: [],
          notes: [],
        },
        {
          displayNumber: 81,
          id: "fdpm.clinical-trial-protocol",
          what: "Inclusion/exclusion, arms, endpoints, safety monitoring, deviation log",
          why: "ICH-GCP requirements demand structured evidence; deviation log is event-sourced by nature",
          tier: "A",
          capabilityKinds: ["cap:profile"],
          crossReferences: [],
          notes: [],
        },
        {
          displayNumber: 82,
          id: "fdpm.statistical-analysis-plan",
          what: "Pre-registered analyses, primary/secondary endpoints, deviation log",
          why: "Pre-registration + deviation log is exactly an event-sourced workbook story",
          tier: "A",
          capabilityKinds: ["cap:profile"],
          crossReferences: [],
          notes: [],
        },
        {
          displayNumber: 83,
          id: "fdpm.survey-design",
          what: "Constructs, items, validity evidence, pilot results",
          why: "Construct-to-item relations + evidence chain",
          tier: "A",
          capabilityKinds: ["cap:profile"],
          crossReferences: [],
          notes: [],
        },
        {
          displayNumber: 84,
          id: "fdpm.argument-mapping",
          what: "IBIS / Toulmin / Walton: claims, grounds, warrants, rebuttals",
          why: "Argument structure is canonical typed relations; pure FDPM fit",
          tier: "A",
          capabilityKinds: ["cap:profile"],
          crossReferences: [],
          notes: [],
        },
        {
          displayNumber: 85,
          id: "fdpm.forecasting-questions",
          what: "Questions, predictions, resolution criteria, scoring",
          why: "Resolvable questions with public evidence are FDPM-shaped; ports Metaculus/GJP workflow",
          tier: "S",
          capabilityKinds: ["cap:profile"],
          crossReferences: [],
          notes: [],
        },
        {
          displayNumber: 86,
          id: "fdpm.decision-journal",
          what: "Decisions, predictions, retrospectives, calibration metrics",
          why: "Predictions + retros + scoring loops back through fs:Citation",
          tier: "S",
          capabilityKinds: ["cap:profile"],
          crossReferences: [],
          notes: [],
        },
        {
          displayNumber: 87,
          id: "fdpm.investor-pipeline",
          what: "Investors, intros, meetings, follow-ups, term-sheet drafts",
          why: "CRM-shaped; FDPM advantage is decision-rationale capture",
          tier: "A",
          capabilityKinds: ["cap:profile"],
          crossReferences: [],
          notes: [],
        },
        {
          displayNumber: 88,
          id: "fdpm.sales-cycle",
          what: "Accounts, opportunities, stages, forecasted close, evidence-of-progress",
          why: "Same critique as #87; salesforce ecosystem is dominant",
          tier: "B",
          capabilityKinds: ["cap:profile"],
          crossReferences: ["fdpm.investor-pipeline"],
          notes: [],
        },
        {
          displayNumber: 89,
          id: "fdpm.disaster-recovery",
          what: "RTO/RPO targets, runbooks, dependencies, drills, results",
          why: "Drill results as evidence + invariants for SLA targets",
          tier: "A",
          capabilityKinds: ["cap:profile"],
          crossReferences: [],
          notes: [],
        },
        {
          displayNumber: 90,
          id: "fdpm.business-continuity",
          what: "BIA, critical processes, dependencies, recovery strategies",
          why: "Subset of #89 in many shops; standalone where regulatory demands it",
          tier: "B",
          capabilityKinds: ["cap:profile"],
          crossReferences: ["fdpm.disaster-recovery"],
          notes: [],
        },
        {
          displayNumber: 91,
          id: "fdpm.postmortem-library",
          what: "Postmortems, contributing factors, action items, cross-incident patterns",
          why: "Cross-incident pattern mining is the FDPM-specific value",
          tier: "S",
          capabilityKinds: ["cap:profile"],
          crossReferences: [],
          notes: [],
        },
        {
          displayNumber: 92,
          id: "fdpm.tech-radar",
          what: "Technologies, rings (adopt/trial/assess/hold), justifications, history",
          why: "Ring history + justifications are typed timeline; complements #15",
          tier: "A",
          capabilityKinds: ["cap:profile"],
          crossReferences: ["fdpm.architecture-decisions"],
          notes: [],
        },
        {
          displayNumber: 93,
          id: "fdpm.dependency-licenses",
          what: "Dependencies, license, source-of-truth file, attribution requirements",
          why: "Compliance angle; pairs with SBOM #94",
          tier: "A",
          capabilityKinds: ["cap:profile"],
          crossReferences: ["fdpm.sbom-management"],
          notes: [],
        },
        {
          displayNumber: 94,
          id: "fdpm.sbom-management",
          what: "Components, versions, vendors, vulnerabilities, VEX statements",
          why: "SBOM as a queryable graph; CycloneDX/SPDX bridges (#151/#152)",
          tier: "A",
          capabilityKinds: ["cap:profile"],
          crossReferences: ["fdpm.cyclonedx-roundtrip", "fdpm.spdx-roundtrip"],
          notes: [
            "Source #151/#152 are crossref-doi-fetch / openalex-import. Cross-reference points at semantically intended SBOM round-trips (fdpm.cyclonedx-roundtrip #167, fdpm.spdx-roundtrip #168).",
          ],
        },
        {
          displayNumber: 95,
          id: "fdpm.release-notes-authoring",
          what: "Releases, items, audiences, draft notes, approvals",
          why: "Multi-audience draft + approval workflow; complements transformer #196",
          tier: "A",
          capabilityKinds: ["cap:profile"],
          crossReferences: [],
          notes: [
            "Source #196 is fdpm.dns-reachable. The intended pairing is with the decisions-to-release-notes transformer (fdpm.decisions-to-release-notes #214). Not adding the cross-reference here because the document's own text is unstable.",
          ],
        },
        {
          displayNumber: 96,
          id: "fdpm.preregistration",
          what: "Hypotheses, designs, analyses, deviations, public posting",
          why: "Open-science pre-registration is exactly an event-sourced ledger",
          tier: "A",
          capabilityKinds: ["cap:profile"],
          crossReferences: [],
          notes: [],
        },
        {
          displayNumber: 97,
          id: "fdpm.zettelkasten",
          what: "Atomic notes, links, structure notes, evolving index",
          why: "PKM angle; FDPM gives queryable links but most users prefer Obsidian/Logseq",
          tier: "B",
          capabilityKinds: ["cap:profile"],
          crossReferences: [],
          notes: [],
        },
        {
          displayNumber: 98,
          id: "fdpm.genealogy",
          what: "Persons, events, places, sources, evidence, relationships",
          why: "Source/evidence fit is strong; entrenched tools (Family Tree Maker, Gramps) very dominant",
          tier: "B",
          capabilityKinds: ["cap:profile"],
          crossReferences: [],
          notes: [],
        },
        {
          displayNumber: 99,
          id: "fdpm.commonplace-book",
          what: "Quotations, themes, cross-references, sources",
          why: "Generic note-taking with citations; thin FDPM-specific case",
          tier: "C",
          capabilityKinds: ["cap:profile"],
          crossReferences: [],
          notes: [],
        },
        {
          displayNumber: 100,
          id: "fdpm.podcast-production",
          what: "Episodes, guests, segments, edits, releases",
          why: "Real workflow but Notion templates already cover it; FDPM-specific value: decision provenance",
          tier: "C",
          capabilityKinds: ["cap:profile"],
          crossReferences: [],
          notes: [],
        },
        {
          displayNumber: 101,
          id: "fdpm.standard-operating-procedure",
          what: "SOP steps, owners, training records, version history",
          why: "Overlaps runbooks (#4); distinct in regulated industries (FDA, ISO 9001) where training records matter",
          tier: "A",
          capabilityKinds: ["cap:profile"],
          crossReferences: ["fdpm.runbooks"],
          notes: [],
        },
        {
          displayNumber: 102,
          id: "fdpm.terminology-management",
          what: "Source terms, target translations, definitions, usage notes, deprecations",
          why: "TBX-shaped vocabulary; partner to #69",
          tier: "A",
          capabilityKinds: ["cap:profile"],
          crossReferences: ["fdpm.localization-glossary"],
          notes: [],
        },
        {
          displayNumber: 103,
          id: "fdpm.api-versioning",
          what: "Versions, breaking changes, deprecation timeline, migration guides, consumer registry",
          why: "Strong overlap with #2 but distinct artefact; lifecycle invariants are the value",
          tier: "A",
          capabilityKinds: ["cap:profile"],
          crossReferences: ["fdpm.api-contracts"],
          notes: [],
        },
        {
          displayNumber: 104,
          id: "fdpm.experiment-results",
          what: "A/B test definitions, hypotheses, metrics, results, post-test decisions",
          why: "Distinct from #8 (discovery): the controlled-experiment ledger",
          tier: "A",
          capabilityKinds: ["cap:profile"],
          crossReferences: ["fdpm.product-discovery"],
          notes: [],
        },
        {
          displayNumber: 105,
          id: "fdpm.change-management",
          what: "Change requests, CAB decisions, implementation evidence, rollback plans",
          why: "ITIL-shaped; the CAB decision provenance is FDPM-specific value",
          tier: "A",
          capabilityKinds: ["cap:profile"],
          crossReferences: [],
          notes: [],
        },
        {
          displayNumber: 106,
          id: "fdpm.deprecation-tracking",
          what: "Deprecated features, sunset dates, migration guidance, blocking consumers",
          why: "Subset of #103 but distinct; consumer-block invariants are useful",
          tier: "B",
          capabilityKinds: ["cap:profile"],
          crossReferences: ["fdpm.api-versioning"],
          notes: [],
        },
        {
          displayNumber: 107,
          id: "fdpm.ab-testing-platform",
          what: "Same as #104 with platform-side primitives (assignment service, exposures)",
          why: "Mostly subsumed by #104; standalone only at scale",
          tier: "B",
          capabilityKinds: ["cap:profile"],
          crossReferences: ["fdpm.experiment-results"],
          notes: [],
        },
        {
          displayNumber: 108,
          id: "fdpm.research-program",
          what: "Multi-year programs with workstreams, milestones, deliverables, dependencies",
          why: "Program-of-record artefact; cross-grant integration",
          tier: "A",
          capabilityKinds: ["cap:profile"],
          crossReferences: [],
          notes: [],
        },
        {
          displayNumber: 109,
          id: "fdpm.knowledge-base",
          what: "Articles, categories, FAQs, ownership, freshness",
          why: "Generic; #36/#179 are the FDPM-specific freshness story",
          tier: "B",
          capabilityKinds: ["cap:profile"],
          crossReferences: ["fdpm.url-currency"],
          notes: [
            "Source #179 is fdpm.ics-import (calendar). The intended freshness story pairs with fdpm.url-currency #36 only.",
          ],
        },
        {
          displayNumber: 110,
          id: "fdpm.aircraft-maintenance",
          what: "Airworthiness directives, scheduled checks, anomalies, evidence",
          why: "Regulated rigour fits FDPM; entrenched OEM tooling is the headwind",
          tier: "B",
          capabilityKinds: ["cap:profile"],
          crossReferences: [],
          notes: [],
        },
        {
          displayNumber: 111,
          id: "fdpm.observability-strategy",
          what: "Telemetry sources, dashboards, alerts, runbooks, owners",
          why: "Subset of #61 + #4 in most orgs",
          tier: "B",
          capabilityKinds: ["cap:profile"],
          crossReferences: ["fdpm.slo-catalog", "fdpm.runbooks"],
          notes: [],
        },
        {
          displayNumber: 112,
          id: "fdpm.cost-estimate-bom",
          what: "Materials, labor, contingency, vendor quotes, evidence-of-price",
          why: "Construction/manufacturing BOM with provenance",
          tier: "A",
          capabilityKinds: ["cap:profile"],
          crossReferences: [],
          notes: [],
        },
        {
          displayNumber: 113,
          id: "fdpm.regulatory-submission",
          what: "FDA / EMA / equivalent submissions: documents, claims, evidence, status",
          why: "Strong fit; very entrenched tooling",
          tier: "A",
          capabilityKinds: ["cap:profile"],
          crossReferences: [],
          notes: [],
        },
        {
          displayNumber: 114,
          id: "fdpm.policy-document",
          what: "Policies, scope, exceptions, attestation records",
          why: "Pairs with #65/#66; attestation log is the value",
          tier: "A",
          capabilityKinds: ["cap:profile"],
          crossReferences: ["fdpm.compliance-mapping", "fdpm.policy-as-code"],
          notes: [],
        },
        {
          displayNumber: 115,
          id: "fdpm.kpi-dashboard",
          what: "KPIs, definitions, owners, evidence sources, history of values",
          why: "KPI definition drift is real; provenance is the differentiator",
          tier: "A",
          capabilityKinds: ["cap:profile"],
          crossReferences: [],
          notes: [],
        },
      ],
    },

    {
      title: "Renderers",
      primaryCapabilityKinds: ["cap:renderer"],
      description:
        "Section header in source markdown declares 35 entries; rows actually present number 36. Validator will flag.",
      entries: [
        { displayNumber: 16, id: "fdpm.gantt-svg", what: "Render plan:* workbooks as SVG Gantt charts with critical-path highlighting", why: "Already partially in planning plugin; promote to standalone", tier: "S", capabilityKinds: ["cap:renderer"], crossReferences: [], notes: [] },
        { displayNumber: 17, id: "fdpm.mermaid-flowchart", what: "Phase + Precedes graph → Mermaid flowchart TD markdown", why: "One-line embed in any markdown render", tier: "S", capabilityKinds: ["cap:renderer"], crossReferences: [], notes: [] },
        { displayNumber: 18, id: "fdpm.graphviz-dot", what: "Full graph as Graphviz .dot for layout-quality diagrams", why: "Mermaid hits limits past ~30 nodes; dot scales further", tier: "S", capabilityKinds: ["cap:renderer"], crossReferences: [], notes: [] },
        { displayNumber: 19, id: "fdpm.cytoscape-json", what: "Export as Cytoscape.js JSON for interactive web exploration", why: 'Pairs naturally with the web/ browser as a "graph view" tab', tier: "S", capabilityKinds: ["cap:renderer"], crossReferences: [], notes: [] },
        { displayNumber: 20, id: "fdpm.docx", what: "Microsoft Word renderer for client-facing deliverables", why: "Markdown-to-DOCX is everyone's pain; one plugin solves it for all profiles", tier: "S", capabilityKinds: ["cap:renderer"], crossReferences: [], notes: [] },
        { displayNumber: 21, id: "fdpm.latex-paper", what: "LaTeX article/IEEE/ACM templates for formal-specification workbooks", why: "Real-world output target for #7", tier: "S", capabilityKinds: ["cap:renderer"], crossReferences: ["fdpm.research-papers"], notes: [] },
        { displayNumber: 22, id: "fdpm.epub", what: "Long-form workbooks (formal specs, books) as EPUB", why: "Different reader audience; reuses existing markdown pipeline", tier: "A", capabilityKinds: ["cap:renderer"], crossReferences: [], notes: [] },
        { displayNumber: 23, id: "fdpm.confluence-storage-format", what: "XML output that pastes directly into Confluence pages", why: "Enterprise teams need this; bridges FDPM and corporate wikis", tier: "S", capabilityKinds: ["cap:renderer"], crossReferences: [], notes: [] },
        { displayNumber: 24, id: "fdpm.notion-blocks", what: "Notion API block JSON; fdpm sync notion-page <id> two-way push", why: "Same use case as Confluence for a different stack", tier: "S", capabilityKinds: ["cap:renderer"], crossReferences: [], notes: [] },
        { displayNumber: 25, id: "fdpm.json-ld-schema-org", what: "Render as Schema.org JSON-LD for SEO-friendly publication", why: "Useful for public-facing spec sites", tier: "B", capabilityKinds: ["cap:renderer"], crossReferences: [], notes: [] },
        { displayNumber: 116, id: "fdpm.reveal-slides", what: "Reveal.js slide deck from workbook headings + content", why: "Presentation is universal need; primitive→slide mapping is FDPM-specific", tier: "S", capabilityKinds: ["cap:renderer"], crossReferences: [], notes: [] },
        { displayNumber: 117, id: "fdpm.quarto", what: "Quarto-flavored markdown for reproducible publishing", why: "Strong overlap with research/notebook authors", tier: "A", capabilityKinds: ["cap:renderer"], crossReferences: [], notes: [] },
        { displayNumber: 118, id: "fdpm.pandoc-multi", what: "Pandoc-driven multi-format export bundle (HTML/PDF/DOCX/EPUB in one pass)", why: "Lowers cost of #20/#22/#119 by reusing one pipeline", tier: "A", capabilityKinds: ["cap:renderer"], crossReferences: ["fdpm.docx", "fdpm.epub", "fdpm.static-html"], notes: [] },
        { displayNumber: 119, id: "fdpm.static-html", what: "Self-contained static HTML site (one workbook = one site) with built-in graph view", why: "Cheap publishing; pairs with #19 as embedded view", tier: "S", capabilityKinds: ["cap:renderer"], crossReferences: ["fdpm.cytoscape-json"], notes: [] },
        { displayNumber: 120, id: "fdpm.docusaurus-site", what: "Docusaurus content tree with frontmatter + sidebar generated from primitive index", why: "Common docs stack; fewer migrations needed", tier: "A", capabilityKinds: ["cap:renderer"], crossReferences: [], notes: [] },
        { displayNumber: 121, id: "fdpm.mkdocs-site", what: "MkDocs/Material content tree", why: "Same case as #120 for a different stack", tier: "A", capabilityKinds: ["cap:renderer"], crossReferences: ["fdpm.docusaurus-site"], notes: [] },
        { displayNumber: 122, id: "fdpm.hugo-content", what: "Hugo content tree with frontmatter", why: "Same case as #120/#121", tier: "A", capabilityKinds: ["cap:renderer"], crossReferences: ["fdpm.docusaurus-site", "fdpm.mkdocs-site"], notes: [] },
        { displayNumber: 123, id: "fdpm.jekyll-content", what: "Jekyll content tree", why: "GitHub Pages default; declining elsewhere", tier: "B", capabilityKinds: ["cap:renderer"], crossReferences: [], notes: [] },
        { displayNumber: 124, id: "fdpm.eleventy-data", what: "Eleventy `_data` files", why: "Smaller audience than Hugo/Astro", tier: "B", capabilityKinds: ["cap:renderer"], crossReferences: [], notes: [] },
        { displayNumber: 125, id: "fdpm.astro-collections", what: "Astro content collections", why: "Modern, growing ecosystem", tier: "A", capabilityKinds: ["cap:renderer"], crossReferences: [], notes: [] },
        { displayNumber: 126, id: "fdpm.gitbook", what: "GitBook source export", why: "GitBook product churn makes this a moving target", tier: "B", capabilityKinds: ["cap:renderer"], crossReferences: [], notes: [] },
        { displayNumber: 127, id: "fdpm.dita-xml", what: "DITA XML for tech-pubs teams", why: "Real but very niche audience", tier: "B", capabilityKinds: ["cap:renderer"], crossReferences: [], notes: [] },
        { displayNumber: 128, id: "fdpm.docbook-xml", what: "DocBook XML output", why: "Interchangeable with #127; low demand", tier: "C", capabilityKinds: ["cap:renderer"], crossReferences: ["fdpm.dita-xml"], notes: [] },
        { displayNumber: 129, id: "fdpm.tei-xml", what: "TEI XML for digital humanities", why: "Niche but a real audience for #7 specialisations", tier: "C", capabilityKinds: ["cap:renderer"], crossReferences: ["fdpm.research-papers"], notes: [] },
        { displayNumber: 130, id: "fdpm.asciidoc", what: "AsciiDoc output", why: "Interchangeable with markdown; some communities prefer it", tier: "B", capabilityKinds: ["cap:renderer"], crossReferences: [], notes: [] },
        { displayNumber: 131, id: "fdpm.org-mode", what: "Emacs Org-mode export", why: "Niche by design; original list called this out", tier: "C", capabilityKinds: ["cap:renderer"], crossReferences: [], notes: [] },
        { displayNumber: 132, id: "fdpm.opml", what: "OPML outline export for outliner tools", why: "Cheap to produce; small audience", tier: "B", capabilityKinds: ["cap:renderer"], crossReferences: [], notes: [] },
        { displayNumber: 133, id: "fdpm.plantuml", what: "PlantUML diagrams from typed relations", why: "Server-side render available; widely used in enterprise wikis", tier: "A", capabilityKinds: ["cap:renderer"], crossReferences: [], notes: [] },
        { displayNumber: 134, id: "fdpm.d2-diagram", what: "D2 diagrams from typed relations", why: "Modern alternative to Mermaid; cleaner output for medium-sized graphs", tier: "A", capabilityKinds: ["cap:renderer"], crossReferences: [], notes: [] },
        { displayNumber: 135, id: "fdpm.bpmn-xml", what: "BPMN 2.0 XML for process diagrams", why: "Pairs with #4 (runbooks) and #105 (change management)", tier: "A", capabilityKinds: ["cap:renderer"], crossReferences: ["fdpm.runbooks", "fdpm.change-management"], notes: [] },
        { displayNumber: 136, id: "fdpm.archimate", what: "ArchiMate model XML for enterprise architecture", why: "Enterprise audience; entrenched", tier: "B", capabilityKinds: ["cap:renderer"], crossReferences: [], notes: [] },
        { displayNumber: 137, id: "fdpm.tikz", what: "TikZ embeds for LaTeX papers", why: "Renders inside #21; useful for high-quality print figures", tier: "B", capabilityKinds: ["cap:renderer"], crossReferences: ["fdpm.latex-paper"], notes: [] },
        { displayNumber: 138, id: "fdpm.print-pdf", what: "PDF/A archival via headless browser", why: "Compliance/archival use case beyond #20", tier: "A", capabilityKinds: ["cap:renderer"], crossReferences: ["fdpm.docx"], notes: [] },
        { displayNumber: 139, id: "fdpm.html-email", what: "MJML-based responsive email render of editorial-calendar / release-notes", why: "Niche but real for #72/#95 audiences", tier: "C", capabilityKinds: ["cap:renderer"], crossReferences: ["fdpm.editorial-calendar", "fdpm.release-notes-authoring"], notes: [] },
        { displayNumber: 140, id: "fdpm.rss-atom", what: "RSS / Atom feed of operation log or release-note workbook", why: "Cheap; useful publishing channel for public workbooks", tier: "A", capabilityKinds: ["cap:renderer"], crossReferences: [], notes: [] },
        { displayNumber: 141, id: "fdpm.json-feed", what: "JSON Feed equivalent of #140", why: "Fully redundant with #140 unless an audience demands JSON Feed", tier: "C", capabilityKinds: ["cap:renderer"], crossReferences: ["fdpm.rss-atom"], notes: [] },
      ],
    },

    {
      title: "Importers / Exporters",
      primaryCapabilityKinds: ["cap:importer", "cap:exporter"],
      description:
        "Section header in source markdown declares 50 entries; rows actually present number 52. Validator will flag.",
      entries: [
        { displayNumber: 26, id: "fdpm.openapi-import", what: "OpenAPI YAML/JSON → api-contracts workbook", why: "Bootstrap an editable workbook from existing API definitions", tier: "S", capabilityKinds: ["cap:importer"], crossReferences: [], notes: [] },
        { displayNumber: 27, id: "fdpm.openapi-export", what: "api-contracts workbook → OpenAPI YAML", why: "Round-trip; CI generates the OpenAPI from the workbook", tier: "S", capabilityKinds: ["cap:exporter"], crossReferences: ["fdpm.openapi-import"], notes: [] },
        { displayNumber: 28, id: "fdpm.protobuf-import", what: ".proto schemas → typed primitives + relations", why: "Same story for protobuf-shop teams", tier: "A", capabilityKinds: ["cap:importer"], crossReferences: [], notes: [] },
        { displayNumber: 29, id: "fdpm.json-schema-roundtrip", what: "JSON Schema ↔ fs:Schema primitives", why: "Bridges to JSONSchema tooling for validation", tier: "S", capabilityKinds: ["cap:importer", "cap:exporter"], crossReferences: [], notes: [] },
        { displayNumber: 30, id: "fdpm.tla-plus-export", what: "Phase + Invariant graph → TLA+ specification", why: "High-rigour leap; not all plans need this but specs do", tier: "A", capabilityKinds: ["cap:exporter"], crossReferences: [], notes: [] },
        { displayNumber: 31, id: "fdpm.markdown-spec-import", what: "Parse a structured markdown spec back into a workbook", why: "Lets authors keep using markdown editors while gaining the queryable graph", tier: "S", capabilityKinds: ["cap:importer"], crossReferences: [], notes: [] },
        { displayNumber: 32, id: "fdpm.csv-table-import", what: "Wide CSV → many primitives of one type, one row each", why: "Fast bootstrap from spreadsheets; teams everywhere have these", tier: "S", capabilityKinds: ["cap:importer"], crossReferences: [], notes: [] },
        { displayNumber: 33, id: "fdpm.linear-jira-import", what: "Issue trackers → plan:Task primitives with status mapping", why: "Migration path from existing PM tools", tier: "S", capabilityKinds: ["cap:importer"], crossReferences: [], notes: [] },
        { displayNumber: 34, id: "fdpm.git-history-import", what: "Commits as fs:ChangeRecord primitives, authors as actors", why: "Brings the actual history of work into the workbook", tier: "A", capabilityKinds: ["cap:importer"], crossReferences: [], notes: [] },
        { displayNumber: 35, id: "fdpm.zotero-import", what: "Zotero library → fs:Citation primitives with currency-date", why: "Academic workflow; the citations come from somewhere", tier: "S", capabilityKinds: ["cap:importer"], crossReferences: [], notes: [] },
        { displayNumber: 142, id: "fdpm.graphql-sdl-import", what: "GraphQL SDL → typed primitives (Type, Field, Resolver hints)", why: "Same case as #28 for GraphQL shops", tier: "A", capabilityKinds: ["cap:importer"], crossReferences: ["fdpm.protobuf-import"], notes: [] },
        { displayNumber: 143, id: "fdpm.graphql-sdl-export", what: "typed primitives → GraphQL SDL", why: "Round-trip with #142", tier: "A", capabilityKinds: ["cap:exporter"], crossReferences: ["fdpm.graphql-sdl-import"], notes: [] },
        { displayNumber: 144, id: "fdpm.asyncapi-import", what: "AsyncAPI → event-bus contracts", why: "Async/event-driven equivalent of #26", tier: "A", capabilityKinds: ["cap:importer"], crossReferences: ["fdpm.openapi-import"], notes: [] },
        { displayNumber: 145, id: "fdpm.asyncapi-export", what: "typed primitives → AsyncAPI document", why: "Round-trip with #144", tier: "A", capabilityKinds: ["cap:exporter"], crossReferences: ["fdpm.asyncapi-import"], notes: [] },
        { displayNumber: 146, id: "fdpm.avro-schema-roundtrip", what: "Avro schemas (Confluent Schema Registry-friendly) ↔ fs:Schema", why: "Streaming-platform schema shops", tier: "B", capabilityKinds: ["cap:importer", "cap:exporter"], crossReferences: [], notes: [] },
        { displayNumber: 147, id: "fdpm.thrift-import", what: "Apache Thrift IDL → primitives", why: "Declining ecosystem; included for completeness", tier: "C", capabilityKinds: ["cap:importer"], crossReferences: [], notes: [] },
        { displayNumber: 148, id: "fdpm.bibtex-roundtrip", what: "BibTeX bibliography ↔ fs:Citation", why: "Default for LaTeX-publishing teams", tier: "S", capabilityKinds: ["cap:importer", "cap:exporter"], crossReferences: [], notes: [] },
        { displayNumber: 149, id: "fdpm.csl-json-roundtrip", what: "CSL-JSON citation interchange", why: "Pandoc/Zotero compatible interchange format", tier: "S", capabilityKinds: ["cap:importer", "cap:exporter"], crossReferences: [], notes: [] },
        { displayNumber: 150, id: "fdpm.ris-import", what: "RIS bibliography format", why: "Older but still emitted by many databases", tier: "A", capabilityKinds: ["cap:importer"], crossReferences: [], notes: [] },
        { displayNumber: 151, id: "fdpm.crossref-doi-fetch", what: "DOI metadata via Crossref API", why: 'Closes the "I have a DOI, give me the citation" loop', tier: "S", capabilityKinds: ["cap:importer"], crossReferences: [], notes: [] },
        { displayNumber: 152, id: "fdpm.openalex-import", what: "OpenAlex paper metadata + citation graph", why: "Free, large; complements #35", tier: "A", capabilityKinds: ["cap:importer"], crossReferences: ["fdpm.zotero-import"], notes: [] },
        { displayNumber: 153, id: "fdpm.arxiv-import", what: "arXiv metadata + abstracts", why: "Cheap, public, well-typed", tier: "A", capabilityKinds: ["cap:importer"], crossReferences: [], notes: [] },
        { displayNumber: 154, id: "fdpm.pubmed-import", what: "PubMed entries with MeSH terms", why: "Medical research workflow", tier: "A", capabilityKinds: ["cap:importer"], crossReferences: [], notes: [] },
        { displayNumber: 155, id: "fdpm.semanticscholar-import", what: "Semantic Scholar API import with citation graph", why: "Useful for citation-graph queries", tier: "A", capabilityKinds: ["cap:importer"], crossReferences: [], notes: [] },
        { displayNumber: 156, id: "fdpm.obsidian-vault-import", what: "Obsidian vault → workbook with link preservation", why: "Migration target; large user base", tier: "A", capabilityKinds: ["cap:importer"], crossReferences: [], notes: [] },
        { displayNumber: 157, id: "fdpm.logseq-import", what: "Logseq graph → workbook", why: "Same as #156 for Logseq users", tier: "A", capabilityKinds: ["cap:importer"], crossReferences: ["fdpm.obsidian-vault-import"], notes: [] },
        { displayNumber: 158, id: "fdpm.roam-json-import", what: "Roam Research JSON → workbook", why: "User base shrinking but the import is cheap", tier: "B", capabilityKinds: ["cap:importer"], crossReferences: [], notes: [] },
        { displayNumber: 159, id: "fdpm.notion-export-import", what: "Notion ZIP/markdown export → workbook", why: "Notion exports are the standard migration path", tier: "A", capabilityKinds: ["cap:importer"], crossReferences: [], notes: [] },
        { displayNumber: 160, id: "fdpm.evernote-enex", what: "Evernote ENEX archive", why: "Legacy migration; small audience now", tier: "C", capabilityKinds: ["cap:importer"], crossReferences: [], notes: [] },
        { displayNumber: 161, id: "fdpm.dayone-json", what: "Day One journal export", why: "Personal-use only; thin case", tier: "C", capabilityKinds: ["cap:importer"], crossReferences: [], notes: [] },
        { displayNumber: 162, id: "fdpm.github-issues-import", what: "GitHub issues + PRs → primitives with reactions, labels, milestones", why: "Broader than #33; PR linkage is what makes it FDPM-shaped", tier: "S", capabilityKinds: ["cap:importer"], crossReferences: ["fdpm.linear-jira-import"], notes: [] },
        { displayNumber: 163, id: "fdpm.gitlab-issues-import", what: "GitLab issues + MRs", why: "Same as #162 for GitLab", tier: "A", capabilityKinds: ["cap:importer"], crossReferences: ["fdpm.github-issues-import"], notes: [] },
        { displayNumber: 164, id: "fdpm.asana-export", what: "Asana project export → primitives", why: "PM migration path", tier: "A", capabilityKinds: ["cap:importer"], crossReferences: [], notes: [] },
        { displayNumber: 165, id: "fdpm.trello-board", what: "Trello board JSON → primitives", why: "Lightweight migration", tier: "B", capabilityKinds: ["cap:importer"], crossReferences: [], notes: [] },
        { displayNumber: 166, id: "fdpm.clickup-export", what: "ClickUp export → primitives", why: "One more PM tool migration; declining differentiation", tier: "B", capabilityKinds: ["cap:importer"], crossReferences: [], notes: [] },
        { displayNumber: 167, id: "fdpm.cyclonedx-roundtrip", what: "CycloneDX SBOM ↔ workbook (pairs with #94)", why: "SBOM is now a regulatory requirement in many jurisdictions", tier: "S", capabilityKinds: ["cap:importer", "cap:exporter"], crossReferences: ["fdpm.sbom-management"], notes: [] },
        { displayNumber: 168, id: "fdpm.spdx-roundtrip", what: "SPDX SBOM ↔ workbook", why: "Other half of the SBOM duopoly", tier: "S", capabilityKinds: ["cap:importer", "cap:exporter"], crossReferences: ["fdpm.cyclonedx-roundtrip"], notes: [] },
        { displayNumber: 169, id: "fdpm.vex-roundtrip", what: "VEX statements ↔ workbook", why: "Pairs with #94/#167/#168; statements are signed events", tier: "A", capabilityKinds: ["cap:importer", "cap:exporter"], crossReferences: ["fdpm.sbom-management", "fdpm.cyclonedx-roundtrip", "fdpm.spdx-roundtrip"], notes: [] },
        { displayNumber: 170, id: "fdpm.oscal-import", what: "OSCAL compliance import (catalog/profile/SSP)", why: "Pairs with #5/#65", tier: "A", capabilityKinds: ["cap:importer"], crossReferences: ["fdpm.compliance-controls", "fdpm.compliance-mapping"], notes: [] },
        { displayNumber: 171, id: "fdpm.oscal-export", what: "OSCAL compliance export", why: "Round-trip with #170", tier: "A", capabilityKinds: ["cap:exporter"], crossReferences: ["fdpm.oscal-import"], notes: [] },
        { displayNumber: 172, id: "fdpm.stix-import", what: "STIX threat intel → indicators, campaigns, attribution", why: "Pairs with #1/#56", tier: "A", capabilityKinds: ["cap:importer"], crossReferences: ["fdpm.threat-modeling", "fdpm.cve-triage"], notes: [] },
        { displayNumber: 173, id: "fdpm.attack-import", what: "MITRE ATT&CK technique import as reference primitives", why: "Reference graph for #1/#172", tier: "A", capabilityKinds: ["cap:importer"], crossReferences: ["fdpm.threat-modeling", "fdpm.stix-import"], notes: [] },
        { displayNumber: 174, id: "fdpm.cve-feed-import", what: "NVD CVE feed import", why: "Feeds #56", tier: "A", capabilityKinds: ["cap:importer"], crossReferences: ["fdpm.cve-triage"], notes: [] },
        { displayNumber: 175, id: "fdpm.osv-vuln-import", what: "OSV vulnerability database import", why: "Multi-ecosystem alternative to #174", tier: "A", capabilityKinds: ["cap:importer"], crossReferences: ["fdpm.cve-feed-import"], notes: [] },
        { displayNumber: 176, id: "fdpm.opa-rego-export", what: "workbook policies → OPA Rego", why: "Bridges #66 to enforcement", tier: "A", capabilityKinds: ["cap:exporter"], crossReferences: ["fdpm.policy-as-code"], notes: [] },
        { displayNumber: 177, id: "fdpm.cedar-policy-export", what: "workbook policies → Cedar", why: "Same as #176 for Cedar", tier: "A", capabilityKinds: ["cap:exporter"], crossReferences: ["fdpm.opa-rego-export"], notes: [] },
        { displayNumber: 178, id: "fdpm.ics-export", what: "ICS calendar from plan:Task with deadlines", why: "Cheap; high utility for human consumers", tier: "A", capabilityKinds: ["cap:exporter"], crossReferences: [], notes: [] },
        { displayNumber: 179, id: "fdpm.ics-import", what: "ICS calendar → plan:Task", why: "Less common direction; useful for capturing existing calendars", tier: "B", capabilityKinds: ["cap:importer"], crossReferences: ["fdpm.ics-export"], notes: [] },
        { displayNumber: 180, id: "fdpm.xlsx-import", what: "Multi-sheet XLSX → primitives by sheet", why: "Spreadsheet-native teams", tier: "A", capabilityKinds: ["cap:importer"], crossReferences: [], notes: [] },
        { displayNumber: 181, id: "fdpm.xlsx-export", what: "Workbook → multi-sheet XLSX", why: 'Round-trip with #180; the "send to finance" path', tier: "A", capabilityKinds: ["cap:exporter"], crossReferences: ["fdpm.xlsx-import"], notes: [] },
        { displayNumber: 182, id: "fdpm.airtable-import", what: "Airtable base → primitives", why: "Airtable is a common pre-FDPM home", tier: "A", capabilityKinds: ["cap:importer"], crossReferences: [], notes: [] },
        { displayNumber: 183, id: "fdpm.coda-import", what: "Coda doc → primitives", why: "Same as #182 for Coda", tier: "B", capabilityKinds: ["cap:importer"], crossReferences: ["fdpm.airtable-import"], notes: [] },
      ],
    },

    {
      title: "Validators / expr helpers",
      primaryCapabilityKinds: ["cap:validator", "cap:expr-helper"],
      entries: [
        { displayNumber: 36, id: "fdpm.url-currency", what: "CEL helper fn.fdpm.url-currency.fetch(url, max_age) checking citations aren't 404 / stale", why: "Closes the citation-currency gap that the formal-spec profile only warns about", tier: "S", capabilityKinds: ["cap:expr-helper"], crossReferences: [], notes: [] },
        { displayNumber: 37, id: "fdpm.regex-corpus", what: "CEL helper for cross-primitive regex queries beyond what stock CEL exposes", why: 'Enables rules like "no two definitions share a key term"', tier: "A", capabilityKinds: ["cap:expr-helper"], crossReferences: [], notes: [] },
        { displayNumber: 38, id: "fdpm.spell-check", what: "Validator that flags spelling errors in description/statement/claim fields", why: "Pure-validation use case; plugin owns the dictionary", tier: "A", capabilityKinds: ["cap:validator"], crossReferences: [], notes: [] },
        { displayNumber: 39, id: "fdpm.style-guide", what: "Validator enforcing project-specific writing rules (passive-voice, em-dash policy, sentence length)", why: "Each project picks its own style; the plugin is parameterised", tier: "A", capabilityKinds: ["cap:validator"], crossReferences: [], notes: [] },
        { displayNumber: 40, id: "fdpm.dead-link-detector", what: "Async lifecycle-hook validator that checks every url field at workbook load time", why: "Cheap once-per-day pass; prevents bibliography rot", tier: "S", capabilityKinds: ["cap:validator", "cap:lifecycle-hook"], crossReferences: [], notes: [] },
        { displayNumber: 184, id: "fdpm.date-arith", what: "CEL helpers for date math (intervals, business days, recurrence, age-from-date)", why: "Date logic in CEL is painful otherwise; underpins many invariants", tier: "S", capabilityKinds: ["cap:expr-helper"], crossReferences: [], notes: [] },
        { displayNumber: 185, id: "fdpm.unit-convert", what: "Unit conversion helpers (SI ↔ imperial; currency with explicit rate-source provenance)", why: "Currency conversions without provenance are a known footgun", tier: "S", capabilityKinds: ["cap:expr-helper"], crossReferences: [], notes: [] },
        { displayNumber: 186, id: "fdpm.geo-distance", what: "Lat/lon distance, bounding-box, point-in-polygon helpers", why: "Underpins #11/#12/#80 plus many investigative-journalism queries", tier: "A", capabilityKinds: ["cap:expr-helper"], crossReferences: ["fdpm.recipe-cookbook", "fdpm.gardening-plot", "fdpm.lab-notebook"], notes: [] },
        { displayNumber: 187, id: "fdpm.semver-helpers", what: "Semver parsing/comparison helpers", why: "Foundation for #103/#106", tier: "A", capabilityKinds: ["cap:expr-helper"], crossReferences: ["fdpm.api-versioning", "fdpm.deprecation-tracking"], notes: [] },
        { displayNumber: 188, id: "fdpm.cron-helpers", what: "Cron expression parsing + next-run helpers", why: "Foundation for any scheduled-job profile", tier: "A", capabilityKinds: ["cap:expr-helper"], crossReferences: [], notes: [] },
        { displayNumber: 189, id: "fdpm.iso-codes", what: "ISO 3166 country / 4217 currency / 639 language code validators", why: "Catches a class of typo errors with ~zero false positives", tier: "A", capabilityKinds: ["cap:validator"], crossReferences: [], notes: [] },
        { displayNumber: 190, id: "fdpm.bcp47-locale", what: "BCP 47 locale tag validation (`en-US-x-piglatin`)", why: "Underpins #69/#102", tier: "A", capabilityKinds: ["cap:validator"], crossReferences: ["fdpm.localization-glossary", "fdpm.terminology-management"], notes: [] },
        { displayNumber: 191, id: "fdpm.email-rfc5322", what: "Email validation per RFC 5322", why: "Strict spec is rarely needed; most use cases are #194-class", tier: "B", capabilityKinds: ["cap:validator"], crossReferences: ["fdpm.cidr-overlap"], notes: [] },
        { displayNumber: 192, id: "fdpm.url-canonical", what: "URL canonicalisation helper (strip tracking, normalise)", why: "Reduces false positives in #36/#40", tier: "A", capabilityKinds: ["cap:expr-helper"], crossReferences: ["fdpm.url-currency", "fdpm.dead-link-detector"], notes: [] },
        { displayNumber: 193, id: "fdpm.uuid-ulid", what: "UUID/ULID generation + validation", why: "Foundation primitive; trivial but worth bundling", tier: "A", capabilityKinds: ["cap:expr-helper", "cap:validator"], crossReferences: [], notes: [] },
        { displayNumber: 194, id: "fdpm.cidr-overlap", what: "IPv4/IPv6 + CIDR validators with overlap detection", why: "Underpins network-asset profiles; specific FDPM value: cross-primitive overlap rules", tier: "B", capabilityKinds: ["cap:validator"], crossReferences: [], notes: [] },
        { displayNumber: 195, id: "fdpm.tls-expiry", what: "Lifecycle hook flagging TLS certs near expiry referenced in any primitive", why: "Cheap once-per-day pass; prevents certificate-rot", tier: "A", capabilityKinds: ["cap:lifecycle-hook", "cap:validator"], crossReferences: [], notes: [] },
        { displayNumber: 196, id: "fdpm.dns-reachable", what: "Periodic DNS reachability check on URLs", why: "Subset of #40; standalone for hostname-typed primitives", tier: "B", capabilityKinds: ["cap:validator", "cap:lifecycle-hook"], crossReferences: ["fdpm.dead-link-detector"], notes: [] },
        { displayNumber: 197, id: "fdpm.archival-snapshot", what: "Lifecycle hook posting cited URLs to Wayback Machine and storing the snapshot URL", why: "Closes the citation-rot loop more aggressively than #36/#40", tier: "S", capabilityKinds: ["cap:lifecycle-hook"], crossReferences: ["fdpm.url-currency", "fdpm.dead-link-detector"], notes: [] },
        { displayNumber: 198, id: "fdpm.fixity-check", what: "SHA-256 fixity check on linked assets", why: "Prevents silent-bitrot for evidence-of-record workflows (#73/#74/#80)", tier: "A", capabilityKinds: ["cap:validator", "cap:lifecycle-hook"], crossReferences: ["fdpm.investigative-journalism", "fdpm.litigation-case", "fdpm.lab-notebook"], notes: [] },
        { displayNumber: 199, id: "fdpm.license-spdx", what: "Validate license fields against SPDX list; flag incompatibilities with project license", why: "Pairs with #93/#94", tier: "S", capabilityKinds: ["cap:validator"], crossReferences: ["fdpm.dependency-licenses", "fdpm.sbom-management"], notes: [] },
        { displayNumber: 200, id: "fdpm.osv-vuln-check", what: "Scan dependency primitives against OSV database", why: "Validator surface of #175", tier: "A", capabilityKinds: ["cap:validator"], crossReferences: ["fdpm.osv-vuln-import"], notes: [] },
        { displayNumber: 201, id: "fdpm.required-field-conditional", what: 'CEL helper enabling rules like "if status=resolved then resolution_evidence_required"', why: "Enables far-richer profile invariants", tier: "S", capabilityKinds: ["cap:expr-helper"], crossReferences: [], notes: [] },
        { displayNumber: 202, id: "fdpm.acronym-expand", what: "Validator: every acronym must have a glossary primitive", why: "Pairs with #226", tier: "A", capabilityKinds: ["cap:validator"], crossReferences: ["fdpm.email-gateway"], notes: [
          "Source #226 is fdpm.email-gateway; the textual pairing is unclear and likely an error in the source. Mirroring the displayed reference target as-is.",
        ] },
        { displayNumber: 203, id: "fdpm.passive-voice", what: "Stylistic validator flagging passive voice in narrative fields (English)", why: "#39 covers it more generally; standalone is redundant", tier: "C", capabilityKinds: ["cap:validator"], crossReferences: ["fdpm.style-guide"], notes: [] },
      ],
    },

    {
      title: "Transformers",
      primaryCapabilityKinds: ["cap:transformer"],
      entries: [
        { displayNumber: 41, id: "fdpm.spec-to-tests", what: "Generate skeleton plan:Task + plan:AcceptanceCriterion from fs:Requirement primitives", why: "Bridges spec-authoring to planning; one-shot lift kicks off implementation", tier: "S", capabilityKinds: ["cap:transformer"], crossReferences: [], notes: [] },
        { displayNumber: 42, id: "fdpm.adr-from-decisions", what: "sw:Decision → standalone ADR markdown files (one per decision) with cross-references", why: "The ADR-as-files workflow many teams want", tier: "S", capabilityKinds: ["cap:transformer"], crossReferences: [], notes: [] },
        { displayNumber: 43, id: "fdpm.decisions-from-prs", what: 'GitHub PRs that contain "Decision:" sections → sw:Decision primitives', why: "Capture decisions from where they actually happen", tier: "A", capabilityKinds: ["cap:transformer"], crossReferences: [], notes: [] },
        { displayNumber: 204, id: "fdpm.requirements-to-bdd", what: "fs:Requirement → Cucumber/Gherkin .feature files", why: "BDD-shop equivalent of #41", tier: "A", capabilityKinds: ["cap:transformer"], crossReferences: ["fdpm.spec-to-tests"], notes: [] },
        { displayNumber: 205, id: "fdpm.spec-to-openapi-stub", what: "sw:Endpoint + fs:Schema → OpenAPI 3.1 stub", why: "One-shot synthesis distinct from the round-trip in #27", tier: "A", capabilityKinds: ["cap:transformer"], crossReferences: ["fdpm.openapi-export"], notes: [] },
        { displayNumber: 206, id: "fdpm.spec-to-graphql-sdl", what: "typed primitives → GraphQL SDL", why: "One-shot synthesis distinct from #143", tier: "A", capabilityKinds: ["cap:transformer"], crossReferences: ["fdpm.graphql-sdl-export"], notes: [] },
        { displayNumber: 207, id: "fdpm.spec-to-protobuf", what: "typed primitives → .proto", why: "Counterpart to #28", tier: "A", capabilityKinds: ["cap:transformer"], crossReferences: ["fdpm.protobuf-import"], notes: [] },
        { displayNumber: 208, id: "fdpm.spec-to-json-schema", what: "fs:Schema → JSON Schema files (one per primitive type)", why: "Counterpart to #29 with one-shot semantics", tier: "S", capabilityKinds: ["cap:transformer"], crossReferences: ["fdpm.json-schema-roundtrip"], notes: [] },
        { displayNumber: 209, id: "fdpm.spec-to-typescript", what: "fs:Schema → TypeScript types", why: "High-leverage developer ergonomics", tier: "S", capabilityKinds: ["cap:transformer"], crossReferences: [], notes: [] },
        { displayNumber: 210, id: "fdpm.spec-to-pydantic", what: "fs:Schema → Pydantic v2 models", why: "Python equivalent of #209", tier: "A", capabilityKinds: ["cap:transformer"], crossReferences: ["fdpm.spec-to-typescript"], notes: [] },
        { displayNumber: 211, id: "fdpm.spec-to-rust-serde", what: "fs:Schema → Rust serde structs", why: "Rust equivalent of #209", tier: "A", capabilityKinds: ["cap:transformer"], crossReferences: ["fdpm.spec-to-typescript"], notes: [] },
        { displayNumber: 212, id: "fdpm.spec-to-go-types", what: "fs:Schema → Go structs + JSON tags", why: "Go equivalent of #209", tier: "A", capabilityKinds: ["cap:transformer"], crossReferences: ["fdpm.spec-to-typescript"], notes: [] },
        { displayNumber: 213, id: "fdpm.decisions-to-changelog", what: "sw:Decision (with release tag) → CHANGELOG.md entries", why: 'The "what changed and why" loop; pairs with #42', tier: "A", capabilityKinds: ["cap:transformer"], crossReferences: ["fdpm.adr-from-decisions"], notes: [] },
        { displayNumber: 214, id: "fdpm.decisions-to-release-notes", what: "sw:Decision → release notes per audience", why: "Multi-audience equivalent of #213; pairs with #95", tier: "A", capabilityKinds: ["cap:transformer"], crossReferences: ["fdpm.decisions-to-changelog", "fdpm.release-notes-authoring"], notes: [] },
        { displayNumber: 215, id: "fdpm.risks-to-register", what: "sw:Risk → risk register CSV/markdown table per stakeholder", why: "The audit-ready output most compliance teams want", tier: "A", capabilityKinds: ["cap:transformer"], crossReferences: [], notes: [] },
        { displayNumber: 216, id: "fdpm.phases-to-critical-path", what: "plan:Phase graph → critical-path summary report", why: "Standalone counterpart to #16's render", tier: "A", capabilityKinds: ["cap:transformer"], crossReferences: ["fdpm.gantt-svg"], notes: [] },
        { displayNumber: 217, id: "fdpm.workbook-to-readme", what: "Workbook → README.md skeleton with TOC and primitive index", why: "Cheap onboarding artefact", tier: "A", capabilityKinds: ["cap:transformer"], crossReferences: [], notes: [] },
        { displayNumber: 218, id: "fdpm.workbook-to-onboarding", what: "Workbook → onboarding tour script with reading order", why: "Programmatic counterpart to #50; produces an artefact, not just chat", tier: "A", capabilityKinds: ["cap:transformer"], crossReferences: ["fdpm.workbook-explainer"], notes: [] },
        { displayNumber: 219, id: "fdpm.profile-to-schema", what: "fdpm-profile package → JSON Schema for the profile primitives", why: "Meta-tool useful for plugin authors and IDE tooling", tier: "S", capabilityKinds: ["cap:transformer"], crossReferences: [], notes: [] },
        { displayNumber: 220, id: "fdpm.glossary-to-flashcards", what: "glossary primitives → Anki / Mochi flashcard deck", why: "Niche but cheap; useful for #10 and #69", tier: "C", capabilityKinds: ["cap:transformer"], crossReferences: ["fdpm.curriculum-design", "fdpm.localization-glossary"], notes: [] },
      ],
    },

    {
      title: "Workspace / observability / ops",
      primaryCapabilityKinds: ["cap:lifecycle-hook", "custom"],
      entries: [
        { displayNumber: 44, id: "fdpm.git-snapshot", what: "Lifecycle hook: every successful edit commits a snapshot of the JSONL log to a git repo", why: "Free time-travel via git; no new infrastructure", tier: "S", capabilityKinds: ["cap:lifecycle-hook"], crossReferences: [], notes: [] },
        { displayNumber: 45, id: "fdpm.s3-backup", what: "Periodic backup of the entire workspace to S3 / R2 / B2 with content-hash dedup", why: "Production safety net; small ops team can afford this", tier: "A", capabilityKinds: ["cap:lifecycle-hook"], crossReferences: [], notes: [] },
        { displayNumber: 46, id: "fdpm.metrics-prometheus", what: "Export ops/sec, validation-failure rate, render latency per workbook to Prometheus", why: "Operability story for self-hosted FDPM", tier: "A", capabilityKinds: ["cap:lifecycle-hook"], crossReferences: [], notes: [] },
        { displayNumber: 47, id: "fdpm.audit-siem", what: "Stream the operation log to Splunk/Elastic/Datadog with normalised event schema", why: "Compliance-team requirement once you cross 50 users", tier: "A", capabilityKinds: ["cap:lifecycle-hook"], crossReferences: [], notes: [] },
        { displayNumber: 221, id: "fdpm.opentelemetry-tracing", what: "Emit OTel traces for tool calls + render pipelines", why: "Tracing is the modern observability default; pairs with #46", tier: "A", capabilityKinds: ["cap:lifecycle-hook"], crossReferences: ["fdpm.metrics-prometheus"], notes: [] },
        { displayNumber: 222, id: "fdpm.sentry-errors", what: "Surface validation/render errors to Sentry with primitive-id context", why: "Error reporting where errors actually live", tier: "A", capabilityKinds: ["cap:lifecycle-hook"], crossReferences: [], notes: [] },
        { displayNumber: 223, id: "fdpm.webhook-receiver", what: "Inbound webhook with signature verification → workbook ops", why: "Foundation for any external-integration scenario", tier: "A", capabilityKinds: ["cap:lifecycle-hook"], crossReferences: [], notes: [] },
        { displayNumber: 224, id: "fdpm.webhook-emit", what: "Outbound webhook on operation log events", why: "Counterpart to #223; integrates FDPM into wider event-driven systems", tier: "A", capabilityKinds: ["cap:lifecycle-hook"], crossReferences: ["fdpm.webhook-receiver"], notes: [] },
        { displayNumber: 225, id: "fdpm.kafka-producer", what: "Stream operation log to Kafka topic (Avro/protobuf framed)", why: "Heavier infra than #224; needed at scale", tier: "B", capabilityKinds: ["cap:lifecycle-hook"], crossReferences: ["fdpm.webhook-emit"], notes: [] },
        { displayNumber: 226, id: "fdpm.email-gateway", what: "Inbound email → primitives via parsers; reply-by-email workflows", why: "Real for some teams but generally cumbersome", tier: "B", capabilityKinds: ["cap:lifecycle-hook"], crossReferences: [], notes: [] },
        { displayNumber: 227, id: "fdpm.slack-notifier", what: "Slack webhook notifications + slash commands for common ops", why: "Where most teams already are", tier: "A", capabilityKinds: ["cap:lifecycle-hook"], crossReferences: [], notes: [] },
        { displayNumber: 228, id: "fdpm.teams-notifier", what: "Microsoft Teams equivalent of #227", why: "Subset of #227's value; enterprise audiences", tier: "B", capabilityKinds: ["cap:lifecycle-hook"], crossReferences: ["fdpm.slack-notifier"], notes: [] },
        { displayNumber: 229, id: "fdpm.discord-notifier", what: "Discord notifications", why: "Smaller audience for a workplace-tool plugin", tier: "B", capabilityKinds: ["cap:lifecycle-hook"], crossReferences: [], notes: [] },
        { displayNumber: 230, id: "fdpm.matrix-notifier", what: "Matrix protocol notifications", why: "Niche audience; included for completeness", tier: "C", capabilityKinds: ["cap:lifecycle-hook"], crossReferences: [], notes: [] },
        { displayNumber: 231, id: "fdpm.crdt-sync", what: "CRDT-based multi-user sync layer for concurrent edits", why: "Technical leap; would unlock real-time collab; high cost to build", tier: "S", capabilityKinds: ["cap:lifecycle-hook"], crossReferences: [], notes: [] },
        { displayNumber: 232, id: "fdpm.lock-leases", what: "Soft-lock leases on primitives during long edits to coordinate human + agent", why: "Real concurrency story for human↔agent workflows", tier: "S", capabilityKinds: ["cap:lifecycle-hook"], crossReferences: [], notes: [] },
        { displayNumber: 233, id: "fdpm.read-replica", what: "Read-only replica for query workloads (analytics dashboards on workspace data)", why: "Pairs with #46/#115", tier: "A", capabilityKinds: ["cap:lifecycle-hook"], crossReferences: ["fdpm.metrics-prometheus", "fdpm.kpi-dashboard"], notes: [] },
        { displayNumber: 234, id: "fdpm.workspace-snapshot-restore", what: "First-class snapshot/restore commands beyond the git-snapshot hook", why: "Operator ergonomics; #44 is the data plane, this is the UX", tier: "A", capabilityKinds: ["cap:lifecycle-hook"], crossReferences: ["fdpm.git-snapshot"], notes: [] },
        { displayNumber: 235, id: "fdpm.activity-pub", what: "Federate workbook events as ActivityPub objects", why: "Interesting but no demand to validate", tier: "C", capabilityKinds: ["cap:lifecycle-hook"], crossReferences: [], notes: [] },
        { displayNumber: 236, id: "fdpm.ipfs-publish", what: "Content-address-publish workbook to IPFS", why: "Limited audience; cheap to add", tier: "C", capabilityKinds: ["cap:lifecycle-hook"], crossReferences: [], notes: [] },
      ],
    },

    {
      title: "Agent-shaped",
      primaryCapabilityKinds: ["verb", "prompt"],
      description:
        "Source flags numbering past 250 in this section. PURPOSE.md not directly read; verb/prompt names are extrapolations.",
      entries: [
        { displayNumber: 48, id: "fdpm.standup-prompts", what: "Plugin-shipped prompts: daily/standup, weekly/retro, iteration/triage for the planning profile", why: "Demonstrates the prompts capability surface; agents can run a real meeting cadence", tier: "A", capabilityKinds: ["cap:expr-helper"], crossReferences: [], notes: [
          "Source row tags this as a prompts surface; capabilityKinds defaults to cap:expr-helper as a stand-in because the schema's CapabilityKindSchema does not enumerate verb/prompt as plugin capabilities (those live on SectionKindSchema). Honest mismatch with the source's intent — flagged here.",
        ] },
        { displayNumber: 49, id: "fdpm.spec-review-agent", what: "Verb spec.audit-completeness + prompt spec/review that walks a formal spec and reports gaps", why: 'Closes the loop where the formal-spec profile already encodes "what good looks like"', tier: "S", capabilityKinds: ["cap:expr-helper"], crossReferences: [], notes: [
          "Same caveat as #48 on capabilityKinds.",
        ] },
        { displayNumber: 50, id: "fdpm.workbook-explainer", what: "Verb workbook.explain(focus_id) generating a reading order + summary tailored to one primitive's context window", why: "The cold-agent onboarding case PURPOSE.md names as the falsifiable test", tier: "S", capabilityKinds: ["cap:expr-helper"], crossReferences: [], notes: [
          "Same caveat as #48 on capabilityKinds.",
        ] },
        { displayNumber: 237, id: "fdpm.glossary-builder", what: "Verb glossary.suggest proposing new glossary entries from frequently-used unlinked terms", why: "Closes a real authoring gap; concrete value", tier: "A", capabilityKinds: ["cap:expr-helper"], crossReferences: [], notes: [] },
        { displayNumber: 238, id: "fdpm.glossary-canonicalize", what: "Verb glossary.merge-candidates finding near-duplicate definitions across a workbook", why: "Maintenance burden grows with workbook size; this fights it", tier: "A", capabilityKinds: ["cap:expr-helper"], crossReferences: [], notes: [] },
        { displayNumber: 239, id: "fdpm.open-loop-hunter", what: "Verb workbook.open-loops returning unclosed threads (status=open primitives referenced from elsewhere)", why: "Direct query over typed graph; no LLM strictly needed but useful for ranking", tier: "S", capabilityKinds: ["cap:expr-helper"], crossReferences: [], notes: [] },
        { displayNumber: 240, id: "fdpm.stale-decision-flagger", what: "Verb decision.stale flagging decisions whose stated preconditions appear changed", why: 'High-signal review aid; relies on graph + LLM for the "appears changed" judgement', tier: "A", capabilityKinds: ["cap:expr-helper"], crossReferences: [], notes: [] },
        { displayNumber: 241, id: "fdpm.coherence-checker", what: "Verb workbook.contradictions running cross-claim contradiction checks", why: "Low precision but high value when it hits; explicitly an LLM-aided surface", tier: "A", capabilityKinds: ["cap:expr-helper"], crossReferences: [], notes: [] },
        { displayNumber: 242, id: "fdpm.citation-needed", what: "Verb workbook.citations-needed flagging assertions without sw:Evidence", why: "High-value, FDPM-specific; mostly graph + lightweight classifier", tier: "S", capabilityKinds: ["cap:expr-helper"], crossReferences: [], notes: [] },
        { displayNumber: 243, id: "fdpm.empty-section", what: "Verb workbook.empty-sections flagging declared sections with no content", why: "Cheap; mostly redundant with structural validators", tier: "B", capabilityKinds: ["cap:expr-helper"], crossReferences: [], notes: [] },
        { displayNumber: 244, id: "fdpm.acronym-expander", what: "Verb glossary.acronyms suggesting expansions from corpus", why: "Counterpart to #202 with proactive suggestions", tier: "A", capabilityKinds: ["cap:expr-helper"], crossReferences: ["fdpm.acronym-expand"], notes: [] },
        { displayNumber: 245, id: "fdpm.readability-grader", what: "Verb workbook.readability returning Flesch-Kincaid + per-primitive scores", why: "Useful but largely LLM-free; thin agent case", tier: "B", capabilityKinds: ["cap:expr-helper"], crossReferences: [], notes: [] },
        { displayNumber: 246, id: "fdpm.fmea-brainstormer", what: "Verb risks.fmea-suggest proposing failure modes from existing structure", why: "Pairs with #1/#14/#55; LLM useful for breadth", tier: "A", capabilityKinds: ["cap:expr-helper"], crossReferences: ["fdpm.threat-modeling", "fdpm.medical-protocols", "fdpm.security-incident-response"], notes: [] },
        { displayNumber: 247, id: "fdpm.adversarial-threat-brainstormer", what: "Verb threats.adversarial proposing attack scenarios from #1's mitigation graph", why: "Counterpart to #246 in the security domain", tier: "A", capabilityKinds: ["cap:expr-helper"], crossReferences: ["fdpm.threat-modeling", "fdpm.fmea-brainstormer"], notes: [] },
        { displayNumber: 248, id: "fdpm.persona-explainer", what: "Verb workbook.explain-as(persona) tailoring summaries for a stakeholder", why: "Variant of #50 with audience awareness", tier: "A", capabilityKinds: ["cap:expr-helper"], crossReferences: ["fdpm.workbook-explainer"], notes: [] },
        { displayNumber: 249, id: "fdpm.translation-roundtrip-qa", what: "Verb localization.qa flagging untranslated, fuzzy, or back-translation drift", why: "Pairs with #69/#102; LLM strong fit for back-translation diff", tier: "A", capabilityKinds: ["cap:expr-helper"], crossReferences: ["fdpm.localization-glossary", "fdpm.terminology-management"], notes: [] },
        { displayNumber: 250, id: "fdpm.devils-advocate", what: "Prompt: critique each major claim against strongest known counter-arguments", why: "Useful one-shot; depends entirely on prompt quality", tier: "A", capabilityKinds: ["cap:expr-helper"], crossReferences: [], notes: [] },
        { displayNumber: 251, id: "fdpm.pre-mortem", what: "Prompt: imagine workbook objective failed; brainstorm causes, surface as new sw:Risk drafts", why: "Classic technique mapped onto FDPM primitives", tier: "A", capabilityKinds: ["cap:expr-helper"], crossReferences: [], notes: [] },
        { displayNumber: 252, id: "fdpm.executive-summary", what: "Verb workbook.executive-summary generating a one-page summary for a chosen audience", why: "Audience-tailored short-form; complements #248", tier: "A", capabilityKinds: ["cap:expr-helper"], crossReferences: ["fdpm.persona-explainer"], notes: [] },
        { displayNumber: 253, id: "fdpm.daily-journal", what: "Prompt: lightweight daily entry with retro on yesterday's commits to workbook", why: "Too informal to live in the runtime; better as user-config", tier: "C", capabilityKinds: ["cap:expr-helper"], crossReferences: [], notes: [] },
      ],
    },

    {
      title: "Templates",
      primaryCapabilityKinds: ["cap:template"],
      description:
        "Original 50 had zero template entries. Section is net-new fill against a real gap.",
      entries: [
        { displayNumber: 254, id: "fdpm.adr-templates", what: "ADR variants: MADR, Y-Statement, Nygard", why: "Most teams pick one and never look back; bundling all three avoids template debate", tier: "S", capabilityKinds: ["cap:template"], crossReferences: [], notes: [] },
        { displayNumber: 255, id: "fdpm.rfc-templates", what: "Internal RFC / IETF-style RFC templates", why: "Pairs with #15; gives organisations a starting structure", tier: "A", capabilityKinds: ["cap:template"], crossReferences: ["fdpm.architecture-decisions"], notes: [] },
        { displayNumber: 256, id: "fdpm.prfaq-template", what: "Amazon-style PR-FAQ template (working backwards)", why: "Specific, well-known artefact; pairs with #8", tier: "A", capabilityKinds: ["cap:template"], crossReferences: ["fdpm.product-discovery"], notes: [] },
        { displayNumber: 257, id: "fdpm.lean-canvas-template", what: "Lean Canvas / Business Model Canvas / Wardley Map starter", why: "Strategy artefacts; mostly interchangeable with regular doc", tier: "B", capabilityKinds: ["cap:template"], crossReferences: [], notes: [] },
        { displayNumber: 258, id: "fdpm.c4-templates", what: "C4 model context/container/component skeleton", why: "Pairs with #15; well-defined methodology", tier: "A", capabilityKinds: ["cap:template"], crossReferences: ["fdpm.architecture-decisions"], notes: [] },
        { displayNumber: 259, id: "fdpm.arc42-template", what: "arc42 architecture documentation skeleton", why: "Big in DACH market; structured methodology", tier: "A", capabilityKinds: ["cap:template"], crossReferences: [], notes: [] },
        { displayNumber: 260, id: "fdpm.5-whys-template", what: "5 Whys + Fishbone root-cause templates", why: "Pairs with #91; simple but conventional", tier: "B", capabilityKinds: ["cap:template"], crossReferences: ["fdpm.postmortem-library"], notes: [] },
        { displayNumber: 261, id: "fdpm.user-story-template", what: "User story / job story / BDD scenario boilerplate", why: "Pairs with #8/#41/#204", tier: "A", capabilityKinds: ["cap:template"], crossReferences: ["fdpm.product-discovery", "fdpm.spec-to-tests", "fdpm.requirements-to-bdd"], notes: [] },
        { displayNumber: 262, id: "fdpm.test-plan-template", what: "Test plan + test report templates", why: "Pairs with #78", tier: "A", capabilityKinds: ["cap:template"], crossReferences: ["fdpm.test-strategy"], notes: [] },
      ],
    },

    {
      title: "Assets",
      primaryCapabilityKinds: ["cap:asset"],
      description:
        "Original 50 had zero asset entries. Same caveat as templates.",
      entries: [
        { displayNumber: 263, id: "fdpm.icon-library-tabler", what: "Tabler icon set bundled as asset, with primitive-type → glyph mapping", why: "Renderer outputs need consistent iconography; license-clean", tier: "A", capabilityKinds: ["cap:asset"], crossReferences: [], notes: [] },
        { displayNumber: 264, id: "fdpm.diagram-theme", what: "Consistent theme tokens (colours, typography, spacing) across all renderer outputs", why: "Cross-renderer visual consistency is real value across #16-#19, #133-#138", tier: "S", capabilityKinds: ["cap:asset"], crossReferences: [], notes: [] },
        { displayNumber: 265, id: "fdpm.latex-classes", what: "IEEE/ACM/Springer LNCS/Elsevier .cls files for #21 latex-paper", why: "Concrete output dependency for #7's audience", tier: "A", capabilityKinds: ["cap:asset"], crossReferences: ["fdpm.latex-paper", "fdpm.research-papers"], notes: [] },
        { displayNumber: 266, id: "fdpm.fonts-bundle", what: "License-clean web-fonts bundle (typefaces + metadata)", why: "Cheap to produce; liability-reducing for orgs with strict licensing", tier: "B", capabilityKinds: ["cap:asset"], crossReferences: [], notes: [] },
        { displayNumber: 267, id: "fdpm.bpmn-shape-kit", what: "SVG shape kit for BPMN/C4/ArchiMate elements used by #133-#136", why: "Underlies multiple renderers; no point duplicating shapes per renderer", tier: "A", capabilityKinds: ["cap:asset"], crossReferences: ["fdpm.plantuml", "fdpm.archimate"], notes: [] },
      ],
    },
  ],

  numberingReconciliation: {
    note:
      "Section 7 ran one row long against the source's plan, so the file uses IDs 1–267 even though the entry count is claimed to be 250. Rows actually present total 267, not 250.",
    displayedNumberMin: 1,
    displayedNumberMax: 267,
    actualEntryCount: 267,
    sectionCounts: [
      { sectionTitle: "Domain profiles", count: 80 },
      { sectionTitle: "Renderers", count: 36 },
      { sectionTitle: "Importers / Exporters", count: 52 },
      { sectionTitle: "Validators / expr helpers", count: 25 },
      { sectionTitle: "Transformers", count: 20 },
      { sectionTitle: "Workspace / observability / ops", count: 20 },
      { sectionTitle: "Agent-shaped", count: 20 },
      { sectionTitle: "Templates", count: 9 },
      { sectionTitle: "Assets", count: 5 },
    ],
  },

  deliberateOmissions: {
    introduction:
      "Reproducing the original list, with deltas; plus net-new omissions surfaced by the expansion.",
    omissions: [
      {
        category: "Generic AI assistant plugins that wrap an LLM call with no FDPM-specific contract",
        decision: "excluded",
        rationale:
          "Section 7 entries earn their place by binding to typed primitives or graph queries; bare wrappers fail the existence bar.",
        examples: [],
      },
      {
        category: "Niche markup languages without specific demand",
        decision: "included_low_tier",
        rationale:
          "Org-mode, AsciiDoc, DocBook, TEI, DITA were included as low-tier (B/C) entries because small but real audiences exist. Demoted, not excluded.",
        examples: ["fdpm.org-mode", "fdpm.asciidoc", "fdpm.docbook-xml", "fdpm.tei-xml", "fdpm.dita-xml"],
      },
      {
        category: "Domain profiles that cannot be grounded in evidence",
        decision: "excluded",
        rationale:
          "Fitness training and tabletop RPG campaigns remain excluded — the original's reasoning holds. Declined to reintroduce just to hit 250.",
        examples: ["fitness training", "tabletop RPG campaigns"],
      },
      {
        category: "One-off interchangeable adapters",
        decision: "included_low_tier",
        rationale:
          "JSON Feed (#141) is included as a C-tier counterpart to RSS/Atom (#140) precisely to mark the cliff.",
        examples: ["fdpm.json-feed"],
      },
      {
        category: "Per-vendor cloud-provider profiles",
        decision: "excluded",
        rationale:
          'Neither portable nor differentiated; better served by #64 with a per-vendor template.',
        examples: ["AWS architecture", "GCP architecture"],
      },
      {
        category: "Per-language style guides",
        decision: "excluded",
        rationale: "Better served by #39 with a parameter set.",
        examples: ["Google Java style"],
      },
      {
        category: 'Generic "AI [domain] assistant" wrappers',
        decision: "excluded",
        rationale: "Excluded by the original's rule and reaffirmed.",
        examples: [],
      },
    ],
  },

  maintainerRecommendation: {
    body:
      "If I were the maintainer, I would not treat the 250 as a backlog. I would promote S-tier to a first-party plugins track, treat A-tier as community-build territory, park B-tier pending real users, and use C-tier only as a calibration aid.",
    actions: [
      {
        action: 'Promote S-tier (49 entries) to a "first-party plugins" track.',
        rationale: "These have clear differentiator stories. They earn limited core-team investment.",
        targetTiers: ["S"],
        targetCapabilities: [],
      },
      {
        action: "Treat A-tier (142 entries) as community-build territory.",
        rationale:
          "Publish the 11-capability contract clearly enough that motivated contributors can land them; don't spend core-team time.",
        targetTiers: ["A"],
        targetCapabilities: [],
      },
      {
        action: 'Park B-tier (41 entries) as "if a real user shows up, we\'ll reconsider."',
        rationale: "Most will never be built, and that's fine.",
        targetTiers: ["B"],
        targetCapabilities: [],
      },
      {
        action: "Use C-tier (18 entries) only as a calibration aid when discussing scope.",
        rationale: "They're explicitly not the goal.",
        targetTiers: ["C"],
        targetCapabilities: [],
      },
      {
        action: "Decide on cap:template and cap:asset.",
        rationale:
          "Either both deserve a real curated bundle (one theme, a few key templates) or the capability surface should be removed from the contract. Carrying capability kinds with no first-party examples invites confusion.",
        targetTiers: [],
        targetCapabilities: ["cap:template", "cap:asset"],
      },
    ],
    highestLeverageAction: {
      title: "Plugin contract conformance test",
      description:
        "Write a one-page plugin contract conformance test that any S-tier candidate must pass before shipping. Filters the list to what's genuinely shippable, and turns \"earns its existence\" from a subjective bar into a falsifiable one.",
    },
  },
};

/**
 * Validate the instance against the schema. Expected to surface real
 * defects that exist in the source markdown (declared 250 vs actual 267,
 * tier-distribution mismatch, section count mismatches) — that is the
 * intended behavior of the schema, not a defect of this instance.
 *
 * Run with: node --experimental-strip-types docs/drafts/plugins.instance.ts
 */
export const fdpm250RegistryValidation =
  FdpmPluginIdeasRegistrySchema.safeParse(fdpm250Registry);
