/**
 * `kc:CitationIndexRenderer` — the verification surface, as a page a reviewer
 * can check.
 *
 * The cartridge renderer prints the claims. This one prints the evidence for
 * them, inverted: source by source, every claim that rests on it with its
 * ordinal. That inversion is the point. Reading down a cartridge you can only
 * ask "is this claim cited"; reading down this page you can ask "does this
 * source actually say all of that", which is the question that catches a
 * fabricated ordinal.
 *
 * It also prints the Pass-6 scoreboard, including the three checks the
 * validator layer cannot make. A page that showed only the checks that passed
 * would be the self-certification the protocol warns about.
 */
import type { RendererInput, RendererOutput } from "../../../src/plugin/types.js";
import { KC_UNENFORCEABLE_CHECKS } from "../validators.js";
import { buildModel, fieldOf, numberOf, type Citation } from "./_model.js";

function esc(s: string): string {
  return s
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;");
}

interface CheckRow {
  label: string;
  verdict: "pass" | "fail" | "unchecked";
  detail: string;
}

export function renderCitationIndex(input: RendererInput): RendererOutput {
  const m = buildModel(input.primitives, input.relations);
  const c = m.cartridge;
  const title = c ? fieldOf(c, "cartridge_id") : "cartridge";

  const diagnostics = m.layers.find((l) => l.label.startsWith("L4"))?.items.length ?? 0;
  const overrides = m.layers.find((l) => l.label.startsWith("L5"))?.items.length ?? 0;
  const rate = m.harvest.discardRate;

  const checks: CheckRow[] = [
    {
      label: "Every normative claim carries KEY:ordinal",
      verdict: m.uncited.length === 0 ? "pass" : "fail",
      detail: m.uncited.length === 0 ? "no uncited claims" : `${m.uncited.length} uncited: ${m.uncited.map((u) => u.id).join(", ")}`,
    },
    {
      label: "Discard rate >= 50%",
      verdict: rate === null ? "unchecked" : rate >= 0.5 ? "pass" : "fail",
      detail:
        rate === null
          ? "no harvest rows recorded"
          : `${(rate * 100).toFixed(0)}% (${m.harvest.discarded} of ${m.harvest.total})`,
    },
    {
      label: "L4 has >= 8 rows",
      verdict: diagnostics >= 8 ? "pass" : "fail",
      detail: `${diagnostics} diagnostics`,
    },
    {
      label: "L5 exists and is non-empty",
      verdict: overrides > 0 ? "pass" : "fail",
      detail: `${overrides} overrides`,
    },
    {
      label: "Exclusions list is non-empty",
      verdict: m.excluded.length > 0 ? "pass" : "fail",
      detail: `${m.excluded.length} exclusions`,
    },
    {
      label: "Declared gaps present",
      verdict: m.gaps.length > 0 ? "pass" : "unchecked",
      detail: `${m.gaps.length} gaps declared`,
    },
    ...KC_UNENFORCEABLE_CHECKS.map(
      (k): CheckRow => ({ label: k.check, verdict: "unchecked", detail: k.why }),
    ),
  ];

  // Invert: source → the claims resting on it.
  const bySource = new Map<string, Array<{ claimId: string; citation: Citation }>>();
  for (const layer of m.layers) {
    for (const item of layer.items) {
      for (const cit of item.citations) {
        const list = bySource.get(cit.sourceId) ?? [];
        list.push({ claimId: item.instance.id, citation: cit });
        bySource.set(cit.sourceId, list);
      }
    }
  }
  for (const list of bySource.values()) list.sort((a, b) => a.citation.ordinal - b.citation.ordinal);

  const html: string[] = [
    "<!-- generated by kc:CitationIndexRenderer -->",
    `<h1>${esc(title)} — citation index</h1>`,
    "<h2>Pass 6 scoreboard</h2>",
    "<table><thead><tr><th>Check</th><th>Verdict</th><th>Detail</th></tr></thead><tbody>",
    ...checks.map(
      (k) =>
        `<tr class="${k.verdict}"><td>${esc(k.label)}</td><td>${k.verdict.toUpperCase()}</td><td>${esc(
          k.detail,
        )}</td></tr>`,
    ),
    "</tbody></table>",
    "<p><em>UNCHECKED is not PASS. Three of these checks cannot be made from the graph alone; they are listed so a clean scoreboard cannot be mistaken for a complete one.</em></p>",
    "<h2>Evidence by source</h2>",
  ];

  for (const source of m.sources) {
    const claims = bySource.get(source.id) ?? [];
    html.push(
      `<h3><code>${esc(fieldOf(source, "citation_key"))}</code> — ${esc(fieldOf(source, "title"))}` +
        ` <small>(${esc(fieldOf(source, "tier"))} tier, ${numberOf(source, "sentence_count") || "?"} sentences)</small></h3>`,
    );
    if (claims.length === 0) {
      html.push("<p><em>No claim rests on this source. An uncited source is corpus, not evidence.</em></p>");
      continue;
    }
    html.push("<table><thead><tr><th>Ordinal</th><th>Claim</th></tr></thead><tbody>");
    for (const { claimId, citation } of claims) {
      html.push(`<tr><td>${citation.ordinal}</td><td><code>${esc(claimId)}</code></td></tr>`);
    }
    html.push("</tbody></table>");
  }

  if (m.defects.length > 0) {
    html.push("<h2>Corpus defects</h2>", "<ul>");
    for (const d of m.defects) {
      html.push(
        `<li><strong>${esc(fieldOf(d, "kind"))}</strong> (${esc(fieldOf(d, "grade"))}) — ${esc(
          fieldOf(d, "signal"),
        )} <em>Fix: ${esc(fieldOf(d, "fix"))}</em></li>`,
      );
    }
    html.push("</ul>");
  }

  return {
    bytes: new TextEncoder().encode(html.join("\n")),
    contentType: "text/html",
    filename: `${title || "cartridge"}-citations.html`,
  };
}
