import type { ReactNode } from "react";
import type {
  DocField,
  DocPrimitive,
  DocRelation,
  ProfileDocumentModel,
} from "./profileDocument";
import { DOCUMENT_DISCLAIMER, DOCUMENT_GENERATOR } from "./profileDocument";

/**
 * Polished, print-optimized rendering of a profile-reference document.
 *
 * This component is a pure projection of `ProfileDocumentModel` — all logic
 * lives in `profileDocument.ts`. It renders a self-contained "sheet of paper"
 * (`.doc`) that reads as a document on screen (light, centered) and prints
 * cleanly to PDF via the browser print engine (see the `@media print` block
 * in `styles.css`). No app chrome is rendered here.
 */
export function ProfileDocument({ model }: { model: ProfileDocumentModel }) {
  const generated = formatTimestamp(model.generatedAt);
  return (
    <article className="doc" aria-label={`${model.title} profile reference document`}>
      <DocCover model={model} generated={generated} />

      {(model.primitives.length > 0 || model.relations.length > 0) && (
        <nav className="doc-toc" aria-label="Contents">
          <h2>Contents</h2>
          <div className="doc-toc-cols">
            <TocColumn
              heading={`Primitive types (${model.primitives.length})`}
              items={model.primitives.map((p) => ({ id: anchorId("prim", p.id), label: p.name }))}
            />
            <TocColumn
              heading={`Relation types (${model.relations.length})`}
              items={model.relations.map((r) => ({ id: anchorId("rel", r.id), label: r.name }))}
            />
          </div>
        </nav>
      )}

      <section className="doc-section">
        <h2>
          Primitive types <span className="doc-count">{model.primitives.length}</span>
        </h2>
        {model.primitives.length === 0 ? (
          <p className="doc-empty">This profile registers no primitive types directly.</p>
        ) : (
          model.primitives.map((p) => <PrimitiveEntry key={p.id} p={p} />)
        )}
      </section>

      <section className="doc-section">
        <h2>
          Relation types <span className="doc-count">{model.relations.length}</span>
        </h2>
        {model.relations.length === 0 ? (
          <p className="doc-empty">This profile registers no relation types directly.</p>
        ) : (
          model.relations.map((r) => <RelationEntry key={r.id} r={r} />)
        )}
      </section>

      <footer className="doc-footer">
        <p className="doc-footer-provenance">
          Generated by {DOCUMENT_GENERATOR} · {generated} · profile <code>{model.id}</code> v
          {model.version}
        </p>
        <p className="doc-footer-disclaimer">{DOCUMENT_DISCLAIMER}</p>
      </footer>
    </article>
  );
}

function DocCover({
  model,
  generated,
}: {
  model: ProfileDocumentModel;
  generated: string;
}) {
  const t = model.totals;
  return (
    <header className="doc-cover">
      <div className="doc-eyebrow">FDPM Domain Profile · Reference</div>
      <h1 className="doc-title">{model.title}</h1>
      {model.description && <p className="doc-subtitle">{model.description}</p>}
      <dl className="doc-meta">
        <Meta term="Profile id" value={<code>{model.id}</code>} />
        <Meta term="Version" value={model.version} />
        <Meta term="Primitive types" value={String(t.primitiveTypes)} />
        <Meta term="Relation types" value={String(t.relationTypes)} />
        <Meta term="Fields" value={`${t.fields} (${t.requiredFields} required)`} />
        {model.extends.length > 0 && (
          <Meta term="Extends" value={model.extends.map((e) => <code key={e}>{e}</code>)} />
        )}
        <Meta term="Generated" value={generated} />
      </dl>
    </header>
  );
}

function Meta({ term, value }: { term: string; value: ReactNode }) {
  return (
    <div className="doc-meta-row">
      <dt>{term}</dt>
      <dd>{value}</dd>
    </div>
  );
}

function TocColumn({
  heading,
  items,
}: {
  heading: string;
  items: Array<{ id: string; label: string }>;
}) {
  if (items.length === 0) return null;
  return (
    <div className="doc-toc-col">
      <h3>{heading}</h3>
      <ul>
        {items.map((it) => (
          <li key={it.id}>
            <a href={`#${it.id}`}>{it.label}</a>
          </li>
        ))}
      </ul>
    </div>
  );
}

function PrimitiveEntry({ p }: { p: DocPrimitive }) {
  return (
    <section className="doc-entry" id={anchorId("prim", p.id)}>
      <header className="doc-entry-head">
        <h3 className="doc-entry-name">{p.name}</h3>
        <code className="doc-entry-id">{p.id}</code>
        {p.scoped && <span className="doc-badge">scoped</span>}
        {p.category && <span className="doc-tag">{p.category}</span>}
      </header>
      {p.description && <p className="doc-entry-desc">{p.description}</p>}
      {p.idFormat && (
        <p className="doc-idformat">
          <span className="doc-inline-label">id format</span>
          <code>{p.idFormat.pattern}</code>
          <span className="doc-dim">
            {" "}
            ({p.idFormat.patternKind}, {p.idFormat.uniqueness})
          </span>
        </p>
      )}
      <FieldTable fields={p.fields} />
    </section>
  );
}

function RelationEntry({ r }: { r: DocRelation }) {
  return (
    <section className="doc-entry" id={anchorId("rel", r.id)}>
      <header className="doc-entry-head">
        <h3 className="doc-entry-name">{r.name}</h3>
        <code className="doc-entry-id">{r.id}</code>
      </header>
      {r.description && <p className="doc-entry-desc">{r.description}</p>}
      <p className="doc-relation-signature">
        <TypeSet label="source" types={r.sources} />
        <span className="doc-arrow" aria-hidden="true">
          →
        </span>
        <TypeSet label="target" types={r.targets} />
      </p>
      <FieldTable fields={r.fields} />
    </section>
  );
}

function TypeSet({ label, types }: { label: string; types: string[] }) {
  return (
    <span className="doc-typeset">
      <span className="doc-inline-label">{label}</span>
      {types.length === 0 ? (
        <span className="doc-dim">—</span>
      ) : (
        types.map((t) => (
          <code key={t} className={t === "*" ? "doc-any" : undefined}>
            {t === "*" ? "any" : t}
          </code>
        ))
      )}
    </span>
  );
}

function FieldTable({ fields }: { fields: DocField[] }) {
  if (fields.length === 0) return <p className="doc-nofields">No fields.</p>;
  return (
    <table className="doc-fields">
      <thead>
        <tr>
          <th>Field</th>
          <th>Type</th>
          <th>Req.</th>
          <th>Description</th>
        </tr>
      </thead>
      <tbody>
        {fields.map((f) => (
          <tr key={f.name}>
            <td>
              <code>{f.name}</code>
            </td>
            <td className="doc-fieldtype">
              <span className="doc-kind">{f.typeLabel}</span>
              {f.rawType && <span className="doc-dim"> {f.rawType}</span>}
              {f.enumValues && f.enumValues.length > 0 && (
                <div className="doc-enum">
                  {f.enumValues.map((v) => (
                    <code key={v} className="doc-enum-val">
                      {v}
                    </code>
                  ))}
                </div>
              )}
            </td>
            <td className="doc-req">{f.required ? "✔" : ""}</td>
            <td>{f.description ?? ""}</td>
          </tr>
        ))}
      </tbody>
    </table>
  );
}

/** Deterministic, DOM-safe anchor id for an in-document link target. */
function anchorId(prefix: string, typeId: string): string {
  return `doc-${prefix}-${typeId.replace(/[^a-zA-Z0-9]+/g, "-")}`;
}

/** Render an ISO timestamp as a human date; fall back to the raw value. */
function formatTimestamp(iso: string): string {
  const d = new Date(iso);
  if (Number.isNaN(d.getTime())) return iso;
  return d.toLocaleDateString(undefined, { year: "numeric", month: "long", day: "numeric" });
}
