/**
 * `application/x-tex` — the paper as LaTeX source.
 *
 * `acad:PaperPdfRenderer` draws with pdf-lib: Helvetica, no math typesetting,
 * no journal class. That is the right artefact to circulate and the wrong one
 * to submit. This is the submittable form. It hands typesetting to a real TeX
 * engine, and in doing so it is the only renderer that can set the profile's
 * equations properly — `acad:Equation.tex` already holds TeX, which every
 * other view can only print as a literal string.
 *
 * It pairs with `acad:BibliographyRenderer`: this file emits `\cite{key}` and
 * `\bibliography{...}`, that one emits the `.bib`. The failure mode of that
 * pairing is quiet — a key absent from the bibliography sets a bold `[?]`
 * rather than raising — so both derive their keys from `citationKeys` in
 * `bibliography.ts` rather than reimplementing the convention twice.
 */

import type { RendererInput, RendererOutput } from "../../../src/plugin/types.js";
import { buildPaperModel } from "./paper_document.js";
import { citationKeys, escapeTex } from "./bibliography.js";

interface Prim {
  id: string;
  type_id: string;
  field_values: Record<string, unknown>;
}

const str = (p: Prim | undefined, k: string): string => {
  const v = p?.field_values?.[k];
  return typeof v === "string" ? v : v === undefined || v === null ? "" : String(v);
};
const arr = (p: Prim | undefined, k: string): string[] => {
  const v = p?.field_values?.[k];
  return Array.isArray(v) ? v.map(String).filter(Boolean) : [];
};

/** A LaTeX label that is stable and free of characters TeX treats as syntax. */
const labelOf = (prefix: string, id: string): string =>
  `${prefix}:${id.replace(/[^A-Za-z0-9]+/g, "-").replace(/^-+|-+$/g, "")}`;

export function renderPaperLatex(input: RendererInput): RendererOutput {
  const model = buildPaperModel(input.primitives as never, input.relations as never);
  const prims = input.primitives as unknown as Prim[];
  const paper = model.paper as unknown as Prim | undefined;

  const keys = citationKeys(model.works as never);

  /* Which citations attach to which passage, so `\cite` lands on the claim,
     finding or section that does the citing rather than in a lump at the end. */
  const citesFor = new Map<string, string[]>();
  for (const c of model.citations) {
    if (c.citing === undefined || c.work === undefined) continue;
    const key = keys.get((c.work as unknown as Prim).id);
    if (key === undefined) continue;
    const id = (c.citing as unknown as Prim).id;
    citesFor.set(id, [...(citesFor.get(id) ?? []), key]);
  }
  const citeSuffix = (id: string): string => {
    const list = citesFor.get(id);
    return list === undefined || list.length === 0 ? "" : ` \\cite{${[...new Set(list)].join(",")}}`;
  };

  const L: string[] = [];
  const title = str(paper, "title") || input.workbookId;

  L.push(
    "% Generated by acad:LatexRenderer from " + escapeTex(input.workbookId) + ".",
    "% Compile with: pdflatex && bibtex && pdflatex twice.",
    "\\documentclass[11pt,a4paper]{article}",
    "\\usepackage[utf8]{inputenc}",
    "\\usepackage[T1]{fontenc}",
    "\\usepackage{amsmath,amssymb}",
    "\\usepackage{graphicx}",
    "\\usepackage{booktabs}",
    "\\usepackage[hidelinks]{hyperref}",
    "",
    `\\title{${escapeTex(title)}}`,
  );

  const byline = model.authors
    .map((a) => {
      const author = a as unknown as Prim;
      const name = escapeTex(str(author, "fullName"));
      const affs = model.affiliationOf.get(author.id) ?? [];
      return affs.length > 0 ? `${name}\\thanks{${escapeTex(affs.join("; "))}}` : name;
    })
    .filter(Boolean);
  L.push(`\\author{${byline.length > 0 ? byline.join(" \\and ") : "\\,"}}`);

  const date = str(paper, "publicationDate") || str(paper, "year");
  L.push(date ? `\\date{${escapeTex(date)}}` : "\\date{}", "", "\\begin{document}", "\\maketitle", "");

  const abstract = str(paper, "abstract");
  if (abstract) {
    L.push("\\begin{abstract}", escapeTex(abstract), "\\end{abstract}", "");
  }

  const sectionCommand = (depth: number): string =>
    depth <= 0 ? "section" : depth === 1 ? "subsection" : "subsubsection";

  const emitApparatus = (sectionId: string): void => {
    for (const q of model.quotationsBySection.get(sectionId) ?? []) {
      const quote = q as unknown as Prim;
      const locator = str(quote, "locator");
      L.push(
        "\\begin{quote}",
        `${escapeTex(str(quote, "body"))}${locator ? ` (${escapeTex(locator)})` : ""}`,
        "\\end{quote}",
        "",
      );
    }
    for (const e of model.equationsBySection.get(sectionId) ?? []) {
      const eq = e as unknown as Prim;
      const tex = str(eq, "tex");
      if (!tex) continue;
      /* The one place the profile's own TeX is used as TeX. Deliberately not
         escaped: escaping it here would typeset the source instead of the
         equation, which is the entire point of this renderer. */
      L.push(
        "\\begin{equation}",
        `\\label{${labelOf("eq", eq.id)}}`,
        tex,
        "\\end{equation}",
        "",
      );
    }
    for (const f of model.figuresBySection.get(sectionId) ?? []) {
      const fig = f as unknown as Prim;
      L.push(
        "\\begin{figure}[htbp]",
        "\\centering",
        str(fig, "imageRef")
          ? `\\includegraphics[width=\\linewidth]{${escapeTex(str(fig, "imageRef"))}}`
          : "% no imageRef recorded for this figure",
        `\\caption{${escapeTex(str(fig, "caption"))}}`,
        `\\label{${labelOf("fig", fig.id)}}`,
        "\\end{figure}",
        "",
      );
    }
    for (const t of model.tablesBySection.get(sectionId) ?? []) {
      const tab = t as unknown as Prim;
      L.push(
        "\\begin{table}[htbp]",
        "\\centering",
        `\\caption{${escapeTex(str(tab, "caption"))}}`,
        `\\label{${labelOf("tab", tab.id)}}`,
        str(tab, "contentRef")
          ? `% content: ${escapeTex(str(tab, "contentRef"))}`
          : "% no contentRef recorded for this table",
        "\\end{table}",
        "",
      );
    }
  };

  const emitClaim = (c: Prim): void => {
    const kind = str(c, "kind") || "claim";
    L.push(
      `\\paragraph{${escapeTex(kind.charAt(0).toUpperCase() + kind.slice(1))}.} ${escapeTex(str(c, "statement"))}${citeSuffix(c.id)}`,
      "",
    );
    const evidence = model.evidenceFor.get(c.id) ?? [];
    if (evidence.length === 0) {
      L.push("% No evidence is recorded for the claim above.", "");
    }
    for (const e of evidence) {
      const ev = e as unknown as Prim;
      L.push(
        `\\begin{quote}\\small ${escapeTex(str(ev, "kind") || "evidence")}: ${escapeTex(str(ev, "summary"))}${citeSuffix(ev.id)}\\end{quote}`,
        "",
      );
    }
  };

  for (const s of model.sections) {
    const section = s as unknown as Prim;
    const cmd = sectionCommand(model.depthOf.get(section.id) ?? 0);
    L.push(`\\${cmd}{${escapeTex(str(section, "title"))}}`, `\\label{${labelOf("sec", section.id)}}`, "");
    const body = str(section, "bodyText");
    for (const para of body.split(/\n\s*\n/).map((x) => x.trim()).filter(Boolean)) {
      L.push(`${escapeTex(para)}${citeSuffix(section.id)}`, "");
    }
    for (const c of model.claimsBySection.get(section.id) ?? []) emitClaim(c as unknown as Prim);
    emitApparatus(section.id);
  }

  const unplaced = model.claimsBySection.get("") ?? [];
  if (unplaced.length > 0) {
    L.push("\\section{Claims not placed in a section}", "");
    for (const c of unplaced) emitClaim(c as unknown as Prim);
  }
  emitApparatus("");

  const simpleList = (heading: string, items: readonly unknown[], line: (p: Prim) => string): void => {
    if (items.length === 0) return;
    L.push(`\\section{${escapeTex(heading)}}`, "\\begin{itemize}");
    for (const item of items) L.push(`\\item ${line(item as Prim)}`);
    L.push("\\end{itemize}", "");
  };

  simpleList("Findings", model.findings, (f) => `${escapeTex(str(f, "statement"))}${citeSuffix(f.id)}`);
  simpleList("Limitations", model.limitations, (l) => escapeTex(str(l, "statement")));
  simpleList(
    "Methods",
    model.methods,
    (m) => `\\textbf{${escapeTex(str(m, "name"))}} ${escapeTex(str(m, "procedure"))}`,
  );

  const funding = prims.filter((p) => p.type_id === "acad:Funding");
  if (funding.length > 0) {
    L.push("\\section*{Funding}", "");
    for (const f of funding) L.push(escapeTex(str(f, "statement") || str(f, "grantNumber") || f.id), "");
  }

  /* `\bibliography` takes the .bib basename without its extension, and the
     sibling renderer is what produces that file. */
  if (model.works.length > 0) {
    L.push("\\bibliographystyle{plain}", `\\bibliography{${input.workbookId}}`, "");
  }

  L.push("\\end{document}", "");

  return {
    bytes: new TextEncoder().encode(L.join("\n")),
    contentType: "application/x-tex",
    filename: `${input.workbookId}.tex`,
  };
}
