#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
fdpm_to_latex.py
================

Render an FDPM academic-paper instance (JSON, profile:academic-paper:0.3)
into a self-contained LaTeX document.

DISCLAIMER
----------
This tool is *strictly mechanical*. It transcribes the contents of the
instance file into LaTeX. It does NOT validate the truth of any claim
in the instance. A statement that is faithfully rendered may still be
incorrect, unsupported, or hallucinated at the level of the instance
itself. Any text in the output that is not backed by a corresponding
field in the JSON is either an explicit placeholder ("[missing: ...]")
or a clearly-marked structural label generated by this renderer.

The script emits no invented content. Missing fields become visible
placeholders so that gaps in the instance are auditable in the rendered
document.

USAGE
-----
    python fdpm_to_latex.py INSTANCE.json [-o OUTPUT.tex]
                                          [--engine ENGINE]
                                          [--no-appendix] [--toc]
                                          [--bib FILE.bib]
                                          [--pdf [--pdf-passes N] [--keep-aux]]

ENGINES
-------
    lualatex (default) — recommended; native UTF-8, Greek and script F
                         characters render without configuration.
    xelatex            — equivalent for our purposes.
    pdflatex           — supported; a Unicode-substitution preamble is
                         emitted to cover the symbols observed in the
                         reference instances. Coverage is best-effort.

When ``--pdf`` is given the selected engine is invoked on the produced
``.tex`` in its directory; cross-references are resolved by running the
engine twice (``--pdf-passes`` controls this). Auxiliary files (.aux,
.log, .out, .toc, ...) are deleted on success unless ``--keep-aux``.

EXIT CODES
----------
    0 — success
    1 — usage error / file not found / invalid JSON
    2 — schema mismatch (no `primitives` / no `Paper` primitive)
    4 — PDF compilation failed (LaTeX engine reported an error)
"""

from __future__ import annotations

import argparse
import json
import re
import shutil
import subprocess
import sys
from collections import defaultdict
from dataclasses import dataclass, field
from pathlib import Path
from typing import Any, Iterable

# ---------------------------------------------------------------------------
# Workbook: load + index the FDPM JSON
# ---------------------------------------------------------------------------


@dataclass
class Workbook:
    """Indexed view of an FDPM instance.

    Attributes:
        raw:               original JSON dict
        primitives:        qualified_id -> primitive
        relations:         qualified_id -> relation
        by_kind:           kind -> [qualified_ids]   (primitives)
        rel_by_kind:       kind -> [qualified_ids]   (relations)
        local_to_qualified: field_values.id -> qualified_id
        outgoing:          (source_qid, rel_kind) -> [target_qids]
        incoming:          (target_qid, rel_kind) -> [source_qids]
    """

    raw: dict[str, Any]
    primitives: dict[str, dict] = field(default_factory=dict)
    relations: dict[str, dict] = field(default_factory=dict)
    by_kind: dict[str, list[str]] = field(default_factory=lambda: defaultdict(list))
    rel_by_kind: dict[str, list[str]] = field(default_factory=lambda: defaultdict(list))
    local_to_qualified: dict[str, str] = field(default_factory=dict)
    outgoing: dict[tuple[str, str], list[str]] = field(
        default_factory=lambda: defaultdict(list)
    )
    incoming: dict[tuple[str, str], list[str]] = field(
        default_factory=lambda: defaultdict(list)
    )

    # -- loading ----------------------------------------------------------

    @classmethod
    def load(cls, path: Path) -> "Workbook":
        with path.open(encoding="utf-8") as f:
            data = json.load(f)
        if not isinstance(data, dict) or "primitives" not in data:
            raise SchemaError(
                f"{path}: top-level key 'primitives' missing; not an FDPM instance."
            )
        wb = cls(raw=data)
        for pid, prim in (data.get("primitives") or {}).items():
            wb.primitives[pid] = prim
            kind = pid.split(":")[1] if pid.startswith("acad:") and ":" in pid[5:] else "Other"
            wb.by_kind[kind].append(pid)
            fv = prim.get("field_values") or {}
            local = fv.get("id")
            if local:
                # If two primitives claim the same local id, keep the first
                # and note the collision via stderr.
                if local in wb.local_to_qualified and wb.local_to_qualified[local] != pid:
                    print(
                        f"[warn] duplicate field_values.id {local!r} "
                        f"({wb.local_to_qualified[local]} and {pid})",
                        file=sys.stderr,
                    )
                else:
                    wb.local_to_qualified[local] = pid
        for rid, rel in (data.get("relations") or {}).items():
            wb.relations[rid] = rel
            kind = rid.split(":")[1] if rid.startswith("acad:") and ":" in rid[5:] else "Other"
            wb.rel_by_kind[kind].append(rid)
            s, t = rel.get("source_id"), rel.get("target_id")
            if s and t:
                wb.outgoing[(s, kind)].append(t)
                wb.incoming[(t, kind)].append(s)
        return wb

    # -- lookups ----------------------------------------------------------

    def resolve(self, ref: str | None) -> dict | None:
        """Resolve a primitive by either its qualified or local id."""
        if not ref:
            return None
        if ref in self.primitives:
            return self.primitives[ref]
        qid = self.local_to_qualified.get(ref)
        return self.primitives.get(qid) if qid else None

    def out(self, source_qid: str, rel_kind: str) -> list[str]:
        return self.outgoing.get((source_qid, rel_kind), [])

    def inc(self, target_qid: str, rel_kind: str) -> list[str]:
        return self.incoming.get((target_qid, rel_kind), [])

    # -- structural queries ----------------------------------------------

    def paper_qid(self) -> str | None:
        papers = self.by_kind.get("Paper") or []
        return papers[0] if papers else None

    def section_depth(self, section_qid: str) -> int:
        """Depth = number of SectionParent hops from this section to a root."""
        cur = section_qid
        seen = {cur}
        depth = 0
        while True:
            parents = self.out(cur, "SectionParent")
            if not parents:
                return depth
            parent = parents[0]
            if parent in seen:
                return depth  # cycle guard
            seen.add(parent)
            cur = parent
            depth += 1


class SchemaError(Exception):
    pass


# ---------------------------------------------------------------------------
# Text utilities: LaTeX escaping
# ---------------------------------------------------------------------------

# Order matters: backslash first via a sentinel, then the rest.
_TEX_ESCAPES = {
    "\\": r"\textbackslash{}",
    "{": r"\{",
    "}": r"\}",
    "$": r"\$",
    "&": r"\&",
    "#": r"\#",
    "%": r"\%",
    "_": r"\_",
    "^": r"\textasciicircum{}",
    "~": r"\textasciitilde{}",
}
_TEX_ESCAPE_RE = re.compile("|".join(re.escape(k) for k in _TEX_ESCAPES))


def tex_escape(s: str | None) -> str:
    """Escape special LaTeX characters in `s` (text mode)."""
    if s is None:
        return ""
    return _TEX_ESCAPE_RE.sub(lambda m: _TEX_ESCAPES[m.group(0)], str(s))


def safe_label(s: str) -> str:
    """Turn an FDPM identifier into a LaTeX label (no colons, no spaces)."""
    return re.sub(r"[^A-Za-z0-9\-]", "-", s)


# Unicode → LaTeX substitution map, applied for ALL engines.
# Math symbols are always wrapped in inline math ($...$) so that they
# render via the math font regardless of whether the body font carries
# the glyph. Keys are characters observed in the two reference instances;
# coverage is best-effort. Accented Latin letters (é, ü, à, ě, ł, î, ý)
# are intentionally absent: they pass through cleanly with [utf8]inputenc
# + [T1]fontenc (pdflatex) and natively with lualatex/xelatex.
_PDFLATEX_UNICODE_MAP: list[tuple[str, str]] = [
    # Greek — math-mode (works in both pdflatex and lualatex/xelatex)
    ("Ω", r"$\Omega$"), ("Σ", r"$\Sigma$"), ("Π", r"$\Pi$"),
    ("τ", r"$\tau$"),   ("χ", r"$\chi$"),   ("α", r"$\alpha$"),
    ("ω", r"$\omega$"), ("β", r"$\beta$"),  ("γ", r"$\gamma$"),
    ("δ", r"$\delta$"), ("ε", r"$\epsilon$"),
    ("μ", r"$\mu$"),    ("π", r"$\pi$"),    ("σ", r"$\sigma$"),
    ("θ", r"$\theta$"), ("λ", r"$\lambda$"),
    ("κ", r"$\kappa$"),
    # Calligraphic / blackboard letters — inline math
    ("𝓕", r"$\mathcal{F}$"), ("𝒮", r"$\mathcal{S}$"), ("𝒞", r"$\mathcal{C}$"),
    ("ℝ", r"$\mathbb{R}$"),  ("ℕ", r"$\mathbb{N}$"),
    ("ℤ", r"$\mathbb{Z}$"),  ("ℚ", r"$\mathbb{Q}$"),
    # Arrows and operators (inline-math)
    ("→", r"$\rightarrow$"), ("←", r"$\leftarrow$"),
    ("↔", r"$\leftrightarrow$"), ("⇒", r"$\Rightarrow$"),
    ("×", r"$\times$"), ("·", r"$\cdot$"),
    ("∑", r"$\sum$"), ("∏", r"$\prod$"), ("⋃", r"$\bigcup$"), ("⋂", r"$\bigcap$"),
    ("∪", r"$\cup$"), ("∩", r"$\cap$"),
    ("≤", r"$\leq$"), ("≥", r"$\geq$"),
    ("≪", r"$\ll$"), ("≫", r"$\gg$"),
    ("≈", r"$\approx$"), ("≠", r"$\neq$"),
    ("∈", r"$\in$"), ("∉", r"$\notin$"),
    ("⊂", r"$\subset$"), ("⊆", r"$\subseteq$"),
    ("⊃", r"$\supset$"), ("⊇", r"$\supseteq$"),
    ("⊨", r"$\models$"), ("⊥", r"$\perp$"),
    ("∀", r"$\forall$"), ("∃", r"$\exists$"), ("∅", r"$\emptyset$"),
    ("∞", r"$\infty$"),
    ("‖", r"$\|$"), ("∖", r"$\setminus$"),
    ("⟨", r"$\langle$"), ("⟩", r"$\rangle$"),
    ("⋆", r"$\star$"),
    # U+2212 (true minus) — separate from hyphen-minus; render as math minus
    ("−", r"$-$"),
    # Superscripts
    ("²", r"$^{2}$"), ("³", r"$^{3}$"),
    # Combining macron: drop standalone — emitting it produces garbage
    ("\u0304", r""),
    # Punctuation
    ("–", r"--"), ("—", r"---"), ("…", r"\ldots{}"),
    ("’", "'"), ("‘", "'"), ("“", r"``"), ("”", r"''"),
    ("§", r"\S{}"),
]


def apply_unicode_subs(s: str) -> str:
    for u, t in _PDFLATEX_UNICODE_MAP:
        s = s.replace(u, t)
    return s


# ---------------------------------------------------------------------------
# Renderer
# ---------------------------------------------------------------------------


@dataclass
class RenderOptions:
    engine: str = "lualatex"  # lualatex | xelatex | pdflatex
    include_appendix: bool = True
    bib_path: Path | None = None  # if set, also emit a .bib file
    include_toc: bool = False  # if True, emit \tableofcontents after title block


class LatexRenderer:
    def __init__(self, wb: Workbook, opts: RenderOptions):
        self.wb = wb
        self.opts = opts
        self.lines: list[str] = []
        # Citation-key cache (Work qid -> bib key)
        self._bibkeys: dict[str, str] = {}
        # Tally of what was rendered (for the build report on stderr)
        self.tally: dict[str, int] = defaultdict(int)

    # -- output helpers ---------------------------------------------------

    def emit(self, *parts: str) -> None:
        for p in parts:
            self.lines.append(p)

    # Primitive types rendered as description-list items (no LaTeX counter).
    # References to these targets are emitted as ``\hyperlink{}{}`` against
    # explicit ``\hypertarget`` anchors; using ``\autoref`` would produce
    # ``??`` because the items have no resolvable label-bound counter.
    _HYPERLINK_TYPE_PREFIXES = (
        "acad:Concept:",
        "acad:Theorist:",
        "acad:PaperRelation:",
    )

    @classmethod
    def _is_hyperlink_target(cls, qid: str) -> bool:
        return any(qid.startswith(p) for p in cls._HYPERLINK_TYPE_PREFIXES)

    @staticmethod
    def _display_name(fv: dict) -> str | None:
        return (
            fv.get("label")
            or fv.get("fullName")
            or fv.get("name")
            or fv.get("familyName")
        )

    def _autoref(self, ref: str) -> str | None:
        """Resolve a primitive reference (either a qualified id or a
        ``field_values.id`` slug) into an LaTeX cross-reference. Returns
        ``\\autoref{...}`` for targets that are bound to a numbered counter
        (sections, claims, equations, definitions, findings, limitations,
        errata, methods, theories) and ``\\hyperlink{...}{name}`` for
        unnumbered glossary-style targets (concepts, theorists,
        paper-relations). Returns ``None`` if the reference is unknown.
        """
        target = self.wb.resolve(ref)
        if target is None:
            return None
        label = safe_label(target["id"])
        if self._is_hyperlink_target(target["id"]):
            fv = target.get("field_values", {}) or {}
            name = self._display_name(fv) or target["id"]
            return rf"\hyperlink{{{label}}}{{{self.text(name)}}}"
        return rf"\autoref{{{label}}}"

    def _reference_or_excerpt(self, ref: str, max_chars: int = 80) -> str:
        """Return a cross-reference plus a short label-or-statement excerpt
        for a primitive reference. For glossary-style targets (concepts,
        theorists, paper-relations) the cross-reference is a hyperlink
        carrying the target's display name (the excerpt collapses into the
        link text). For numbered targets the form is
        ``\\autoref{...} (\\textit{excerpt})``. Falls back to a bare
        escaped string when the reference can't be resolved.
        """
        target = self.wb.resolve(ref)
        if target is None:
            return self.text(ref)
        label = safe_label(target["id"])
        fv = target.get("field_values", {}) or {}
        if self._is_hyperlink_target(target["id"]):
            name = self._display_name(fv) or target["id"]
            return rf"\hyperlink{{{label}}}{{\textit{{{self.text(name)}}}}}"
        excerpt = (
            self._display_name(fv)
            or fv.get("statement")
            or fv.get("body")
            or target["id"]
        )
        if isinstance(excerpt, str) and len(excerpt) > max_chars:
            excerpt = excerpt[:max_chars].rstrip() + "…"
        return (
            rf"\autoref{{{label}}} "
            rf"(\textit{{{self.text(excerpt)}}})"
        )

    def text(self, s: str | None) -> str:
        """Escape text content for inclusion in LaTeX prose.

        Order:
          1. tex_escape  — handles \\, {, }, $, &, #, %, _, ^, ~
          2. Unicode subs — wrap math symbols (𝓕, ≫, →, ∑, ...) in
             ``$...$``. This makes the output engine-independent: even
             with lualatex + unicode-math, the body fonts (Latin Modern
             Roman) lack many of these glyphs, so wrapping them in math
             mode where a math font carries the glyph is the correct
             typesetting choice anyway.
        """
        if s is None:
            return ""
        out = tex_escape(s)
        out = apply_unicode_subs(out)
        return out

    # -- main entrypoint -------------------------------------------------

    def render(self) -> str:
        paper_qid = self.wb.paper_qid()
        if not paper_qid:
            raise SchemaError("No primitive of kind 'Paper' found in instance.")
        paper = self.wb.primitives[paper_qid]

        self._render_disclaimer_comment()
        self._render_preamble(paper)
        self.emit(r"\begin{document}")
        self._render_titlepage(paper, paper_qid)
        self._render_abstract(paper)
        if self.opts.include_toc:
            self.emit(r"\tableofcontents", r"\newpage", "")
        self._render_body(paper_qid)
        if self.opts.include_appendix:
            self._render_appendix(paper_qid)
        self._render_bibliography(paper_qid)
        self.emit(r"\end{document}")

        return "\n".join(self.lines) + "\n"

    # -- preamble & disclaimer ------------------------------------------

    def _render_disclaimer_comment(self) -> None:
        wb_meta = self.wb.raw.get("workbook", {}) or {}
        self.emit(
            "% =====================================================================",
            "% Auto-generated by fdpm_to_latex.py.",
            "% This document is a mechanical transcription of an FDPM JSON instance.",
            "% No statement, definition, equation, or citation rendered here has been",
            "% independently verified. Any content not backed by a corresponding",
            "% field in the source instance may be invalid, erroneous, or",
            "% hallucinated at the level of the instance itself.",
            f"% Workbook id      : {wb_meta.get('id', '[missing]')}",
            f"% Workbook name    : {wb_meta.get('name', '[missing]')}",
            f"% Workbook profile : {wb_meta.get('profile_id', '[missing]')}",
            f"% Workbook revision: {wb_meta.get('revision', '[missing]')}",
            f"% Source created   : {wb_meta.get('created_at', '[missing]')}",
            f"% Renderer engine  : {self.opts.engine}",
            "% =====================================================================",
            "",
        )

    def _render_preamble(self, paper: dict) -> None:
        fv = paper.get("field_values", {}) or {}
        title = fv.get("title") or "[missing title]"

        self.emit(r"\documentclass[11pt,a4paper]{article}")

        if self.opts.engine in ("lualatex", "xelatex"):
            self.emit(
                r"\usepackage{fontspec}",
                # unicode-math supersedes amssymb (and conflicts with it).
                r"\usepackage{unicode-math}",
            )
            math_packages = r"\usepackage{amsmath, amsthm}"
        else:
            # pdflatex
            self.emit(
                r"\usepackage[utf8]{inputenc}",
                r"\usepackage[T1]{fontenc}",
                r"\usepackage{textcomp}",
                r"\usepackage{lmodern}",
            )
            math_packages = r"\usepackage{amsmath, amssymb, amsthm}"

        self.emit(
            r"\usepackage[a4paper,margin=2.5cm]{geometry}",
            math_packages,
            r"\usepackage{mathtools}",
            r"\usepackage{graphicx}",
            r"\usepackage{hyperref}",
            # cleveref must come AFTER hyperref
            r"\usepackage[capitalise,noabbrev]{cleveref}",
            r"\usepackage{xcolor}",
            r"\usepackage{enumitem}",
            r"\usepackage{csquotes}",
            r"\usepackage{tcolorbox}",
            r"\tcbuselibrary{breakable,skins}",
            r"\usepackage{microtype}",
            r"\usepackage{parskip}",
            "",
            r"\hypersetup{",
            r"    colorlinks=true,",
            r"    linkcolor=blue!50!black,",
            r"    citecolor=green!50!black,",
            r"    urlcolor=blue!50!black",
            r"}",
            "",
            # Theorem-like environments for Claim/Definition/Finding rendering.
            # Each FDPM Claim 'kind' maps to one of: claim, postulate,
            # prediction, assumption (predictions in particular get their own
            # counter so they're visually distinct from supporting claims).
            r"\theoremstyle{definition}",
            r"\newtheorem{fdpmdefn}{Definition}[section]",
            r"\theoremstyle{plain}",
            r"\newtheorem{fdpmclaim}{Claim}[section]",
            r"\newtheorem{fdpmpostulate}[fdpmclaim]{Postulate}",
            r"\newtheorem{fdpmprediction}[fdpmclaim]{Prediction}",
            r"\newtheorem{fdpmassumption}[fdpmclaim]{Assumption}",
            r"\newtheorem{fdpmfinding}[fdpmclaim]{Finding}",
            r"\theoremstyle{remark}",
            r"\newtheorem*{fdpmlimit}{Limitation}",
            r"\newtheorem*{fdpmevidence}{Evidence}",
            r"\newtheorem*{fdpmerratum}{Erratum}",
            "",
            # Block-quote environment for Quotation primitives.
            r"\newenvironment{fdpmquote}[1][]{%",
            r"  \begin{quote}\itshape\small",
            r"  \ifx\\#1\\\else\textbf{[#1]}\quad\fi",
            r"}{\end{quote}}",
            "",
            # Frame for tables whose cells are not encoded in the instance.
            r"\newtcolorbox{fdpmtablebox}[2][]{",
            r"  colback=gray!5, colframe=gray!50, breakable,",
            r"  fonttitle=\bfseries, title=#2, #1",
            r"}",
            "",
            # Frame for the paper-metadata block (keywords, epistemic method).
            r"\newtcolorbox{fdpmmetabox}[1][]{",
            r"  colback=blue!2, colframe=blue!30, breakable,",
            r"  left=4pt, right=4pt, top=4pt, bottom=4pt, #1",
            r"}",
            "",
            rf"\title{{{self.text(title)}}}",
            r"\date{}",
            "",
        )

    # -- title page ------------------------------------------------------

    def _render_titlepage(self, paper: dict, paper_qid: str) -> None:
        fv = paper.get("field_values", {}) or {}
        title = fv.get("title") or "[missing title]"
        subtitle = fv.get("subtitle")

        # Authors: every Author primitive whose AuthorPaper points at this
        # paper. Sort by 'position' enum (first / middle / last) so the by-line
        # order matches the paper's intended author sequence.
        position_order = {"first": 0, "middle": 1, "last": 2}

        def _author_sort_key(aqid: str) -> tuple:
            afv = (self.wb.primitives.get(aqid, {}).get("field_values") or {})
            return (
                position_order.get(afv.get("position", ""), 99),
                afv.get("familyName") or afv.get("fullName") or aqid,
            )

        author_qids = sorted(
            self.wb.inc(paper_qid, "AuthorPaper"), key=_author_sort_key
        )
        author_blocks: list[str] = []
        for aqid in author_qids:
            a = self.wb.primitives.get(aqid, {})
            afv = a.get("field_values", {}) or {}
            name = afv.get("fullName") or " ".join(
                filter(None, [afv.get("givenNames"), afv.get("familyName")])
            ) or "[missing author name]"
            block_parts: list[str] = [self.text(name)]

            # Affiliations: institution + department + country if present.
            affil_qids = self.wb.out(aqid, "AuthorAffiliations")
            affil_lines: list[str] = []
            for aff_qid in affil_qids:
                aff_fv = (self.wb.primitives.get(aff_qid, {}).get("field_values") or {})
                pieces = [
                    aff_fv.get("institution"),
                    aff_fv.get("department"),
                    aff_fv.get("country"),
                ]
                rendered = ", ".join(p for p in pieces if p)
                if rendered:
                    affil_lines.append(rendered)
            if affil_lines:
                block_parts.append(r"\small " + self.text("; ".join(affil_lines)))

            # Optional author metadata.
            meta_bits: list[str] = []
            role = afv.get("role")
            if role:
                meta_bits.append(rf"\textit{{role:}} {self.text(role)}")
            orcid = afv.get("orcid")
            if orcid:
                meta_bits.append(rf"ORCID: \href{{https://orcid.org/{self.text(orcid)}}}{{{self.text(orcid)}}}")
            email = afv.get("email")
            if email:
                meta_bits.append(rf"\href{{mailto:{self.text(email)}}}{{{self.text(email)}}}")
            if meta_bits:
                block_parts.append(r"\footnotesize " + " · ".join(meta_bits))

            contributions = afv.get("contributions") or []
            if contributions:
                block_parts.append(
                    r"\footnotesize\textit{contributions:} "
                    + self.text(", ".join(contributions))
                )

            author_blocks.append(r" \\ ".join(block_parts))
            self.tally["authors"] += 1

        if author_blocks:
            self.emit(r"\author{" + r" \and ".join(author_blocks) + "}")
        else:
            self.emit(r"\author{}")

        self.emit(r"\maketitle")

        if subtitle:
            self.emit(
                r"\begin{center}",
                r"\large\itshape " + self.text(subtitle),
                r"\end{center}",
                "",
            )

    # -- abstract --------------------------------------------------------

    def _render_abstract(self, paper: dict) -> None:
        fv = paper.get("field_values", {}) or {}
        abstract = fv.get("abstract")
        if abstract:
            self.emit(
                r"\begin{abstract}",
                self.text(abstract),
                r"\end{abstract}",
                "",
            )
        self._render_paper_metadata(paper)

    def _render_paper_metadata(self, paper: dict) -> None:
        """Render the Paper's secondary metadata (keywords, epistemic
        method, format, language, version, DOI) as a compact info block
        immediately after the abstract."""
        fv = paper.get("field_values", {}) or {}
        rows: list[tuple[str, str]] = []
        if fv.get("epistemicMethod"):
            rows.append(("Epistemic method", str(fv["epistemicMethod"])))
        if fv.get("format"):
            rows.append(("Format", str(fv["format"])))
        if fv.get("language"):
            rows.append(("Language", str(fv["language"])))
        if fv.get("version"):
            rows.append(("Version", str(fv["version"])))
        if fv.get("doi"):
            rows.append(("DOI", str(fv["doi"])))
        if fv.get("license"):
            rows.append(("License", str(fv["license"])))
        if fv.get("sourceDocument"):
            rows.append(("Source document", str(fv["sourceDocument"])))
        keywords = fv.get("keywords") or []
        if not rows and not keywords:
            return
        self.emit(r"\begin{fdpmmetabox}")
        if rows:
            self.emit(r"\begin{description}[leftmargin=*,labelsep=0.5em,itemsep=0pt]")
            for label, value in rows:
                self.emit(
                    rf"\item[\textbf{{{self.text(label)}:}}] {self.text(value)}"
                )
            self.emit(r"\end{description}")
        if keywords:
            kw_text = ", ".join(str(k) for k in keywords)
            self.emit(
                rf"\textbf{{Keywords:}} \textit{{{self.text(kw_text)}}}.",
            )
        self.emit(r"\end{fdpmmetabox}", "")

    # -- body: sections in order, with content placed inside ------------

    def _render_body(self, paper_qid: str) -> None:
        # Top-level sections of this paper (SectionPaper points to paper,
        # no SectionParent edge OR parent is outside this paper).
        section_qids = self.wb.inc(paper_qid, "SectionPaper")
        # Roots: sections with no SectionParent
        roots = [s for s in section_qids if not self.wb.out(s, "SectionParent")]
        roots.sort(key=self._section_sort_key)
        for sqid in roots:
            self._render_section(sqid, level=0)

    def _section_sort_key(self, sqid: str) -> tuple:
        fv = (self.wb.primitives.get(sqid, {}).get("field_values") or {})
        order = fv.get("order")
        if isinstance(order, (int, float)):
            return (0, order, sqid)
        if isinstance(order, str):
            # Try lex order on the string
            return (1, order, sqid)
        return (2, 0, sqid)

    def _render_section(self, section_qid: str, level: int) -> None:
        sec = self.wb.primitives.get(section_qid, {})
        fv = sec.get("field_values", {}) or {}
        title = fv.get("title") or fv.get("label") or "[missing section title]"
        label = safe_label(section_qid)
        cmd = self._section_command(level)
        self.emit(
            f"{cmd}{{{self.text(title)}}}",
            rf"\label{{{label}}}",
            "",
        )
        self.tally["sections"] += 1

        body = fv.get("bodyText")
        if body:
            # Split on blank lines so logical paragraphs in the source
            # become separate LaTeX paragraphs. Single newlines collapse
            # to spaces (LaTeX default).
            paragraphs = [p.strip() for p in re.split(r"\n\s*\n", body) if p.strip()]
            for para in paragraphs:
                self.emit(self.text(para), "")
        else:
            self.emit(r"\textit{[missing: section body text not present in instance]}", "")

        # Quotations placed in this section (block-quoted from cited works)
        for qqid in self.wb.inc(section_qid, "QuotationSection"):
            self._render_quotation(qqid)

        # Footnotes attached to this section — emitted as a small list.
        footnote_qids = self.wb.inc(section_qid, "FootnoteSection")
        if footnote_qids:
            self._render_footnotes(footnote_qids)

        # Figures placed in this section
        for fqid in self.wb.inc(section_qid, "FigureSection"):
            self._render_figure(fqid)

        # Definitions placed in this section
        for did in self.wb.inc(section_qid, "DefinitionSection"):
            self._render_definition(did)

        # Equations placed in this section
        for eqid in self.wb.inc(section_qid, "EquationSection"):
            self._render_equation(eqid)

        # Tables placed in this section
        for tqid in self.wb.inc(section_qid, "TableSection"):
            self._render_table(tqid)

        # Claims placed in this section
        for cqid in self.wb.inc(section_qid, "ClaimSection"):
            self._render_claim(cqid)

        # Findings placed in this section (proposition-B has these)
        for fqid in self.wb.inc(section_qid, "FindingSection"):
            self._render_finding(fqid)

        # Citations attached at the section level (not already pulled
        # into a claim) — emit a "\cite{...}" cluster as a footnote so
        # the reference appears in the bibliography.
        section_cites = self.wb.inc(section_qid, "CitationCitingSection")
        section_cite_keys = []
        for cite_qid in section_cites:
            # Skip if this citation also has a CitationCitingClaim
            # (already rendered with the claim).
            if self.wb.out(cite_qid, "CitationCitingClaim"):
                continue
            key = self._bibkey_for_citation(cite_qid)
            if key:
                section_cite_keys.append(key)
        if section_cite_keys:
            self.emit(
                r"\par\noindent\textit{Section references:} "
                + ", ".join(rf"\cite{{{k}}}" for k in section_cite_keys)
                + ".",
                "",
            )

        # Recurse into child sections
        children = self.wb.inc(section_qid, "SectionParent")
        children.sort(key=self._section_sort_key)
        for ch in children:
            self._render_section(ch, level=level + 1)

    @staticmethod
    def _section_command(level: int) -> str:
        return {
            0: r"\section",
            1: r"\subsection",
            2: r"\subsubsection",
            3: r"\paragraph",
        }.get(level, r"\subparagraph")

    # -- definitions, equations, claims, tables, findings ---------------

    def _render_definition(self, defn_qid: str) -> None:
        d = self.wb.primitives.get(defn_qid, {})
        fv = d.get("field_values", {}) or {}
        # Get the concept this defines (via DefinitionConcept)
        concept_qids = self.wb.out(defn_qid, "DefinitionConcept")
        concept_label = ""
        if concept_qids:
            c = self.wb.primitives.get(concept_qids[0], {})
            concept_label = (c.get("field_values", {}) or {}).get("label") or ""
        body = fv.get("body") or "[missing definition body]"
        prov = fv.get("provenance")
        canonical = ""
        if concept_qids:
            c = self.wb.primitives.get(concept_qids[0], {})
            canonical = (c.get("field_values", {}) or {}).get("canonicalForm") or ""

        label = safe_label(defn_qid)
        title = self.text(concept_label) if concept_label else "Definition"
        self.emit(
            rf"\begin{{fdpmdefn}}[{title}]\label{{{label}}}",
        )
        if canonical:
            self.emit(rf"\textbf{{Canonical form:}} {self.text(canonical)}.\\")
        self.emit(self.text(body))
        if prov:
            self.emit(rf"\\ \textit{{Provenance:}} {self.text(prov)}.")
        # DefinitionCitedFrom (proposition-B uses this)
        cited_from = self.wb.out(defn_qid, "DefinitionCitedFrom")
        if cited_from:
            keys = [self._bibkey_for_work(w) for w in cited_from]
            keys = [k for k in keys if k]
            if keys:
                self.emit(
                    rf"\\ \textit{{Cited from:}} "
                    + ", ".join(rf"\cite{{{k}}}" for k in keys)
                    + "."
                )
        self.emit(r"\end{fdpmdefn}", "")
        self.tally["definitions"] += 1

    def _render_equation(self, eq_qid: str) -> None:
        e = self.wb.primitives.get(eq_qid, {})
        fv = e.get("field_values", {}) or {}
        tex_body = fv.get("tex")
        label = safe_label(eq_qid)
        eq_label = fv.get("label")
        role = fv.get("role")

        if eq_label:
            self.emit(rf"\noindent\textbf{{{self.text(eq_label)}}}" + (rf" \textit{{({self.text(role)})}}" if role else "") + ":")
        if tex_body:
            self.emit(
                r"\begin{equation}",
                rf"\label{{{label}}}",
                tex_body,
                r"\end{equation}",
            )
        else:
            self.emit(r"\textit{[missing: equation has no `tex` field]}")

        # Derivation annotations — autoref hyperlinks where targets exist.
        derivs = self.wb.out(eq_qid, "EquationDerivesFrom")
        postulates = self.wb.out(eq_qid, "EquationFromPostulates")
        annotations: list[str] = []
        if derivs:
            annotations.append(
                "derives from "
                + "; ".join(self._reference_or_excerpt(q, max_chars=60) for q in derivs)
            )
        if postulates:
            annotations.append(
                "via postulate(s): "
                + "; ".join(self._reference_or_excerpt(q, max_chars=80) for q in postulates)
            )
        if annotations:
            self.emit(
                r"\par\small\textit{Provenance:} "
                + "; ".join(annotations)
                + r".\normalsize"
            )
        self.emit("")
        self.tally["equations"] += 1

    def _render_claim(self, claim_qid: str) -> None:
        c = self.wb.primitives.get(claim_qid, {})
        fv = c.get("field_values", {}) or {}
        kind = (fv.get("kind") or "claim").lower()
        env = {
            "postulate": "fdpmpostulate",
            "prediction": "fdpmprediction",
            "assumption": "fdpmassumption",
        }.get(kind, "fdpmclaim")
        statement = fv.get("statement") or "[missing claim statement]"
        status = fv.get("lifecycleStatus")
        label = safe_label(claim_qid)

        self.emit(rf"\begin{{{env}}}\label{{{label}}}")
        self.emit(self.text(statement))

        # Citations specifically attached to this claim
        cite_keys = []
        for cite_qid in self.wb.inc(claim_qid, "CitationCitingClaim"):
            k = self._bibkey_for_citation(cite_qid)
            if k:
                cite_keys.append(k)
        if cite_keys:
            self.emit(r"\par\noindent\textit{Supporting citations:} "
                      + ", ".join(rf"\cite{{{k}}}" for k in cite_keys) + ".")

        # ClaimDerivesFrom — emit autoref hyperlinks when the target is
        # in this paper; fall back to a truncated statement otherwise.
        derivs = self.wb.out(claim_qid, "ClaimDerivesFrom")
        if derivs:
            self.emit(
                r"\par\noindent\textit{Derives from:} "
                + "; ".join(self._reference_or_excerpt(q) for q in derivs)
                + "."
            )

        # ClaimCounterReads — adversarial / counter-reading lineage.
        counters = self.wb.out(claim_qid, "ClaimCounterReads")
        if counters:
            self.emit(
                r"\par\noindent\textit{Counter-reads:} "
                + "; ".join(self._reference_or_excerpt(q) for q in counters)
                + "."
            )

        # ClaimSupersededBy
        for s_qid in self.wb.out(claim_qid, "ClaimSupersededBy"):
            ref = self._autoref(s_qid) or self._reference_or_excerpt(s_qid)
            self.emit(r"\par\noindent\textit{Superseded by:} " + ref + ".")

        # Evidence supporting this claim
        evidence_qids = self.wb.inc(claim_qid, "EvidenceSupports")
        for ev_qid in evidence_qids:
            ev = self.wb.primitives.get(ev_qid, {})
            ev_fv = ev.get("field_values", {}) or {}
            summary = ev_fv.get("summary") or "[missing evidence summary]"
            kind = ev_fv.get("kind")
            kind_str = rf" \textit{{({self.text(kind)})}}" if kind else ""
            # Linked work, if any
            work_qids = self.wb.out(ev_qid, "EvidenceWork")
            work_keys = [self._bibkey_for_work(w) for w in work_qids]
            work_keys = [k for k in work_keys if k]
            cite_str = ""
            if work_keys:
                cite_str = " " + ", ".join(rf"\cite{{{k}}}" for k in work_keys)
            self.emit(
                r"\par\noindent\textit{Evidence:}" + kind_str + " "
                + self.text(summary) + cite_str + "."
            )

        if status:
            self.emit(rf"\par\noindent\textit{{Lifecycle status:}} {self.text(status)}.")

        self.emit(rf"\end{{{env}}}", "")
        self.tally["claims"] += 1

    def _render_table(self, table_qid: str) -> None:
        t = self.wb.primitives.get(table_qid, {})
        fv = t.get("field_values", {}) or {}
        title = fv.get("label") or "Table"
        caption = fv.get("caption")
        alt = fv.get("altText")
        rows = fv.get("rowCount")
        cols = fv.get("columnCount")
        # The FDPM instance carries table *metadata*, not cell content.
        # We render that metadata honestly, without inventing cells.
        self.emit(rf"\begin{{fdpmtablebox}}{{{self.text(title)}}}")
        meta_bits = []
        if rows is not None:
            meta_bits.append(f"rows = {rows}")
        if cols is not None:
            meta_bits.append(f"columns = {cols}")
        if meta_bits:
            self.emit(rf"\textit{{Shape: {', '.join(meta_bits)}.}}\par")
        self.emit(r"\textbf{Caption.} " + self.text(caption or "[missing caption]"))
        if alt:
            self.emit(r"\par\textbf{Alt text.} " + self.text(alt))
        self.emit(
            r"\par\textbf{Note.} Cell-level table content is not encoded in this "
            r"FDPM instance; only the table's metadata (caption, alt text, shape) "
            r"is rendered here.",
            r"\end{fdpmtablebox}",
            "",
        )
        self.tally["tables"] += 1

    def _render_finding(self, finding_qid: str) -> None:
        f = self.wb.primitives.get(finding_qid, {})
        fv = f.get("field_values", {}) or {}
        label = safe_label(finding_qid)
        statement = fv.get("statement") or fv.get("body") or "[missing finding body]"
        outcome = fv.get("outcome")
        self.emit(
            rf"\begin{{fdpmfinding}}\label{{{label}}}",
            self.text(statement),
        )
        if outcome:
            self.emit(rf"\par\noindent\textit{{Outcome:}} {self.text(outcome)}.")
        # Supporting evidence via FindingSupportedBy
        for ev_qid in self.wb.out(finding_qid, "FindingSupportedBy"):
            ev = self.wb.primitives.get(ev_qid, {})
            ev_fv = ev.get("field_values", {}) or {}
            summary = ev_fv.get("summary") or ev_fv.get("statement") or "[missing]"
            kind = ev_fv.get("kind")
            kind_str = rf" \textit{{({self.text(kind)})}}" if kind else ""
            self.emit(
                r"\par\noindent\textit{Supported by:}" + kind_str + " "
                + self.text(summary) + "."
            )
        # FindingTestsHypothesis — link by autoref where possible
        for h_qid in self.wb.out(finding_qid, "FindingTestsHypothesis"):
            ref = self._autoref(h_qid) or "the referenced hypothesis"
            self.emit(r"\par\noindent\textit{Tests hypothesis:} " + ref + ".")
        # Citations attached to this finding
        cite_keys: list[str] = []
        for cite_qid in self.wb.inc(finding_qid, "CitationCitingFinding"):
            key = self._bibkey_for_citation(cite_qid)
            if key:
                cite_keys.append(key)
        if cite_keys:
            self.emit(
                r"\par\noindent\textit{Citations:} "
                + ", ".join(rf"\cite{{{k}}}" for k in cite_keys)
                + "."
            )
        self.emit(r"\end{fdpmfinding}", "")
        self.tally["findings"] += 1

    # -- quotations / footnotes / figures -------------------------------

    def _render_quotation(self, quotation_qid: str) -> None:
        q = self.wb.primitives.get(quotation_qid, {})
        fv = q.get("field_values", {}) or {}
        body = fv.get("body") or "[missing quotation body]"
        locator = fv.get("locator")
        # quotesFrom is a Work scalar ref; surface as a citation key.
        from_works = self.wb.out(quotation_qid, "QuotationQuotesFrom")
        cite_keys = [self._bibkey_for_work(w) for w in from_works]
        cite_keys = [k for k in cite_keys if k]
        head_bits: list[str] = []
        if cite_keys:
            head_bits.append(", ".join(rf"\cite{{{k}}}" for k in cite_keys))
        if locator:
            head_bits.append(self.text(locator))
        head = ", ".join(head_bits)
        self.emit(rf"\begin{{fdpmquote}}[{head}]")
        self.emit(self.text(body))
        self.emit(r"\end{fdpmquote}", "")
        self.tally["quotations"] += 1

    def _render_footnotes(self, footnote_qids: list[str]) -> None:
        """Render a block of section-level footnotes as a small list. LaTeX
        ``\\footnote`` is not used here because FDPM footnotes are not anchored
        to a particular inline position in the bodyText — they are
        section-scoped notes."""
        self.emit(r"\par\smallskip\noindent\textit{Notes for this section:}")
        self.emit(r"\begin{itemize}[leftmargin=*,itemsep=0pt]")
        for fqid in footnote_qids:
            fv = (self.wb.primitives.get(fqid, {}).get("field_values") or {})
            label = fv.get("label") or ""
            body = fv.get("body") or "[missing footnote body]"
            prefix = rf"\textbf{{{self.text(label)}}}: " if label else ""
            self.emit(rf"  \item {prefix}{self.text(body)}")
            self.tally["footnotes"] += 1
        self.emit(r"\end{itemize}", "")

    def _render_figure(self, figure_qid: str) -> None:
        f = self.wb.primitives.get(figure_qid, {})
        fv = f.get("field_values", {}) or {}
        label = safe_label(figure_qid)
        caption = fv.get("caption") or "[missing caption]"
        alt = fv.get("altText")
        image_ref = fv.get("imageRef")
        figure_label = fv.get("label") or "Figure"
        self.emit(r"\begin{figure}[ht]", r"  \centering")
        if image_ref:
            # The instance may store either a file path or an opaque ref.
            # We pass it through to \includegraphics; if it isn't a file the
            # engine will fail loudly rather than silently.
            self.emit(rf"  \includegraphics[max width=\linewidth,width=0.85\linewidth]{{{self.text(image_ref)}}}")
        else:
            self.emit(
                r"  \fbox{\parbox{0.85\linewidth}{\centering\textit{"
                + self.text(alt or "[image not embedded in instance]")
                + r"}}}"
            )
        self.emit(
            rf"  \caption{{\textbf{{{self.text(figure_label)}.}} "
            + self.text(caption) + "}",
            rf"  \label{{{label}}}",
            r"\end{figure}",
            "",
        )
        self.tally["figures"] += 1

    # -- appendix: theories, methods, concepts, theorists, limitations --

    def _render_appendix(self, paper_qid: str) -> None:
        # Collect appendix-eligible items
        methods = self.wb.inc(paper_qid, "MethodPaper")
        limitations = self.wb.inc(paper_qid, "LimitationPaper")
        theories = self.wb.by_kind.get("Theory", [])
        theorists = self.wb.by_kind.get("Theorist", [])
        concepts = self.wb.by_kind.get("Concept", [])

        if not any([methods, limitations, theories, theorists, concepts]):
            return

        self.emit(r"\appendix", "")

        if methods:
            self.emit(r"\section{Methods}", r"\label{appendix:methods}", "")
            for m_qid in methods:
                m = self.wb.primitives.get(m_qid, {})
                fv = m.get("field_values", {}) or {}
                name = fv.get("name") or "[unnamed method]"
                kind = fv.get("kind")
                proc = fv.get("procedure") or "[missing procedure]"
                self.emit(
                    rf"\subsection*{{{self.text(name)}}}",
                    rf"\label{{{safe_label(m_qid)}}}",
                )
                if kind:
                    self.emit(rf"\textit{{Kind: {self.text(kind)}.}}\par")
                self.emit(self.text(proc), "")
                self.tally["methods"] += 1

        if theories:
            self.emit(r"\section{Theories referenced}", r"\label{appendix:theories}", "")
            for th_qid in theories:
                th = self.wb.primitives.get(th_qid, {})
                fv = th.get("field_values", {}) or {}
                name = fv.get("name") or "[unnamed theory]"
                summary = fv.get("summary") or "[missing summary]"
                self.emit(
                    rf"\subsection*{{{self.text(name)}}}",
                    rf"\label{{{safe_label(th_qid)}}}",
                )
                # primaryTheorist link
                primary_qids = self.wb.out(th_qid, "TheoryPrimaryTheorist")
                if primary_qids:
                    refs = [self._reference_or_excerpt(q, max_chars=60) for q in primary_qids]
                    self.emit(rf"\textit{{Primary theorist:}} " + "; ".join(refs) + r".\par")
                # extendsTheory / respondsTo (typed lineage)
                ext_qids = self.wb.out(th_qid, "TheoryExtendsTheory")
                if ext_qids:
                    refs = [self._reference_or_excerpt(q, max_chars=60) for q in ext_qids]
                    self.emit(rf"\textit{{Extends:}} " + "; ".join(refs) + r".\par")
                resp_qids = self.wb.out(th_qid, "TheoryRespondsTo")
                if resp_qids:
                    refs = [self._reference_or_excerpt(q, max_chars=60) for q in resp_qids]
                    self.emit(rf"\textit{{Responds to:}} " + "; ".join(refs) + r".\par")
                self.emit(self.text(summary), "")
                self.tally["theories"] += 1

        if concepts:
            self.emit(r"\section{Glossary of concepts}", r"\label{appendix:concepts}", "")
            self.emit(r"\begin{description}")
            # Sort by label for stable, scannable output.
            def _ck(q: str) -> tuple:
                fv = (self.wb.primitives.get(q, {}).get("field_values") or {})
                return (str(fv.get("label") or q).lower(), q)
            for c_qid in sorted(concepts, key=_ck):
                c = self.wb.primitives.get(c_qid, {})
                fv = c.get("field_values", {}) or {}
                lbl = fv.get("label") or c_qid
                domain = fv.get("domain")
                cform = fv.get("canonicalForm")
                wikidata = fv.get("wikidataId")
                bits: list[str] = []
                if cform:
                    bits.append(rf"canonical form: {self.text(cform)}")
                if domain:
                    bits.append(rf"domain: {self.text(domain)}")
                if wikidata:
                    bits.append(
                        rf"Wikidata: \href{{https://www.wikidata.org/wiki/{self.text(wikidata)}}}{{{self.text(wikidata)}}}"
                    )
                # Lineage from ConceptBorrowsFrom / ConceptExtends relations.
                borrows = self.wb.out(c_qid, "ConceptBorrowsFrom")
                if borrows:
                    borrow_links: list[str] = []
                    for b_qid in borrows:
                        ref = self._autoref(b_qid)
                        if ref is None:
                            bfv = (self.wb.primitives.get(b_qid, {}).get("field_values") or {})
                            ref = self.text(bfv.get("fullName") or bfv.get("familyName") or b_qid)
                        borrow_links.append(ref)
                    bits.append("borrows from " + "; ".join(borrow_links))
                ext_concepts = self.wb.out(c_qid, "ConceptExtends")
                if ext_concepts:
                    bits.append(
                        "extends "
                        + "; ".join(
                            self._reference_or_excerpt(q, max_chars=40)
                            for q in ext_concepts
                        )
                    )
                self.emit(
                    rf"\hypertarget{{{safe_label(c_qid)}}}{{}}"
                    rf"\item[\textbf{{{self.text(lbl)}}}] "
                    + ("; ".join(bits) if bits else r"\textit{[no further data]}")
                    + "."
                )
                self.tally["concepts"] += 1
            self.emit(r"\end{description}", "")

        # PaperRelation primitives — companion-of / commentary-on / etc.
        paper_rels = self.wb.inc(paper_qid, "PaperRelationPaper")
        if paper_rels:
            self.emit(
                r"\section{Related papers}",
                r"\label{appendix:paper-relations}",
                "",
            )
            self.emit(r"\begin{description}")
            for pr_qid in paper_rels:
                pr = self.wb.primitives.get(pr_qid, {})
                fv = pr.get("field_values", {}) or {}
                kind = fv.get("kind") or "related-to"
                rationale = fv.get("rationale") or ""
                # The related Work, via PaperRelationRelatedWork.
                related_works = self.wb.out(pr_qid, "PaperRelationRelatedWork")
                titles: list[str] = []
                for w_qid in related_works:
                    w_fv = (self.wb.primitives.get(w_qid, {}).get("field_values") or {})
                    t = w_fv.get("title") or w_qid
                    key = self._bibkey_for_work(w_qid)
                    if key:
                        titles.append(rf"\cite{{{key}}} ({self.text(t)})")
                    else:
                        titles.append(self.text(t))
                body = "; ".join(titles) if titles else r"\textit{[no related work resolved]}"
                rat = rf" \textit{{{self.text(rationale)}}}" if rationale else ""
                self.emit(
                    rf"\hypertarget{{{safe_label(pr_qid)}}}{{}}"
                    rf"\item[\textbf{{{self.text(kind)}:}}] {body}.{rat}"
                )
                self.tally["paper_relations"] += 1
            self.emit(r"\end{description}", "")

        # Erratum primitives.
        errata = self.wb.inc(paper_qid, "ErratumPaper")
        if errata:
            self.emit(r"\section{Errata}", r"\label{appendix:errata}", "")
            for e_qid in errata:
                e = self.wb.primitives.get(e_qid, {})
                fv = e.get("field_values", {}) or {}
                kind = fv.get("kind") or "correction"
                title = fv.get("title") or kind.title()
                body = fv.get("body") or "[missing erratum body]"
                issued = fv.get("issuedDate")
                self.emit(rf"\begin{{fdpmerratum}}\label{{{safe_label(e_qid)}}}")
                self.emit(rf"\textbf{{{self.text(title)}}} \textit{{({self.text(kind)})}}.")
                if issued:
                    self.emit(rf"\par\textit{{Issued:}} {self.text(issued)}.")
                # Cross-references
                for rel_type, label in (
                    ("ErratumCorrectsSection", "Corrects section"),
                    ("ErratumCorrectsClaim", "Corrects claim"),
                    ("ErratumCorrectsFinding", "Corrects finding"),
                    ("ErratumCorrectsEquation", "Corrects equation"),
                ):
                    for target_qid in self.wb.out(e_qid, rel_type):
                        ref = self._autoref(target_qid) or self.text(target_qid)
                        self.emit(rf"\par\textit{{{label}:}} {ref}.")
                self.emit(r"\par " + self.text(body))
                self.emit(r"\end{fdpmerratum}", "")
                self.tally["errata"] += 1

        if theorists:
            self.emit(r"\section{Theorists referenced}", r"\label{appendix:theorists}", "")
            self.emit(r"\begin{description}")
            # Sort by family name when available
            def tkey(q: str) -> tuple:
                fv = self.wb.primitives.get(q, {}).get("field_values", {}) or {}
                return (fv.get("familyName") or fv.get("fullName") or q,)
            for t_qid in sorted(theorists, key=tkey):
                t = self.wb.primitives.get(t_qid, {})
                fv = t.get("field_values", {}) or {}
                name = fv.get("fullName") or fv.get("familyName") or t_qid
                by = fv.get("birthYear")
                dy = fv.get("deathYear")
                years = ""
                if by or dy:
                    years = f" ({by or '?'}–{dy or '?'})"
                self.emit(
                    rf"\hypertarget{{{safe_label(t_qid)}}}{{}}"
                    rf"\item[\textbf{{{self.text(name)}{self.text(years)}}}] \hfill"
                )
                self.tally["theorists"] += 1
            self.emit(r"\end{description}", "")

        if limitations:
            self.emit(r"\section{Limitations}", r"\label{appendix:limitations}", "")
            for l_qid in limitations:
                l = self.wb.primitives.get(l_qid, {})
                fv = l.get("field_values", {}) or {}
                statement = fv.get("statement") or "[missing limitation statement]"
                scope = fv.get("scope")
                self.emit(rf"\begin{{fdpmlimit}}\label{{{safe_label(l_qid)}}}")
                if scope:
                    self.emit(rf"\textit{{Scope: {self.text(scope)}.}}\par")
                self.emit(self.text(statement))
                self.emit(r"\end{fdpmlimit}", "")
                self.tally["limitations"] += 1

    # -- bibliography ---------------------------------------------------

    def _bibkey_for_work(self, work_qid: str) -> str | None:
        """Generate / cache a stable BibTeX key for a Work primitive."""
        if not work_qid or work_qid not in self.wb.primitives:
            return None
        if work_qid in self._bibkeys:
            return self._bibkeys[work_qid]
        # Strip "acad:Work:" prefix and sanitize
        local = work_qid.split(":", 2)[-1] if work_qid.startswith("acad:Work:") else work_qid
        key = re.sub(r"[^A-Za-z0-9]+", "_", local).strip("_") or "work"
        self._bibkeys[work_qid] = key
        return key

    def _bibkey_for_citation(self, cite_qid: str) -> str | None:
        """Resolve a Citation primitive to its cited Work's bib key."""
        works = self.wb.out(cite_qid, "CitationCitedWork")
        if not works:
            return None
        return self._bibkey_for_work(works[0])

    def _render_bibliography(self, paper_qid: str) -> None:
        """Render every Work primitive that is the target of some
        CitationCitedWork edge into a \\bibitem entry. Works that are
        not cited are omitted from the rendered bibliography (they
        remain in the JSON instance regardless)."""
        cited_works: dict[str, dict] = {}
        for cite_qid in self.wb.by_kind.get("Citation", []):
            for w_qid in self.wb.out(cite_qid, "CitationCitedWork"):
                if w_qid in self.wb.primitives:
                    cited_works[w_qid] = self.wb.primitives[w_qid]

        if not cited_works:
            return

        # Sort by author family name then year (stable).
        def sort_key(item: tuple[str, dict]) -> tuple:
            w_qid, w = item
            fv = w.get("field_values", {}) or {}
            authors = fv.get("authorsFreeText") or []
            first = authors[0] if authors else ""
            year = fv.get("year") or 0
            return (str(first).lower(), int(year) if str(year).isdigit() else 0, w_qid)

        items = sorted(cited_works.items(), key=sort_key)

        self.emit(
            r"\begin{thebibliography}{99}",
            r"\addcontentsline{toc}{section}{References}",
        )
        for w_qid, w in items:
            key = self._bibkey_for_work(w_qid)
            self.emit(rf"\bibitem{{{key}}} {self._format_work(w)}")
            self.tally["references"] += 1
        self.emit(r"\end{thebibliography}", "")

        # Optional standalone .bib output
        if self.opts.bib_path is not None:
            self._write_bibfile(items)

    def _format_work(self, w: dict) -> str:
        fv = w.get("field_values", {}) or {}
        authors = fv.get("authorsFreeText") or []
        year = fv.get("year")
        title = fv.get("title") or "[missing title]"
        venue = fv.get("venue")
        publisher = fv.get("publisher")
        kind = fv.get("kind")
        doi = fv.get("doi")
        isbn = fv.get("isbn")
        url = fv.get("url")
        parts: list[str] = []
        if authors:
            parts.append(self.text("; ".join(authors)))
        if year:
            parts.append(rf"({self.text(str(year))})")
        parts.append(rf"\textit{{{self.text(title)}}}")
        if venue:
            parts.append(self.text(venue))
        if publisher and publisher != venue:
            parts.append(self.text(publisher))
        if kind:
            parts.append(rf"[{self.text(kind)}]")
        if doi:
            parts.append(rf"DOI: \href{{https://doi.org/{self.text(doi)}}}{{{self.text(doi)}}}")
        if isbn:
            parts.append(rf"ISBN: {self.text(isbn)}")
        if url and not doi:
            parts.append(rf"\href{{{self.text(url)}}}{{{self.text(url)}}}")
        # Strip trailing periods so the joiner is the only period source.
        clean = [p[:-1] if p.endswith(".") else p for p in parts]
        return ". ".join(clean) + "."

    def _write_bibfile(self, items: Iterable[tuple[str, dict]]) -> None:
        """Emit a BibTeX file. Mapping rules:

          * ``Work.kind`` selects the BibTeX entry type.
          * ``Work.publisher`` always maps to ``publisher`` regardless of
            entry type. ``Work.venue`` maps to ``journal`` (article),
            ``booktitle`` (proceedings / incollection), or ``series`` /
            ``note`` (book, fallback).
          * ``Work.doi`` / ``isbn`` / ``url`` map to their canonical
            BibTeX fields when present.
        """
        assert self.opts.bib_path is not None
        bib_lines: list[str] = [
            "% Auto-generated by fdpm_to_latex.py; transcription only.",
            "",
        ]
        kind_map = {
            "journal-article": "article",
            "book": "book",
            "book-chapter": "incollection",
            "conference-paper": "inproceedings",
            "preprint": "misc",
            "report": "techreport",
            "thesis": "phdthesis",
            "newspaper-article": "article",
            "archival-document": "misc",
            "website": "online",
            "dataset": "misc",
            "software": "misc",
        }
        venue_field_map = {
            "article": "journal",
            "inproceedings": "booktitle",
            "incollection": "booktitle",
            "book": "series",
            "techreport": "institution",
        }
        for w_qid, w in items:
            fv = w.get("field_values", {}) or {}
            key = self._bibkey_for_work(w_qid) or "key"
            entry_type = kind_map.get(fv.get("kind") or "", "misc")
            fields: list[tuple[str, str]] = []
            if fv.get("authorsFreeText"):
                fields.append(("author", " and ".join(fv["authorsFreeText"])))
            if fv.get("title"):
                fields.append(("title", fv["title"]))
            if fv.get("year"):
                fields.append(("year", str(fv["year"])))
            if fv.get("publisher"):
                fields.append(("publisher", fv["publisher"]))
            if fv.get("venue"):
                vfield = venue_field_map.get(entry_type, "note")
                fields.append((vfield, fv["venue"]))
            if fv.get("doi"):
                fields.append(("doi", fv["doi"]))
            if fv.get("isbn"):
                fields.append(("isbn", fv["isbn"]))
            if fv.get("url"):
                fields.append(("url", fv["url"]))
            if fv.get("language"):
                fields.append(("language", fv["language"]))
            bib_lines.append(f"@{entry_type}{{{key},")
            for fname, fval in fields:
                fval_clean = str(fval).replace("{", "\\{").replace("}", "\\}")
                bib_lines.append(f"  {fname} = {{{fval_clean}}},")
            bib_lines.append("}\n")
        self.opts.bib_path.write_text("\n".join(bib_lines), encoding="utf-8")


# ---------------------------------------------------------------------------
# PDF compilation
# ---------------------------------------------------------------------------


class PdfBuildError(Exception):
    """Raised when the LaTeX engine fails to produce a PDF."""


def compile_pdf(
    tex_path: Path,
    *,
    engine: str,
    bib_path: Path | None,
    passes: int = 2,
    keep_aux: bool = False,
) -> Path:
    """Compile ``tex_path`` to a PDF in the same directory using ``engine``.

    The function runs the engine ``passes`` times to resolve cross-references
    (TOC, ``\\autoref``, ``\\cite``). When a separate ``.bib`` file is present
    the function does NOT invoke ``bibtex`` — the document uses
    ``thebibliography`` directly and the ``.bib`` is supplementary metadata.
    Auxiliary files (.aux, .log, .out, .toc, .lof, .lot) are removed unless
    ``keep_aux=True``.

    Returns the produced PDF path. Raises ``PdfBuildError`` on failure,
    including the tail of the engine log when available.
    """
    if shutil.which(engine) is None:
        raise PdfBuildError(
            f"{engine!r} not found on PATH. Install TeXLive / MiKTeX, or "
            f"choose a different --engine."
        )
    workdir = tex_path.parent
    base = tex_path.stem
    cmd = [
        engine,
        "-interaction=nonstopmode",
        "-halt-on-error",
        "-file-line-error",
        tex_path.name,
    ]
    last_log = ""
    for n in range(passes):
        proc = subprocess.run(
            cmd, cwd=workdir, capture_output=True, text=True, check=False
        )
        last_log = proc.stdout + proc.stderr
        if proc.returncode != 0:
            log_file = workdir / f"{base}.log"
            tail = ""
            if log_file.is_file():
                try:
                    tail_lines = log_file.read_text(
                        encoding="utf-8", errors="replace"
                    ).splitlines()[-40:]
                    tail = "\n".join(tail_lines)
                except OSError:
                    pass
            raise PdfBuildError(
                f"{engine} failed on pass {n + 1}/{passes} for {tex_path}.\n"
                f"--- log tail ---\n{tail or last_log[-2000:]}"
            )
    pdf_path = workdir / f"{base}.pdf"
    if not pdf_path.is_file():
        raise PdfBuildError(
            f"{engine} reported success but {pdf_path} was not produced.\n"
            f"--- last engine output ---\n{last_log[-2000:]}"
        )
    if not keep_aux:
        for ext in (".aux", ".log", ".out", ".toc", ".lof", ".lot", ".fls",
                    ".fdb_latexmk", ".synctex.gz"):
            (workdir / f"{base}{ext}").unlink(missing_ok=True)
    return pdf_path


# ---------------------------------------------------------------------------
# CLI
# ---------------------------------------------------------------------------


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(
        prog="fdpm_to_latex.py",
        description=(
            "Render an FDPM academic-paper JSON instance into a self-contained "
            "LaTeX document. Mechanical transcription only — no inferred content."
        ),
    )
    parser.add_argument("input", type=Path, help="Path to the FDPM JSON instance.")
    parser.add_argument(
        "-o", "--output", type=Path, default=None,
        help="Output .tex path (default: <input-basename>.tex).",
    )
    parser.add_argument(
        "--engine", choices=("lualatex", "xelatex", "pdflatex"), default="lualatex",
        help="Target TeX engine; affects preamble (default: lualatex).",
    )
    parser.add_argument(
        "--no-appendix", action="store_true",
        help="Skip the back-matter (methods, theories, glossary, theorists, limitations).",
    )
    parser.add_argument(
        "--toc", action="store_true",
        help="Emit a table of contents after the abstract.",
    )
    parser.add_argument(
        "--bib", type=Path, default=None,
        help="Also write a BibTeX file with the cited works.",
    )
    parser.add_argument(
        "--pdf", action="store_true",
        help=(
            "After writing the .tex, compile it to PDF with the chosen "
            "engine. Runs the engine twice to resolve cross-references. "
            "Auxiliary files are removed unless --keep-aux is set."
        ),
    )
    parser.add_argument(
        "--pdf-passes", type=int, default=2,
        help="Number of engine passes when compiling to PDF (default: 2).",
    )
    parser.add_argument(
        "--keep-aux", action="store_true",
        help="When compiling to PDF, retain .aux / .log / .toc auxiliary files.",
    )
    args = parser.parse_args(argv)

    if not args.input.is_file():
        print(f"error: file not found: {args.input}", file=sys.stderr)
        return 1

    try:
        wb = Workbook.load(args.input)
    except json.JSONDecodeError as e:
        print(f"error: invalid JSON in {args.input}: {e}", file=sys.stderr)
        return 1
    except SchemaError as e:
        print(f"error: {e}", file=sys.stderr)
        return 2

    opts = RenderOptions(
        engine=args.engine,
        include_appendix=not args.no_appendix,
        bib_path=args.bib,
        include_toc=args.toc,
    )

    try:
        renderer = LatexRenderer(wb, opts)
        tex = renderer.render()
    except SchemaError as e:
        print(f"error: {e}", file=sys.stderr)
        return 2

    out_path = args.output or args.input.with_suffix(".tex")
    out_path.write_text(tex, encoding="utf-8")

    # Build report on stderr.
    paper_qid = wb.paper_qid()
    paper_title = ""
    if paper_qid:
        paper_title = (wb.primitives[paper_qid].get("field_values") or {}).get("title", "")
    print(f"[ok] wrote {out_path}", file=sys.stderr)
    print(f"     paper: {paper_title}", file=sys.stderr)
    counts = renderer.tally
    print(
        f"     rendered: "
        f"{counts.get('sections', 0)} sections, "
        f"{counts.get('definitions', 0)} definitions, "
        f"{counts.get('equations', 0)} equations, "
        f"{counts.get('claims', 0)} claims, "
        f"{counts.get('findings', 0)} findings, "
        f"{counts.get('tables', 0)} tables, "
        f"{counts.get('methods', 0)} methods, "
        f"{counts.get('theories', 0)} theories, "
        f"{counts.get('concepts', 0)} concepts, "
        f"{counts.get('theorists', 0)} theorists, "
        f"{counts.get('limitations', 0)} limitations, "
        f"{counts.get('references', 0)} references.",
        file=sys.stderr,
    )
    if opts.bib_path is not None:
        print(f"[ok] wrote {opts.bib_path}", file=sys.stderr)

    if args.pdf:
        try:
            pdf_path = compile_pdf(
                out_path,
                engine=args.engine,
                bib_path=opts.bib_path,
                passes=args.pdf_passes,
                keep_aux=args.keep_aux,
            )
        except PdfBuildError as e:
            print(f"error: PDF build failed:\n{e}", file=sys.stderr)
            return 4
        print(f"[ok] wrote {pdf_path}", file=sys.stderr)
    return 0


if __name__ == "__main__":
    sys.exit(main())
