/**
 * AUTO-GENERATED by scripts/generate-build-from-transfer.ts.
 * Source: roadmap-v0.5.2.transfer.json
 *
 * Recreates the workbook through the @fdpm/cli SDK. Output is
 * deterministic per (source-transfer, generator-version, active-
 * profile) — re-running the generator on the same input yields a
 * byte-identical script, so CI can detect drift via `git diff`.
 *
 * Companion artifacts (regenerated together):
 *   build-roadmap-v0.5.2.primitives.ts  — PRIMITIVES array
 *   build-roadmap-v0.5.2.relations.ts   — RELATIONS array
 *   build-roadmap-v0.5.2.summary.md     — human summary, type counts, validity
 *
 * Transformations applied at generation time:
 *   - Relation field_values._metadata.* lifted to top-level fields.
 *   - Legacy _strength field dropped.
 *   - Primitive/relation revision fields omitted (SDK assigns fresh).
 *
 * Known-invalid primitives (78) and
 * known-invalid relations (0) are
 * enumerated below. They will fail §7 validation under the active
 * profile (oversized fields, id-format mismatches, enum mismatches,
 * etc.). Pass --skip-invalid to elide them from the commit. When
 * primitives are skipped, any relation pointing at a skipped id is
 * also elided automatically.
 *
 * Run (substitute the actual path to this file as needed):
 *   FDPM_DATA_DIR=/tmp/rebuild npx tsx <path-to>/build-roadmap-v0.5.2.ts
 *   FDPM_DATA_DIR=/tmp/rebuild npx tsx <path-to>/build-roadmap-v0.5.2.ts --skip-invalid
 */

import { openHost, defineProject } from "../src/sdk.js";
import { PRIMITIVES } from "./build-roadmap-v0.5.2.primitives.js";
import { RELATIONS } from "./build-roadmap-v0.5.2.relations.js";

const PROJECT_ID = "roadmap-v051";
const PROJECT_NAME = "Roadmap Unified v0.5.1";
// Profile id inlined from the source transfer. The generator does not
// import a typed PROFILE_ID constant from a specific plugin — that
// would tie the generated script to one profile only. If you rename
// this profile, regenerate.
const PROFILE_ID = "profile:formal-specification:3.0";

/**
 * Primitive ids whose field shapes are known to violate the active
 * profile's validation rules. Run with --skip-invalid to elide them.
 * The list is stable per generation; if the source transfer changes,
 * regenerate this script.
 */
const KNOWN_INVALID_PRIMITIVES = new Set<string>([
  "assumption:h:05.02",
  "assumption:h:19.01",
  "invariant:i-01.02",
  "invariant:i-01.05",
  "invariant:i-02.01",
  "invariant:i-02.03",
  "invariant:i-03.01",
  "invariant:i-03.02",
  "invariant:i-03.03",
  "invariant:i-04.01",
  "invariant:i-04.02",
  "invariant:i-05.01",
  "invariant:i-05.02",
  "invariant:i-05.03",
  "invariant:i-05.04",
  "invariant:i-06.01",
  "invariant:i-06.02",
  "invariant:i-07.01",
  "invariant:i-07.02",
  "invariant:i-07.03",
  "invariant:i-07.04",
  "invariant:i-07.05",
  "invariant:i-08.01",
  "invariant:i-08.02",
  "invariant:i-08.03",
  "invariant:i-08.04",
  "invariant:i-08.05",
  "invariant:i-09.01",
  "invariant:i-09.02",
  "invariant:i-10.01",
  "invariant:i-10.02",
  "invariant:i-10.03",
  "invariant:i-11.01",
  "invariant:i-11.02",
  "invariant:i-12.01",
  "invariant:i-12.02",
  "invariant:i-12.03",
  "invariant:i-12.04",
  "invariant:i-13.01",
  "invariant:i-13.02",
  "invariant:i-14.01",
  "invariant:i-14.02",
  "invariant:i-14.03",
  "invariant:i-15.01",
  "invariant:i-15.02",
  "invariant:i-16.01",
  "invariant:i-16.02",
  "invariant:i-16.03",
  "invariant:i-17.01",
  "invariant:i-17.02",
  "invariant:i-18.01",
  "invariant:i-18.03",
  "invariant:i-19.01",
  "invariant:i-20.01",
  "invariant:i-20.02",
  "invariant:i-21.01",
  "statecomp:s-activation",
  "statecomp:s-architecture",
  "statecomp:s-backend",
  "statecomp:s-cloud",
  "statecomp:s-compliance",
  "statecomp:s-data",
  "statecomp:s-design_system",
  "statecomp:s-foundation",
  "statecomp:s-identity",
  "statecomp:s-integrations",
  "statecomp:s-launch",
  "statecomp:s-launch_readiness",
  "statecomp:s-marketing",
  "statecomp:s-mobile",
  "statecomp:s-observability",
  "statecomp:s-performance",
  "statecomp:s-problem_frame",
  "statecomp:s-product_def",
  "statecomp:s-sales",
  "statecomp:s-security_audit",
  "statecomp:s-testing",
  "statecomp:s-web"
]);

/** Same, for relations (typically: enum mismatches on `kind`). */
const KNOWN_INVALID_RELATIONS = new Set<string>([]);

async function main() {
  const skipInvalid = process.argv.includes("--skip-invalid");
  const host = await openHost();
  const primitives = skipInvalid
    ? PRIMITIVES.filter((p) => !KNOWN_INVALID_PRIMITIVES.has(p.id))
    : PRIMITIVES;
  // Relations are elided in two cases when --skip-invalid is set:
  //   1. Their source or target points at a skipped primitive (avoids
  //      core:relation:source-missing / target-missing).
  //   2. They're explicitly in KNOWN_INVALID_RELATIONS (typically
  //      enum mismatches on `kind`).
  const presentIds = new Set(primitives.map((p) => p.id));
  let skippedRelByEnum = 0;
  let skippedRelByEndpoint = 0;
  const relations = skipInvalid
    ? RELATIONS.filter((r) => {
        if (KNOWN_INVALID_RELATIONS.has(r.id)) {
          skippedRelByEnum++;
          return false;
        }
        if (!presentIds.has(r.from) || !presentIds.has(r.to)) {
          skippedRelByEndpoint++;
          return false;
        }
        return true;
      })
    : RELATIONS;
  if (skipInvalid) {
    const skippedP = PRIMITIVES.length - primitives.length;
    if (skippedP > 0 || skippedRelByEnum > 0 || skippedRelByEndpoint > 0) {
      console.error(
        `--skip-invalid: skipped ${skippedP} primitive(s), ${skippedRelByEnum} relation(s) by KNOWN_INVALID, ${skippedRelByEndpoint} relation(s) by missing-endpoint cascade.`,
      );
    }
  }
  const result = await defineProject(host, {
    id: PROJECT_ID,
    name: PROJECT_NAME,
    profile: PROFILE_ID,
  })
    .primitives(primitives)
    .relations(relations)
    .commit({ rollbackOnError: true });
  console.log("Built workbook:", result.workbook_id);
  console.log("  primitives:", result.primitives_created);
  console.log("  relations: ", result.relations_created);
  console.log("  revision:  ", result.revision);
}

main().catch((e) => {
  console.error("FAILED:", e instanceof Error ? e.message : String(e));
  if (e && typeof e === "object" && "findings" in e) {
    console.error(
      "Findings:",
      JSON.stringify((e as { findings: unknown }).findings, null, 2),
    );
  }
  process.exit(1);
});
