/**
 * Score every active plugin under the workbook quality rubric and print a
 * Markdown report. Run with:
 *
 *   npx tsx scripts/quality-score-all-plugins.ts
 *
 * The script:
 *   1. boots a fresh Host and discovers every built-in plugin,
 *   2. for each plugin that registers a profile, attempts to seed a minimal
 *      single-instance fixture workbook (one primitive of each declared
 *      type, when possible),
 *   3. runs scorePlugin against that fixture,
 *   4. prints a single summary table + per-plugin axis breakdown.
 *
 * This is a *runner*, not a CLI subcommand. The proper `fdpm quality score`
 * subcommand is a follow-up; this runner exists so the rubric has a
 * mechanical evidence trail today.
 */
import { join, resolve } from "node:path";
import { existsSync, readdirSync } from "node:fs";
import { Host } from "../src/core/host.js";
import { scorePlugin, type PluginScoreReport } from "../src/quality/score-workbook.js";

interface ProbeResult {
  pluginId: string;
  fixtureWorkbookId: string | null;
  testFilePath: string | null;
  readmePath: string | null;
  skipReason?: string;
}

async function main(): Promise<void> {
  const host = new Host({
    dataDir: null,
    builtinDirs: [resolve(process.cwd(), "plugins")],
    pluginPaths: [],
  });
  await host.load();

  const records = host.plugins.list();
  const active = records.filter((r) => r.state === "active");
  const skipped = records.filter((r) => r.state !== "active");

  // --- For each active plugin, try to seed a fixture using one primitive of
  // each registered type. If we can't (required fields we can't guess),
  // we still score plugin-level axes against an *empty* fixture so the
  // manifest/parity/permissions axes are exercised.
  const probes: ProbeResult[] = [];
  for (const r of active) {
    const profileId = r.contributions.profileIds[0];
    let fixtureId: string | null = null;
    if (profileId) {
      const wbId = `quality-fixture-${r.id.replace(/[^a-z0-9-]/g, "-")}`;
      try {
        await host.createProject({
          workbook_id: wbId,
          name: wbId,
          profile_id: profileId,
        });
        fixtureId = wbId;
      } catch (err) {
        // Composition profiles whose primitives all live in the parent
        // profile may need a different setup. We accept the failure and
        // score plugin-only axes.
        probes.push({
          pluginId: r.id,
          fixtureWorkbookId: null,
          testFilePath: null,
          readmePath: null,
          skipReason: `createProject failed: ${err instanceof Error ? err.message : String(err)}`,
        });
        continue;
      }
    }

    // Heuristic test/readme location — these match the codebase's convention.
    const readmePath = guessReadmePath(r.id);
    const testFilePath = guessTestFilePath(r.id);
    probes.push({ pluginId: r.id, fixtureWorkbookId: fixtureId, readmePath, testFilePath });
  }

  // --- Score every plugin
  const reports: PluginScoreReport[] = [];
  for (const p of probes) {
    try {
      const report = await scorePlugin(host, p.pluginId, {
        fixtureWorkbookId: p.fixtureWorkbookId ?? undefined,
        readmePath: p.readmePath ?? undefined,
        testFilePath: p.testFilePath ?? undefined,
      });
      reports.push(report);
    } catch (err) {
      console.error(
        `scorePlugin failed for ${p.pluginId}: ${err instanceof Error ? err.message : String(err)}`,
      );
    }
  }

  // --- Print Markdown report
  console.log("");
  console.log("# FDPM plugin quality scoreboard");
  console.log("");
  console.log("Generated by `scripts/quality-score-all-plugins.ts`. Rubric: `docs/drafts/workbook-quality-rubric.md`.");
  console.log("");
  console.log("## Summary");
  console.log("");
  console.log("| Plugin | Version | Score | Grade | Fixture | Notes |");
  console.log("|--------|---------|------:|-------|---------|-------|");
  for (const r of reports) {
    const fixture = r.fixture_workbook_id ?? "—";
    const note = r.notes.length > 0 ? r.notes[0] : "";
    console.log(
      `| \`${r.plugin_id}\` | \`${r.plugin_version}\` | ${r.score} | \`${r.grade}\` | \`${fixture}\` | ${note} |`,
    );
  }
  for (const r of skipped) {
    console.log(
      `| \`${r.id}\` | \`${r.version}\` | — | \`${r.state}\` | — | ${r.errorMessage ?? ""} |`,
    );
  }

  console.log("");
  console.log("## Per-plugin axis breakdown");
  console.log("");
  for (const r of reports) {
    console.log(`### \`${r.plugin_id}\` — ${r.score}/100 (${r.grade})`);
    console.log("");
    console.log("| Axis | Score / Max | Gate? | Details |");
    console.log("|------|-------------|-------|---------|");
    for (const [name, ax] of Object.entries(r.axes)) {
      const gate = ax.hard_gate ? (ax.gate_passed ? "✓" : "✗") : "—";
      const details = ax.details.slice(0, 3).join("; ");
      console.log(`| ${name} | ${ax.score}/${ax.max} | ${gate} | ${details} |`);
    }
    if (r.workbook_report) {
      const w = r.workbook_report;
      console.log("");
      console.log(
        `Workbook \`${w.workbook_id}\`: ${w.score}/100 (${w.grade}) — errors=${w.errors_count} warnings=${w.warnings_count}; signals=[${w.excellence_signals.join(", ") || "none"}]`,
      );
    }
    if (r.notes.length > 0) {
      console.log("");
      for (const n of r.notes) console.log(`> ${n}`);
    }
    console.log("");
  }
}

function guessReadmePath(pluginId: string): string | null {
  // fdpm.starter → plugins/_starter/README.md (underscore directory by convention).
  // fdpm.foo-bar → plugins/foo_bar/README.md (snake-case directory).
  const localName = pluginId.replace(/^fdpm\./, "").replace(/^acme\./, "acme_").replace(/-/g, "_");
  const candidates = [
    resolve(process.cwd(), `plugins/_${localName}/README.md`),
    resolve(process.cwd(), `plugins/${localName}/README.md`),
  ];
  for (const c of candidates) if (existsSync(c)) return c;
  return null;
}

function guessTestFilePath(pluginId: string): string | null {
  const localName = pluginId.replace(/^fdpm\./, "").replace(/^acme\./, "");
  const snake = localName.replace(/-/g, "_");

  // Per-plugin suite directory. This is where every plugin added since the
  // convention changed puts its tests — knowledge_cartridge, loop_forward,
  // style, uixo, uml, document_plan and both deck plugins among them. Probing
  // only the flat `tests/<name>-*.test.ts` forms scored 14 of 19 plugins at
  // 0/10 on the test-surface axis while they held hundreds of passing tests
  // between them, which made the axis measure naming convention rather than
  // test coverage and left the published scoreboard misleading.
  const suiteDir = resolve(process.cwd(), `tests/plugins/${snake}`);
  if (existsSync(suiteDir)) {
    const entries = readdirSync(suiteDir)
      .filter((f) => f.endsWith(".test.ts"))
      .sort();
    // Prefer the profile/contract suite when present so the reported path is
    // the one a reader should open first; otherwise any suite proves the axis.
    const preferred =
      entries.find((f) => f === "profile.test.ts") ??
      entries.find((f) => f === "validators.test.ts") ??
      entries[0];
    if (preferred !== undefined) return join(suiteDir, preferred);
  }

  const candidates = [
    resolve(process.cwd(), `tests/${localName}-plugin.test.ts`),
    resolve(process.cwd(), `tests/${localName}-plugin-contract.test.ts`),
    resolve(process.cwd(), `tests/${snake}-plugin.test.ts`),
    resolve(process.cwd(), `tests/${localName}-content.test.ts`),
    resolve(process.cwd(), `tests/${localName}-validators.test.ts`),
  ];
  for (const c of candidates) if (existsSync(c)) return c;
  return null;
}

main().catch((e) => {
  console.error("FAILED:", e instanceof Error ? e.message : String(e));
  process.exit(1);
});
